[package]
name = "@forgegraph/foundation/resource-relations"
version = "0.1.0"
edition = "2027"
[dependencies.party]
path = "../party"
deploy = true
[dependencies.specification]
path = "../specification"
deploy = true
[dependencies.evidence]
path = "../evidence"
deploy = true
