-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE artifact (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_component (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  "next" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE artifact_content (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "upload_state" TEXT NOT NULL,
  "media_type" TEXT,
  "byte_count" INTEGER,
  "digest" TEXT,
  "upload_attempt" INTEGER,
  "staged_media_type" TEXT,
  "staged_byte_count" INTEGER,
  "content_generation" INTEGER,
  "sealed_generation" TEXT,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "artifact" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "media_type" TEXT NOT NULL,
  "byte_count" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "realization" TEXT,
  "components" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, artifact) REFERENCES artifact (tenant, id),
  FOREIGN KEY (tenant, content) REFERENCES artifact_content (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, realization) REFERENCES realization (tenant, id),
  FOREIGN KEY (tenant, components) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE evaluation_executor (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE evaluation_finish (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "run" TEXT NOT NULL,
  "start" TEXT,
  "outcome" TEXT NOT NULL,
  "finished_at" TEXT NOT NULL,
  "support" TEXT,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, run) REFERENCES evaluation_run (tenant, id),
  FOREIGN KEY (tenant, start) REFERENCES evaluation_start (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evaluation_quarantine (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "run" TEXT NOT NULL,
  "source_digest" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, run) REFERENCES evaluation_run (tenant, id)
);

CREATE TABLE evaluation_run (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "evaluation_set" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "executor" TEXT NOT NULL,
  "parent" TEXT,
  "depth" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, evaluation_set) REFERENCES evaluation_set (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, executor) REFERENCES evaluation_executor (tenant, id),
  FOREIGN KEY (tenant, parent) REFERENCES evaluation_run (tenant, id)
);

CREATE TABLE evaluation_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE evaluation_start (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "run" TEXT NOT NULL,
  "started_at" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, run) REFERENCES evaluation_run (tenant, id)
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "predecessor" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, predecessor) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evidence_item (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "source_record" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "revision" TEXT,
  "digest" TEXT,
  "provenance" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES evidence_source (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id)
);

CREATE TABLE evidence_member (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "item" TEXT NOT NULL,
  "next" TEXT,
  "depth" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, item) REFERENCES evidence_item (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_seal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "head" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, head) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_source (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment_set" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "executor" TEXT NOT NULL,
  "requested_at" TEXT NOT NULL,
  "evidence" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment_set) REFERENCES fulfillment_set (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, executor) REFERENCES fulfillment_executor (tenant, id),
  FOREIGN KEY (tenant, evidence) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE fulfillment_end (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "start" TEXT,
  "outcome" TEXT NOT NULL,
  "coverage" TEXT NOT NULL,
  "ended_at" TEXT NOT NULL,
  "evidence" TEXT,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id),
  FOREIGN KEY (tenant, start) REFERENCES fulfillment_start (tenant, id),
  FOREIGN KEY (tenant, evidence) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE fulfillment_executor (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment_replacement (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "prior" TEXT NOT NULL,
  "prior_end" TEXT NOT NULL,
  "replacement" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, prior) REFERENCES fulfillment (tenant, id),
  FOREIGN KEY (tenant, prior_end) REFERENCES fulfillment_end (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE fulfillment_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment_start (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "began_at" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE fulfillment_task_link (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "queue" TEXT NOT NULL,
  "task" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE metric_breach_effect (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "breach" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, breach) REFERENCES metric_breach_event (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE metric_breach_event (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "assessment" TEXT NOT NULL,
  "occurred_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, assessment) REFERENCES performance_assessment (tenant, id)
);

CREATE TABLE metric_definition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "dimension" TEXT NOT NULL,
  "unit" TEXT NOT NULL,
  "semantics" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, semantics) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE metric_objective (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "metric" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "policy" TEXT NOT NULL,
  "target" INTEGER NOT NULL,
  "minimum" INTEGER,
  "maximum" INTEGER,
  "from_" TEXT NOT NULL,
  "until" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, metric) REFERENCES metric_definition (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES metric_subject (tenant, id),
  FOREIGN KEY (tenant, policy) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE metric_observation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "metric" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "unit" TEXT NOT NULL,
  "value_" INTEGER NOT NULL,
  "observed_at" TEXT,
  "from_" TEXT,
  "until" TEXT,
  "source" TEXT NOT NULL,
  "source_record" TEXT NOT NULL,
  "support" TEXT,
  "operation" TEXT NOT NULL,
  "left_" TEXT,
  "right_" TEXT,
  "depth" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, metric) REFERENCES metric_definition (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES metric_subject (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES evidence_source (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id),
  FOREIGN KEY (tenant, left_) REFERENCES metric_observation (tenant, id),
  FOREIGN KEY (tenant, right_) REFERENCES metric_observation (tenant, id)
);

CREATE TABLE metric_subject (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE performance_assessment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "objective" TEXT NOT NULL,
  "observation" TEXT NOT NULL,
  "evaluation" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, objective) REFERENCES metric_objective (tenant, id),
  FOREIGN KEY (tenant, observation) REFERENCES metric_observation (tenant, id),
  FOREIGN KEY (tenant, evaluation) REFERENCES evaluation_finish (tenant, id)
);

CREATE TABLE realization (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "build_hash" TEXT NOT NULL,
  "manifest_digest" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE repository (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "locator" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE specification_pin (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "anchor" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, repository) REFERENCES repository (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX artifact_uq_key ON artifact (tenant, key_);
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision (tenant, content);
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision (tenant, artifact, id);
CREATE UNIQUE INDEX evaluation_executor_uq_key ON evaluation_executor (tenant, key_);
CREATE UNIQUE INDEX evaluation_finish_uq_run ON evaluation_finish (tenant, run);
CREATE UNIQUE INDEX evaluation_quarantine_uq_run ON evaluation_quarantine (tenant, run);
CREATE INDEX evaluation_run_ix_by_definition ON evaluation_run (tenant, definition, id);
CREATE INDEX evaluation_run_ix_by_evaluation_set ON evaluation_run (tenant, evaluation_set, id);
CREATE UNIQUE INDEX evaluation_start_uq_run ON evaluation_start (tenant, run);
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle (tenant, key_);
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item (tenant, bundle, source, source_record);
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item (tenant, bundle, id);
CREATE INDEX evidence_item_ix_by_source ON evidence_item (tenant, source, id);
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal (tenant, bundle);
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source (tenant, key_);
CREATE UNIQUE INDEX fulfillment_uq_fulfillmentSet_ordinal ON fulfillment (tenant, fulfillment_set, ordinal);
CREATE INDEX fulfillment_ix_by_fulfillment_set ON fulfillment (tenant, fulfillment_set, ordinal, id);
CREATE UNIQUE INDEX fulfillment_end_uq_fulfillment ON fulfillment_end (tenant, fulfillment);
CREATE UNIQUE INDEX fulfillment_executor_uq_key ON fulfillment_executor (tenant, key_);
CREATE UNIQUE INDEX fulfillment_replacement_uq_prior ON fulfillment_replacement (tenant, prior);
CREATE UNIQUE INDEX fulfillment_replacement_uq_replacement ON fulfillment_replacement (tenant, replacement);
CREATE UNIQUE INDEX fulfillment_start_uq_fulfillment ON fulfillment_start (tenant, fulfillment);
CREATE UNIQUE INDEX fulfillment_task_link_uq_queue_task ON fulfillment_task_link (tenant, queue, task);
CREATE INDEX fulfillment_task_link_ix_by_fulfillment ON fulfillment_task_link (tenant, fulfillment, id);
CREATE UNIQUE INDEX metric_breach_effect_uq_breach_fulfillment ON metric_breach_effect (tenant, breach, fulfillment);
CREATE UNIQUE INDEX metric_breach_event_uq_assessment ON metric_breach_event (tenant, assessment);
CREATE UNIQUE INDEX metric_definition_uq_key_definition ON metric_definition (tenant, key_, definition);
CREATE UNIQUE INDEX metric_objective_uq_key ON metric_objective (tenant, key_);
CREATE UNIQUE INDEX metric_observation_uq_key ON metric_observation (tenant, key_);
CREATE UNIQUE INDEX metric_observation_uq_source_sourceRecord ON metric_observation (tenant, source, source_record);
CREATE UNIQUE INDEX metric_subject_uq_key ON metric_subject (tenant, key_);
CREATE UNIQUE INDEX performance_assessment_uq_objective_observation ON performance_assessment (tenant, objective, observation);
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization (tenant, pin, build_hash, manifest_digest);
CREATE INDEX realization_ix_by_pin ON realization (tenant, pin, id);
CREATE UNIQUE INDEX repository_uq_key ON repository (tenant, key_);
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin (tenant, repository, anchor, revision);
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin (tenant, repository, anchor, id);
