//! TypeScript client generated from the target-independent contracts. One
//! client is used against either deployment; only `baseUrl` changes.

use forge_planner::contracts::{Contracts, JsonSchema};
use serde_json::Value;
use std::fmt::Write;

fn ts_type(schema: &Value, optional_null: bool) -> String {
    let base = if let Some(e) = schema.get("enum").and_then(|e| e.as_array()) {
        e.iter().filter_map(|v| v.as_str()).map(|s| format!("{s:?}")).collect::<Vec<_>>().join(" | ")
    } else if schema.get("$ref").is_some() {
        "unknown".into()
    } else {
        match schema.get("type") {
            Some(Value::String(t)) => match t.as_str() {
                "string" => "string".into(),
                "integer" | "number" => "number".into(),
                "boolean" => "boolean".into(),
                _ => "unknown".into(),
            },
            Some(Value::Array(ts)) => ts.iter().filter_map(|t| t.as_str()).map(|t| match t { "string" => "string", "integer" | "number" => "number", "boolean" => "boolean", "null" => "null", _ => "unknown" }.to_string()).collect::<Vec<_>>().join(" | "),
            _ => "unknown".into(),
        }
    };
    if optional_null && !base.contains("null") { format!("{base} | null") } else { base }
}

fn interface(out: &mut String, name: &str, schema: &JsonSchema) {
    let _ = writeln!(out, "export interface {name} {{");
    for (field, s) in &schema.properties {
        let required = schema.required.contains(field);
        let _ = writeln!(out, "  {field}{}: {};", if required { "" } else { "?" }, ts_type(s, false));
    }
    let _ = writeln!(out, "}}\n");
}

fn plural(wire: &str) -> String {
    if wire.ends_with('s') { format!("{wire}es") } else { format!("{wire}s") }
}
fn lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}
fn upper_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}
fn camel_from_wire(wire: &str) -> String {
    let mut out = String::new();
    let mut up = false;
    for ch in wire.chars() {
        if ch == '_' { up = true; } else if up { out.push(ch.to_ascii_uppercase()); up = false; } else { out.push(ch); }
    }
    out
}

pub fn client_ts(c: &Contracts) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by forge build from {} ({}). Do not edit.\n", c.package, c.version);
    out.push_str(RUNTIME_PRELUDE);

    // operations table
    let _ = writeln!(out, "export const operations: Record<string, OperationSpec> = {{");
    for r in &c.resources {
        for op in &r.operations {
            let Some(h) = &op.http else { continue };
            let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: {:?}, resource: {:?} }},", op.id, h.method, h.path, op.kind, r.name);
        }
    }
    for f in &c.functions {
        if let Some(h) = &f.http {
            let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: \"function\", resource: {:?} }},", f.id, h.method, h.path, f.name);
        }
    }
    let pkg = &c.package;
    for (action, method, path) in [("propose", "POST", "/v1/changesets"), ("get", "GET", "/v1/changesets/{id}"), ("preview", "GET", "/v1/changesets/{id}/preview"), ("approve", "POST", "/v1/changesets/{id}/approve"), ("commit", "POST", "/v1/changesets/{id}/commit")] {
        let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: {:?}, resource: \"changesets\" }},", format!("{pkg}/_/changesets.{action}"), method, path, format!("changeset.{action}"));
    }
    for action in ["export", "import", "verify", "fence", "inspect"] {
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: {:?}, resource: \"admin\" }},", format!("{pkg}/_/admin.{action}"), format!("/v1/admin/{action}"), format!("admin.{action}"));
    }
    let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: \"/v1/admin/subjects/locate\", kind: \"admin.subjects.locate\", resource: \"admin\" }},", format!("{pkg}/_/admin.subjects.locate"));
    for (action, path) in [("inspect", "/v1/imports/inspect"), ("stage", "/v1/imports/stage")] {
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: {:?}, resource: \"imports\" }},", format!("{pkg}/_/imports.{action}"), path, format!("import.{action}"));
    }
    for v in &c.views {
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"view.query\", resource: {:?} }},", format!("{}.query", v.id), v.http.path, v.name);
    }
    for p in &c.projections {
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"projection.get\", resource: {:?} }},", format!("{}.get", p.id), format!("{}/{{id}}", p.path), p.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"projection.status\", resource: {:?} }},", format!("{}.status", p.id), format!("{}/status", p.path), p.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: \"projection.rebuild\", resource: {:?} }},", format!("{}.rebuild", p.id), format!("{}/rebuild", p.path), p.name);
    }
    for k in &c.caches {
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"cache.read\", resource: {:?} }},", format!("{}.read", k.id), k.http.path, k.name);
    }
    for s in &c.schedules {
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"schedule.status\", resource: {:?} }},", format!("{}.status", s.id), s.path, s.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: \"schedule.tick\", resource: {:?} }},", format!("{}.tick", s.id), format!("{}/tick", s.path), s.name);
    }
    for w in &c.workflows {
        let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: \"workflow.start\", resource: {:?} }},", format!("{}.start", w.id), w.start.method, w.start.path, w.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"GET\", path: {:?}, kind: \"workflow.get\", resource: {:?} }},", format!("{}.get", w.id), format!("{}/{{id}}", w.path), w.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: \"workflow.cancel\", resource: {:?} }},", format!("{}.cancel", w.id), format!("{}/{{id}}/cancel", w.path), w.name);
        let _ = writeln!(out, "  {:?}: {{ method: \"POST\", path: {:?}, kind: \"workflow.signal\", resource: {:?} }},", format!("{}.signal", w.id), format!("{}/signals/{{message}}", w.path), w.name);
    }
    let _ = writeln!(out, "}};\n");

    for v in &c.views {
        interface(&mut out, &format!("{}Row", v.name), &v.record);
    }
    // Edition 2027: `Resource.Record<Purpose>` as a concrete nominal type; the runtime emits exactly these keys.
    for s in &c.surfaces {
        let _ = writeln!(out, "/** {}.Record<{}> — surface digest {} */", s.resource_name, s.purpose_name, &s.digest[..12]);
        interface(&mut out, &format!("{}{}Record", s.resource_name, s.purpose_name), &s.record);
    }
    for p in &c.projections {
        interface(&mut out, &format!("{}Record", p.name), &p.record);
    }
    for r in &c.resources {
        interface(&mut out, &format!("{}Record", r.name), &r.record);
        interface(&mut out, &format!("{}Create", r.name), &r.create);
        interface(&mut out, &format!("{}Patch", r.name), &r.patch);
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                interface(&mut out, &format!("{}{}Input", r.name, upper_first(&a.name)), &a.input);
            }
        }
    }

    // typed facade per resource
    for r in &c.resources {
        let _ = writeln!(out, "export interface {}Api {{", r.name);
        for op in &r.operations {
            if op.http.is_none() {
                continue;
            }
            let rec = format!("{}Record", r.name);
            match op.kind.as_str() {
                "create" => { let _ = writeln!(out, "  create(input: {}Create, opts?: CallOptions): Promise<{rec}>;", r.name); }
                "get" => { let _ = writeln!(out, "  get(id: string): Promise<{rec}>;"); }
                "update" => { let _ = writeln!(out, "  update(id: string, expectedVersion: number, patch: {}Patch, opts?: CallOptions): Promise<{rec}>;", r.name); }
                "delete" => { let _ = writeln!(out, "  delete(id: string, expectedVersion: number, opts?: CallOptions): Promise<{rec}>;"); }
                "restore" => { let _ = writeln!(out, "  restore(id: string, expectedVersion: number, opts?: CallOptions): Promise<{rec}>;"); }
                "beginUpload" => { let _ = writeln!(out, "  beginUpload(id: string, expectedVersion: number, input: {{ mediaType: string; byteCount: number }}): Promise<{{ record: {rec}; upload: SignedUrl }}>;"); }
                "finalizeUpload" => { let _ = writeln!(out, "  finalizeUpload(id: string, expectedVersion: number): Promise<{rec}>;"); }
                "download" => { let _ = writeln!(out, "  download(id: string): Promise<SignedUrl & {{ mediaType: string; byteCount: number; digest: string }}>;"); }
                "effective" => { let _ = writeln!(out, "  effective(params: Record<string, string> & {{ at: string }}): Promise<{rec} | null>;"); }
                "move" => { let _ = writeln!(out, "  move(id: string, expectedVersion: number, parent: string | null): Promise<{rec}>;"); }
                "children" => { let _ = writeln!(out, "  children(id: string): Promise<Page<{rec}>>;"); }
                "ancestors" => { let _ = writeln!(out, "  ancestors(id: string): Promise<Page<{rec}>>;"); }
                "find" | "list" => {
                    let q = r.queries.iter().find(|q| Some(&q.name) == op.query.as_ref()).unwrap();
                    let params: Vec<String> = q.params.iter().map(|p| format!("{p}: {}", ts_type(r.record.properties.get(p).unwrap_or(&Value::Null), false))).collect();
                    let method = format!("{}{}", op.kind, upper_first(&q.name));
                    if op.kind == "find" {
                        let _ = writeln!(out, "  {method}(params: {{ {} }}): Promise<{rec} | null>;", params.join("; "));
                    } else {
                        let _ = writeln!(out, "  {method}(params: {{ {} }}, page?: PageOptions): Promise<Page<{rec}>>;", params.join("; "));
                    }
                }
                _ => {}
            }
        }
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                let exposed = r.operations.iter().any(|o| o.action.as_ref() == Some(&a.name) && o.http.is_some());
                if exposed {
                    let _ = writeln!(out, "  {}(id: string, expectedVersion: number, input: {}{}Input, opts?: CallOptions): Promise<{}Record>;", a.name, r.name, upper_first(&a.name), r.name);
                }
            }
        }
        let _ = writeln!(out, "}}\n");
    }

    let _ = writeln!(out, "export interface FunctionsApi {{");
    for f in c.functions.iter().filter(|f| f.http.is_some()) {
        let _ = writeln!(out, "  {}(input: Record<string, unknown>, opts?: CallOptions): Promise<unknown>;", lower_first(&f.name));
    }
    let _ = writeln!(out, "}}\n");
    let _ = writeln!(out, "export interface ForgeClient {{");
    let _ = writeln!(out, "  functions: FunctionsApi;");
    let _ = writeln!(out, "  call(op: string, input: unknown, opts?: CallOptions): Promise<CallResult>;");
    let _ = writeln!(out, "  changesets: ChangesetsApi;");
    let _ = writeln!(out, "  imports: ImportsApi;");
    let _ = writeln!(out, "  admin: AdminApi;");
    for r in &c.resources {
        let _ = writeln!(out, "  {}: {}Api;", camel_from_wire(&plural(&r.wire_name)), r.name);
    }
    let _ = writeln!(out, "  views: {{");
    for v in &c.views {
        let params: Vec<String> = v.params.iter().map(|p| format!("{p}: string")).collect();
        let _ = writeln!(out, "    {}: {{ query(params: {{ {} }}, page?: PageOptions): Promise<Page<{}Row>> }};", lower_first(&v.name), params.join("; "), v.name);
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  projections: {{");
    for p in &c.projections {
        let _ = writeln!(out, "    {}: {{ get(id: string): Promise<{}Record>; status(): Promise<ProjectionStatus>; rebuild(): Promise<ProjectionStatus> }};", lower_first(&p.name), p.name);
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  caches: {{");
    for k in &c.caches {
        let keys: Vec<String> = k.keys.iter().map(|p| format!("{p}: string")).collect();
        let value = k.value_resource.as_ref().map(|r| format!("{r}Record | null")).unwrap_or_else(|| "unknown".into());
        let _ = writeln!(out, "    {}: {{ read(key: {{ {} }}): Promise<CacheRead<{}>> }};", lower_first(&k.name), keys.join("; "), value);
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  schedules: {{");
    for s in &c.schedules {
        let _ = writeln!(out, "    {}: {{ status(): Promise<ScheduleStatus>; tick(now?: string): Promise<{{ results: ScheduleTick[] }}> }};", lower_first(&s.name));
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "  workflows: {{");
    for w in &c.workflows {
        let msgs: Vec<String> = w.signals.iter().map(|(_, m)| format!("{m:?}")).collect();
        let _ = writeln!(out, "    {}: {{ start(input: Record<string, unknown>, opts?: CallOptions): Promise<WorkflowInstance>; get(id: string): Promise<WorkflowInstance>; cancel(id: string): Promise<WorkflowInstance>; signal(message: {}, payload: Record<string, unknown>, messageId?: string): Promise<{{ delivered: number; held: number }}> }};", lower_first(&w.name), if msgs.is_empty() { "never".to_string() } else { msgs.join(" | ") });
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "export function createClient(options: ClientOptions): ForgeClient {{");
    let _ = writeln!(out, "  const t = createTransport(options, operations);");
    let _ = writeln!(out, "  return {{");
    let _ = writeln!(out, "    call: t.call,");
    let _ = writeln!(out, "    changesets: {{");
    let _ = writeln!(out, "      propose: (input, opts) => t.unwrap(t.call({:?}, input, opts)),", format!("{pkg}/_/changesets.propose"));
    let _ = writeln!(out, "      get: (id) => t.unwrap(t.call({:?}, {{ id }})),", format!("{pkg}/_/changesets.get"));
    let _ = writeln!(out, "      preview: (id) => t.unwrap(t.call({:?}, {{ id }})),", format!("{pkg}/_/changesets.preview"));
    let _ = writeln!(out, "      approve: (id, contentHash) => t.unwrap(t.call({:?}, {{ id, contentHash }})),", format!("{pkg}/_/changesets.approve"));
    let _ = writeln!(out, "      commit: (id, opts) => t.unwrap(t.call({:?}, {{ id }}, opts)),", format!("{pkg}/_/changesets.commit"));
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    functions: {{");
    for f in c.functions.iter().filter(|f| f.http.is_some()) {
        let _ = writeln!(out, "      {}: (input, opts) => t.unwrap(t.call({:?}, input, opts)),", lower_first(&f.name), f.id);
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    imports: {{");
    let _ = writeln!(out, "      inspect: (input) => t.unwrap(t.call({:?}, input)),", format!("{pkg}/_/imports.inspect"));
    let _ = writeln!(out, "      stage: (input) => t.unwrap(t.call({:?}, input)),", format!("{pkg}/_/imports.stage"));
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    admin: {{");
    let _ = writeln!(out, "      export: () => t.unwrap(t.call({:?}, {{}})),", format!("{pkg}/_/admin.export"));
    let _ = writeln!(out, "      import: (snapshot) => t.unwrap(t.call({:?}, {{ snapshot }})),", format!("{pkg}/_/admin.import"));
    let _ = writeln!(out, "      verify: (snapshot) => t.unwrap(t.call({:?}, {{ snapshot }})),", format!("{pkg}/_/admin.verify"));
    let _ = writeln!(out, "      fence: (on) => t.unwrap(t.call({:?}, {{ on }})),", format!("{pkg}/_/admin.fence"));
    let _ = writeln!(out, "      locateSubject: (input) => t.unwrap(t.call({:?}, input)),", format!("{pkg}/_/admin.subjects.locate"));
    let _ = writeln!(out, "      inspect: (input) => t.unwrap(t.call({:?}, input)),", format!("{pkg}/_/admin.inspect"));
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    views: {{");
    for v in &c.views {
        let _ = writeln!(out, "      {}: {{ query: (params, page) => t.unwrap(t.call({:?}, {{ params, ...(page ?? {{}}) }})) }},", lower_first(&v.name), format!("{}.query", v.id));
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    projections: {{");
    for p in &c.projections {
        let _ = writeln!(out, "      {}: {{ get: (id) => t.unwrap(t.call({:?}, {{ id }})), status: () => t.unwrap(t.call({:?}, {{}})), rebuild: () => t.unwrap(t.call({:?}, {{}})) }},", lower_first(&p.name), format!("{}.get", p.id), format!("{}.status", p.id), format!("{}.rebuild", p.id));
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    caches: {{");
    for k in &c.caches {
        let _ = writeln!(out, "      {}: {{ read: (key) => t.unwrap(t.call({:?}, {{ key }})) }},", lower_first(&k.name), format!("{}.read", k.id));
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    schedules: {{");
    for s in &c.schedules {
        let _ = writeln!(out, "      {}: {{ status: () => t.unwrap(t.call({:?}, {{}})), tick: (now) => t.unwrap(t.call({:?}, now ? {{ now }} : {{}})) }},", lower_first(&s.name), format!("{}.status", s.id), format!("{}.tick", s.id));
    }
    let _ = writeln!(out, "    }},");
    let _ = writeln!(out, "    workflows: {{");
    for w in &c.workflows {
        let _ = writeln!(out, "      {}: {{ start: (input, opts) => t.unwrap(t.call({:?}, input, opts)), get: (id) => t.unwrap(t.call({:?}, {{ id }})), cancel: (id) => t.unwrap(t.call({:?}, {{ id }})), signal: (message, payload, messageId) => t.unwrap(t.call({:?}, {{ message, payload, ...(messageId ? {{ messageId }} : {{}}) }})) }},", lower_first(&w.name), format!("{}.start", w.id), format!("{}.get", w.id), format!("{}.cancel", w.id), format!("{}.signal", w.id));
    }
    let _ = writeln!(out, "    }},");
    for r in &c.resources {
        let _ = writeln!(out, "    {}: {{", camel_from_wire(&plural(&r.wire_name)));
        for op in &r.operations {
            if op.http.is_none() {
                continue;
            }
            let id = &op.id;
            match op.kind.as_str() {
                "create" => { let _ = writeln!(out, "      create: (input, opts) => t.unwrap(t.call({id:?}, input, opts)),"); }
                "get" => { let _ = writeln!(out, "      get: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "update" => { let _ = writeln!(out, "      update: (id, expectedVersion, patch, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion, patch }}, opts)),"); }
                "delete" => { let _ = writeln!(out, "      delete: (id, expectedVersion, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }}, opts)),"); }
                "restore" => { let _ = writeln!(out, "      restore: (id, expectedVersion, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }}, opts)),"); }
                "beginUpload" => { let _ = writeln!(out, "      beginUpload: (id, expectedVersion, input) => t.unwrap(t.call({id:?}, {{ id, expectedVersion, ...input }})),"); }
                "finalizeUpload" => { let _ = writeln!(out, "      finalizeUpload: (id, expectedVersion) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }})),"); }
                "download" => { let _ = writeln!(out, "      download: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "effective" => { let _ = writeln!(out, "      effective: (params) => t.unwrapNullable(t.call({id:?}, {{ params }})),"); }
                "move" => { let _ = writeln!(out, "      move: (id, expectedVersion, parent) => t.unwrap(t.call({id:?}, {{ id, expectedVersion, parent }})),"); }
                "children" => { let _ = writeln!(out, "      children: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "ancestors" => { let _ = writeln!(out, "      ancestors: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "find" => { let _ = writeln!(out, "      find{}: (params) => t.unwrapNullable(t.call({id:?}, {{ params }})),", upper_first(op.query.as_ref().unwrap())); }
                "list" => { let _ = writeln!(out, "      list{}: (params, page) => t.unwrap(t.call({id:?}, {{ params, ...page }})),", upper_first(op.query.as_ref().unwrap())); }
                _ => {}
            }
        }
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                let opid = format!("{}.status.{}", r.id, a.name);
                if r.operations.iter().any(|o| o.id == opid && o.http.is_some()) {
                    let _ = writeln!(out, "      {}: (id, expectedVersion, input, opts) => t.unwrap(t.call({opid:?}, {{ id, expectedVersion, input }}, opts)),", a.name);
                }
            }
        }
        let _ = writeln!(out, "    }},");
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "}}");
    out
}

const RUNTIME_PRELUDE: &str = r#"export interface OperationSpec { method: string; path: string; kind: string; resource: string }
export interface ChangesetOperation { op: string; input: unknown }
export interface ChangesetItem { index: number; op: string; status: "ok" | "error" | "committed" | "skipped"; diff?: { path: string; before: unknown; after: unknown }[]; result?: unknown; error?: Problem }
export interface ChangesetBudget { mode: string; logicalOperations: number; logicalLimit: number; physicalActions: number; physicalLimit: number; atomicAllowed: boolean }
export interface Changeset { id: string; status: string; mode: "atomic" | "resumable"; operations: number; contentHash?: string; items?: ChangesetItem[]; budget?: ChangesetBudget; results?: ChangesetItem[] }
export interface ImportInspection { header: string[]; rows: number; sample: string[][]; suggestedMapping: Record<string, string>; errors: { line: number; code: string; message: string }[] }
export interface ImportStaged { changeset: string; rows: number; staged: number; rowErrors: { line: number; code: string; path?: string; message: string }[] }
export interface ImportsApi {
  inspect(input: { resource: string; csv: string }): Promise<ImportInspection>;
  stage(input: { resource: string; csv: string; mapping: Record<string, string>; upsertBy?: string; mode?: "atomic" | "resumable" }): Promise<ImportStaged>;
}
export interface ChangesetsApi {
  propose(input: { mode?: "atomic" | "resumable"; operations: ChangesetOperation[] }, opts?: CallOptions): Promise<Changeset>;
  get(id: string): Promise<Changeset>;
  preview(id: string): Promise<Changeset & { contentHash: string }>;
  approve(id: string, contentHash: string): Promise<Changeset>;
  commit(id: string, opts?: CallOptions): Promise<Changeset>;
}
export interface Page<T> { items: T[]; next: string | null; limit: number }
export interface ProjectionStatus { generation: number; status: string; lastProcessed: unknown }
export interface CacheRead<T> { value: T; source: "cache" | "loader"; freshUntil: string }
export interface Snapshot { version: "export/1"; package: string; tenant: string; exportedAt: string; manifest: { contractsVersion: string; buildHash: string; resources: string[] }; resources: Record<string, { count: number; hash: string; records: Record<string, unknown>[] }> }
export interface VerifyReport { ok: boolean; verifiedAt: string; resources: Record<string, { expectedCount: number; actualCount: number; hashMatch: boolean; revisionMismatches: { id: string; expected: unknown; actual: unknown }[]; references: { checked: number; missing: number } }> }
/** Provider switching (plan §22): operator-only. */
export interface AdminApi {
  export(): Promise<Snapshot>;
  import(snapshot: Snapshot): Promise<{ imported: Record<string, number>; skipped: Record<string, number>; importedAt: string }>;
  verify(snapshot: Snapshot): Promise<VerifyReport>;
  fence(on: boolean): Promise<{ fenced: boolean }>;
  /** Records of one subject through declared bindings; linked subjects reported, never cascaded (plan §7.2). */
  locateSubject(input: { kind: string; resource: string; id: string }): Promise<{ subject: { kind: string; resource: string; id: string }; records: { resource: string; count: number; via?: string }[]; linked: { resource: string; id: string; via: string; kind: string; sharedWith: number | null }[]; cascade: never[] }>;
  /** Content inspection verdict bound to the sealed digest (plan §7.3). */
  inspect(input: { resource: string; id: string; digest: string; verdict: "allowed" | "quarantined" | "failed" | "review"; detector: string; detail?: string }): Promise<{ id: string; generation: number; inspection: { state: string; generation: number } }>;
}
export interface ScheduleStatus { source: string; lastOccurrence: string | null; next: string | null; skipped: string[] }
export interface ScheduleTick { source: string; occurrence: string; outcome: "ran" | "duplicate" | "skipped-overlap" | "failed"; error?: string }
export interface WorkflowInstance { id: string; workflow: string; version: number; status: "running" | "waiting" | "sleeping" | "completed" | "failed" | "cancelled"; input: Record<string, unknown>; bindings: Record<string, unknown>; history: { step: string; kind: string; at: string }[]; waiting?: { step: string; message: string; correlationKey: string; dueAt?: string }; sleeping?: { step: string; dueAt: string }; output?: unknown; error?: { code: string; detail?: string } }
export interface PageOptions { cursor?: string | null; limit?: number }
export interface CallOptions { idempotencyKey?: string; /** Edition 2027: the purpose surface to run under (one; never a union). */ purpose?: string }
export interface SignedUrl { url: string; method: "PUT" | "GET"; headers?: Record<string, string>; expiresAt: string }
export interface ProblemField { path: string; code: string; message: string }
export interface Problem {
  type: string; title: string; status: number; code: string; detail?: string;
  requestId?: string; retryable: boolean; fields?: ProblemField[]; constraint?: string;
}
export type CallResult = { ok: true; value: unknown; version?: number } | { ok: false; code: string; status: number; problem: Problem };
export class ForgeError extends Error {
  readonly problem: Problem;
  constructor(problem: Problem) {
    super(`${problem.code}: ${problem.detail ?? problem.title}`);
    this.problem = problem;
  }
  get code() { return this.problem.code; }
  get status() { return this.problem.status; }
}
export interface ClientOptions {
  baseUrl: string;
  tenant?: string;
  actor?: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

function fillPath(path: string, input: Record<string, unknown>): string {
  return path.replace(/\{(\w+)\}/g, (_, k) => encodeURIComponent(String(input[k])));
}

export function createTransport(options: ClientOptions, ops: Record<string, OperationSpec>) {
  const f = options.fetch ?? fetch;
  const base = options.baseUrl.replace(/\/$/, "");
  async function call(op: string, rawInput: unknown, opts?: CallOptions): Promise<CallResult> {
    const spec = ops[op];
    if (!spec) throw new Error(`unknown operation ${op}`);
    const input = (rawInput ?? {}) as Record<string, unknown>;
    const headers: Record<string, string> = { accept: "application/json", ...(options.headers ?? {}) };
    if (options.tenant) headers["x-forge-tenant"] = options.tenant;
    if (options.actor) headers["x-forge-actor"] = options.actor;
    if (opts?.idempotencyKey) headers["idempotency-key"] = opts.idempotencyKey;
    if (opts?.purpose) headers["x-forge-purpose"] = opts.purpose;
    if (typeof input["expectedVersion"] === "number") headers["if-match"] = `"${input["expectedVersion"]}"`;
    let url = base + fillPath(spec.path, input);
    let body: string | null = null;
    if (spec.kind === "find" || spec.kind === "list" || spec.kind === "effective" || spec.kind === "view.query" || spec.kind === "cache.read") {
      const q = new URLSearchParams();
      for (const [k, v] of Object.entries((input[spec.kind === "cache.read" ? "key" : "params"] ?? {}) as Record<string, unknown>)) q.set(k, String(v));
      if (input["cursor"]) q.set("cursor", String(input["cursor"]));
      if (input["limit"]) q.set("limit", String(input["limit"]));
      const qs = q.toString();
      if (qs) url += "?" + qs;
    } else if (spec.kind === "create" || spec.kind === "function" || spec.kind === "workflow.start" || spec.kind.startsWith("admin.") || spec.kind === "changeset.propose" || spec.kind === "changeset.approve" || spec.kind === "import.inspect" || spec.kind === "import.stage") {
      const { id: _id, ...rest } = input;
      void _id;
      body = JSON.stringify(spec.kind === "changeset.approve" ? rest : input);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "workflow.signal") {
      const { message: _m, ...rest } = input;
      void _m;
      body = JSON.stringify(rest);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "workflow.cancel" || spec.kind === "schedule.tick" || spec.kind === "projection.rebuild") {
      body = JSON.stringify(input);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "update") {
      body = JSON.stringify(input["patch"] ?? {});
      headers["content-type"] = "application/json";
    } else if (spec.kind === "beginUpload" || spec.kind === "move") {
      const { id: _id, expectedVersion: _v, ...rest } = input;
      void _id;
      void _v;
      body = JSON.stringify(rest);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "transition") {
      body = JSON.stringify(input["input"] ?? {});
      headers["content-type"] = "application/json";
    }
    const res = await f(url, { method: spec.method, headers, body });
    const text = await res.text();
    const json = text ? JSON.parse(text) : null;
    if (res.ok) {
      const etag = res.headers.get("etag");
      return { ok: true, value: json, ...(etag ? { version: Number(etag.replace(/"/g, "")) } : {}) };
    }
    const problem: Problem = json && json.code ? json : { type: "about:blank", title: res.statusText, status: res.status, code: "Internal", retryable: res.status >= 500 };
    return { ok: false, code: problem.code, status: res.status, problem };
  }
  async function unwrap<T>(p: Promise<CallResult>): Promise<T> {
    const r = await p;
    if (r.ok) return r.value as T;
    throw new ForgeError(r.problem);
  }
  async function unwrapNullable<T>(p: Promise<CallResult>): Promise<T | null> {
    const r = await p;
    if (r.ok) return r.value as T;
    if (r.code === "NotFound") return null;
    throw new ForgeError(r.problem);
  }
  return { call, unwrap, unwrapNullable };
}

"#;
