//! TypeScript client generated from the target-independent contracts. One
//! client is used against either deployment; only `baseUrl` changes.

use forge_planner::contracts::{Contracts, JsonSchema};
use serde_json::Value;
use std::fmt::Write;

fn ts_type(schema: &Value, optional_null: bool) -> String {
    let base = if let Some(e) = schema.get("enum").and_then(|e| e.as_array()) {
        e.iter().filter_map(|v| v.as_str()).map(|s| format!("{s:?}")).collect::<Vec<_>>().join(" | ")
    } else if schema.get("$ref").is_some() {
        "unknown".into()
    } else {
        match schema.get("type") {
            Some(Value::String(t)) => match t.as_str() {
                "string" => "string".into(),
                "integer" | "number" => "number".into(),
                "boolean" => "boolean".into(),
                _ => "unknown".into(),
            },
            Some(Value::Array(ts)) => ts.iter().filter_map(|t| t.as_str()).map(|t| match t { "string" => "string", "integer" | "number" => "number", "boolean" => "boolean", "null" => "null", _ => "unknown" }.to_string()).collect::<Vec<_>>().join(" | "),
            _ => "unknown".into(),
        }
    };
    if optional_null && !base.contains("null") { format!("{base} | null") } else { base }
}

fn interface(out: &mut String, name: &str, schema: &JsonSchema) {
    let _ = writeln!(out, "export interface {name} {{");
    for (field, s) in &schema.properties {
        let required = schema.required.contains(field);
        let _ = writeln!(out, "  {field}{}: {};", if required { "" } else { "?" }, ts_type(s, false));
    }
    let _ = writeln!(out, "}}\n");
}

fn plural(wire: &str) -> String {
    if wire.ends_with('s') { format!("{wire}es") } else { format!("{wire}s") }
}
fn upper_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}
fn camel_from_wire(wire: &str) -> String {
    let mut out = String::new();
    let mut up = false;
    for ch in wire.chars() {
        if ch == '_' { up = true; } else if up { out.push(ch.to_ascii_uppercase()); up = false; } else { out.push(ch); }
    }
    out
}

pub fn client_ts(c: &Contracts) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by forge build from {} ({}). Do not edit.\n", c.package, c.version);
    out.push_str(RUNTIME_PRELUDE);

    // operations table
    let _ = writeln!(out, "export const operations: Record<string, OperationSpec> = {{");
    for r in &c.resources {
        for op in &r.operations {
            let Some(h) = &op.http else { continue };
            let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: {:?}, resource: {:?} }},", op.id, h.method, h.path, op.kind, r.name);
        }
    }
    for f in &c.functions {
        if let Some(h) = &f.http {
            let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: \"function\", resource: {:?} }},", f.id, h.method, h.path, f.name);
        }
    }
    let pkg = &c.package;
    for (action, method, path) in [("propose", "POST", "/v1/changesets"), ("get", "GET", "/v1/changesets/{id}"), ("preview", "GET", "/v1/changesets/{id}/preview"), ("approve", "POST", "/v1/changesets/{id}/approve"), ("commit", "POST", "/v1/changesets/{id}/commit")] {
        let _ = writeln!(out, "  {:?}: {{ method: {:?}, path: {:?}, kind: {:?}, resource: \"changesets\" }},", format!("{pkg}/_/changesets.{action}"), method, path, format!("changeset.{action}"));
    }
    let _ = writeln!(out, "}};\n");

    for r in &c.resources {
        interface(&mut out, &format!("{}Record", r.name), &r.record);
        interface(&mut out, &format!("{}Create", r.name), &r.create);
        interface(&mut out, &format!("{}Patch", r.name), &r.patch);
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                interface(&mut out, &format!("{}{}Input", r.name, upper_first(&a.name)), &a.input);
            }
        }
    }

    // typed facade per resource
    for r in &c.resources {
        let _ = writeln!(out, "export interface {}Api {{", r.name);
        for op in &r.operations {
            if op.http.is_none() {
                continue;
            }
            let rec = format!("{}Record", r.name);
            match op.kind.as_str() {
                "create" => { let _ = writeln!(out, "  create(input: {}Create, opts?: CallOptions): Promise<{rec}>;", r.name); }
                "get" => { let _ = writeln!(out, "  get(id: string): Promise<{rec}>;"); }
                "update" => { let _ = writeln!(out, "  update(id: string, expectedVersion: number, patch: {}Patch, opts?: CallOptions): Promise<{rec}>;", r.name); }
                "delete" => { let _ = writeln!(out, "  delete(id: string, expectedVersion: number, opts?: CallOptions): Promise<{rec}>;"); }
                "restore" => { let _ = writeln!(out, "  restore(id: string, expectedVersion: number, opts?: CallOptions): Promise<{rec}>;"); }
                "beginUpload" => { let _ = writeln!(out, "  beginUpload(id: string, expectedVersion: number, input: {{ mediaType: string; byteCount: number }}): Promise<{{ record: {rec}; upload: SignedUrl }}>;"); }
                "finalizeUpload" => { let _ = writeln!(out, "  finalizeUpload(id: string, expectedVersion: number): Promise<{rec}>;"); }
                "download" => { let _ = writeln!(out, "  download(id: string): Promise<SignedUrl & {{ mediaType: string; byteCount: number; digest: string }}>;"); }
                "find" | "list" => {
                    let q = r.queries.iter().find(|q| Some(&q.name) == op.query.as_ref()).unwrap();
                    let params: Vec<String> = q.params.iter().map(|p| format!("{p}: {}", ts_type(r.record.properties.get(p).unwrap_or(&Value::Null), false))).collect();
                    let method = format!("{}{}", op.kind, upper_first(&q.name));
                    if op.kind == "find" {
                        let _ = writeln!(out, "  {method}(params: {{ {} }}): Promise<{rec} | null>;", params.join("; "));
                    } else {
                        let _ = writeln!(out, "  {method}(params: {{ {} }}, page?: PageOptions): Promise<Page<{rec}>>;", params.join("; "));
                    }
                }
                _ => {}
            }
        }
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                let exposed = r.operations.iter().any(|o| o.action.as_ref() == Some(&a.name) && o.http.is_some());
                if exposed {
                    let _ = writeln!(out, "  {}(id: string, expectedVersion: number, input: {}{}Input, opts?: CallOptions): Promise<{}Record>;", a.name, r.name, upper_first(&a.name), r.name);
                }
            }
        }
        let _ = writeln!(out, "}}\n");
    }

    let _ = writeln!(out, "export interface ForgeClient {{");
    let _ = writeln!(out, "  call(op: string, input: unknown, opts?: CallOptions): Promise<CallResult>;");
    let _ = writeln!(out, "  changesets: ChangesetsApi;");
    for r in &c.resources {
        let _ = writeln!(out, "  {}: {}Api;", camel_from_wire(&plural(&r.wire_name)), r.name);
    }
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "export function createClient(options: ClientOptions): ForgeClient {{");
    let _ = writeln!(out, "  const t = createTransport(options, operations);");
    let _ = writeln!(out, "  return {{");
    let _ = writeln!(out, "    call: t.call,");
    let _ = writeln!(out, "    changesets: {{");
    let _ = writeln!(out, "      propose: (input, opts) => t.unwrap(t.call({:?}, input, opts)),", format!("{pkg}/_/changesets.propose"));
    let _ = writeln!(out, "      get: (id) => t.unwrap(t.call({:?}, {{ id }})),", format!("{pkg}/_/changesets.get"));
    let _ = writeln!(out, "      preview: (id) => t.unwrap(t.call({:?}, {{ id }})),", format!("{pkg}/_/changesets.preview"));
    let _ = writeln!(out, "      approve: (id, contentHash) => t.unwrap(t.call({:?}, {{ id, contentHash }})),", format!("{pkg}/_/changesets.approve"));
    let _ = writeln!(out, "      commit: (id, opts) => t.unwrap(t.call({:?}, {{ id }}, opts)),", format!("{pkg}/_/changesets.commit"));
    let _ = writeln!(out, "    }},");
    for r in &c.resources {
        let _ = writeln!(out, "    {}: {{", camel_from_wire(&plural(&r.wire_name)));
        for op in &r.operations {
            if op.http.is_none() {
                continue;
            }
            let id = &op.id;
            match op.kind.as_str() {
                "create" => { let _ = writeln!(out, "      create: (input, opts) => t.unwrap(t.call({id:?}, input, opts)),"); }
                "get" => { let _ = writeln!(out, "      get: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "update" => { let _ = writeln!(out, "      update: (id, expectedVersion, patch, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion, patch }}, opts)),"); }
                "delete" => { let _ = writeln!(out, "      delete: (id, expectedVersion, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }}, opts)),"); }
                "restore" => { let _ = writeln!(out, "      restore: (id, expectedVersion, opts) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }}, opts)),"); }
                "beginUpload" => { let _ = writeln!(out, "      beginUpload: (id, expectedVersion, input) => t.unwrap(t.call({id:?}, {{ id, expectedVersion, ...input }})),"); }
                "finalizeUpload" => { let _ = writeln!(out, "      finalizeUpload: (id, expectedVersion) => t.unwrap(t.call({id:?}, {{ id, expectedVersion }})),"); }
                "download" => { let _ = writeln!(out, "      download: (id) => t.unwrap(t.call({id:?}, {{ id }})),"); }
                "find" => { let _ = writeln!(out, "      find{}: (params) => t.unwrapNullable(t.call({id:?}, {{ params }})),", upper_first(op.query.as_ref().unwrap())); }
                "list" => { let _ = writeln!(out, "      list{}: (params, page) => t.unwrap(t.call({id:?}, {{ params, ...page }})),", upper_first(op.query.as_ref().unwrap())); }
                _ => {}
            }
        }
        if let Some(lc) = &r.lifecycle {
            for a in &lc.actions {
                let opid = format!("{}.status.{}", r.id, a.name);
                if r.operations.iter().any(|o| o.id == opid && o.http.is_some()) {
                    let _ = writeln!(out, "      {}: (id, expectedVersion, input, opts) => t.unwrap(t.call({opid:?}, {{ id, expectedVersion, input }}, opts)),", a.name);
                }
            }
        }
        let _ = writeln!(out, "    }},");
    }
    let _ = writeln!(out, "  }};");
    let _ = writeln!(out, "}}");
    out
}

const RUNTIME_PRELUDE: &str = r#"export interface OperationSpec { method: string; path: string; kind: string; resource: string }
export interface ChangesetOperation { op: string; input: unknown }
export interface ChangesetItem { index: number; op: string; status: "ok" | "error" | "committed" | "skipped"; diff?: { path: string; before: unknown; after: unknown }[]; result?: unknown; error?: Problem }
export interface ChangesetBudget { mode: string; logicalOperations: number; logicalLimit: number; physicalActions: number; physicalLimit: number; atomicAllowed: boolean }
export interface Changeset { id: string; status: string; mode: "atomic" | "resumable"; operations: number; contentHash?: string; items?: ChangesetItem[]; budget?: ChangesetBudget; results?: ChangesetItem[] }
export interface ChangesetsApi {
  propose(input: { mode?: "atomic" | "resumable"; operations: ChangesetOperation[] }, opts?: CallOptions): Promise<Changeset>;
  get(id: string): Promise<Changeset>;
  preview(id: string): Promise<Changeset & { contentHash: string }>;
  approve(id: string, contentHash: string): Promise<Changeset>;
  commit(id: string, opts?: CallOptions): Promise<Changeset>;
}
export interface Page<T> { items: T[]; next: string | null; limit: number }
export interface PageOptions { cursor?: string | null; limit?: number }
export interface CallOptions { idempotencyKey?: string }
export interface SignedUrl { url: string; method: "PUT" | "GET"; headers?: Record<string, string>; expiresAt: string }
export interface ProblemField { path: string; code: string; message: string }
export interface Problem {
  type: string; title: string; status: number; code: string; detail?: string;
  requestId?: string; retryable: boolean; fields?: ProblemField[]; constraint?: string;
}
export type CallResult = { ok: true; value: unknown; version?: number } | { ok: false; code: string; status: number; problem: Problem };
export class ForgeError extends Error {
  readonly problem: Problem;
  constructor(problem: Problem) {
    super(`${problem.code}: ${problem.detail ?? problem.title}`);
    this.problem = problem;
  }
  get code() { return this.problem.code; }
  get status() { return this.problem.status; }
}
export interface ClientOptions {
  baseUrl: string;
  tenant?: string;
  actor?: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

function fillPath(path: string, input: Record<string, unknown>): string {
  return path.replace(/\{(\w+)\}/g, (_, k) => encodeURIComponent(String(input[k])));
}

export function createTransport(options: ClientOptions, ops: Record<string, OperationSpec>) {
  const f = options.fetch ?? fetch;
  const base = options.baseUrl.replace(/\/$/, "");
  async function call(op: string, rawInput: unknown, opts?: CallOptions): Promise<CallResult> {
    const spec = ops[op];
    if (!spec) throw new Error(`unknown operation ${op}`);
    const input = (rawInput ?? {}) as Record<string, unknown>;
    const headers: Record<string, string> = { accept: "application/json", ...(options.headers ?? {}) };
    if (options.tenant) headers["x-forge-tenant"] = options.tenant;
    if (options.actor) headers["x-forge-actor"] = options.actor;
    if (opts?.idempotencyKey) headers["idempotency-key"] = opts.idempotencyKey;
    if (typeof input["expectedVersion"] === "number") headers["if-match"] = `"${input["expectedVersion"]}"`;
    let url = base + fillPath(spec.path, input);
    let body: string | null = null;
    if (spec.kind === "find" || spec.kind === "list") {
      const q = new URLSearchParams();
      for (const [k, v] of Object.entries((input["params"] ?? {}) as Record<string, unknown>)) q.set(k, String(v));
      if (input["cursor"]) q.set("cursor", String(input["cursor"]));
      if (input["limit"]) q.set("limit", String(input["limit"]));
      const qs = q.toString();
      if (qs) url += "?" + qs;
    } else if (spec.kind === "create" || spec.kind === "function" || spec.kind === "changeset.propose" || spec.kind === "changeset.approve") {
      const { id: _id, ...rest } = input;
      void _id;
      body = JSON.stringify(spec.kind === "changeset.approve" ? rest : input);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "update") {
      body = JSON.stringify(input["patch"] ?? {});
      headers["content-type"] = "application/json";
    } else if (spec.kind === "beginUpload") {
      const { id: _id, expectedVersion: _v, ...rest } = input;
      void _id;
      void _v;
      body = JSON.stringify(rest);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "transition") {
      body = JSON.stringify(input["input"] ?? {});
      headers["content-type"] = "application/json";
    }
    const res = await f(url, { method: spec.method, headers, body });
    const text = await res.text();
    const json = text ? JSON.parse(text) : null;
    if (res.ok) {
      const etag = res.headers.get("etag");
      return { ok: true, value: json, ...(etag ? { version: Number(etag.replace(/"/g, "")) } : {}) };
    }
    const problem: Problem = json && json.code ? json : { type: "about:blank", title: res.statusText, status: res.status, code: "Internal", retryable: res.status >= 500 };
    return { ok: false, code: problem.code, status: res.status, problem };
  }
  async function unwrap<T>(p: Promise<CallResult>): Promise<T> {
    const r = await p;
    if (r.ok) return r.value as T;
    throw new ForgeError(r.problem);
  }
  async function unwrapNullable<T>(p: Promise<CallResult>): Promise<T | null> {
    const r = await p;
    if (r.ok) return r.value as T;
    if (r.code === "NotFound") return null;
    throw new ForgeError(r.problem);
  }
  return { call, unwrap, unwrapNullable };
}

"#;
