[package]
name = "@forgegraph/foundation/fulfillment"
version = "0.1.0"
edition = "2027"
[source]
root = "src"
entry = "src/model.forge"
[dependencies.specification]
path = "../specification"
deploy = true
[dependencies.evidence]
path = "../evidence"
deploy = true
