[package]
name = "forgegraph-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
description = "Emitters: TypeScript client, SQL migrations, app bundle"

[dependencies]
forgegraph-semantic = { path = "../forgegraph-semantic", version = "0.3.0" }
forgegraph-planner = { path = "../forgegraph-planner", version = "0.3.0" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile = "3"
