-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE classification_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE taxonomy (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id")
);

CREATE TABLE concept (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "taxonomy" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "identifiers" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "parent" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "taxonomy") REFERENCES taxonomy ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "parent") REFERENCES concept ("tenant", "id")
);

CREATE TABLE concept_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "concept" TEXT COLLATE "C" NOT NULL,
  "taxonomy" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "revision" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "parent_meaning" TEXT COLLATE "C",
  "label" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "concept") REFERENCES concept ("tenant", "id"),
  FOREIGN KEY ("tenant", "taxonomy") REFERENCES taxonomy ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES concept_revision ("tenant", "id"),
  FOREIGN KEY ("tenant", "parent_meaning") REFERENCES concept_revision ("tenant", "id")
);

CREATE TABLE classification_assignment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "classifications" TEXT COLLATE "C" NOT NULL,
  "meaning" TEXT COLLATE "C" NOT NULL,
  "recorded_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "classifications") REFERENCES classification_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "meaning") REFERENCES concept_revision ("tenant", "id")
);

CREATE TABLE classification_retraction (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "assignment" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "assignment") REFERENCES classification_assignment ("tenant", "id")
);

CREATE TABLE concept_alias (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "taxonomy" TEXT COLLATE "C" NOT NULL,
  "alias" TEXT COLLATE "C" NOT NULL,
  "meaning" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "taxonomy") REFERENCES taxonomy ("tenant", "id"),
  FOREIGN KEY ("tenant", "meaning") REFERENCES concept_revision ("tenant", "id")
);

CREATE TABLE concept_disposition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "concept" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "concept") REFERENCES concept ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES concept_revision ("tenant", "id")
);

CREATE TABLE issuer (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier_set" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C",
  "issuer_scope" TEXT COLLATE "C" NOT NULL,
  "value_" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier_set") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES issuer ("tenant", "id")
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier") REFERENCES identifier ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES identifier ("tenant", "id")
);

CREATE TABLE job_family (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "classifications" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "classifications") REFERENCES classification_set ("tenant", "id")
);

CREATE TABLE knowledge_article (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "classifications" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "classifications") REFERENCES classification_set ("tenant", "id")
);

CREATE TABLE product (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "classifications" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "classifications") REFERENCES classification_set ("tenant", "id")
);

CREATE TABLE risk_scenario (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "classifications" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "classifications") REFERENCES classification_set ("tenant", "id")
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX classification_assignment_uq_classifications_meaning ON classification_assignment ("tenant", "classifications", "meaning");
CREATE INDEX classification_assignment_ix_by_classifications ON classification_assignment ("tenant", "classifications", "id");
CREATE UNIQUE INDEX classification_retraction_uq_assignment ON classification_retraction ("tenant", "assignment");
CREATE UNIQUE INDEX concept_uq_identifiers ON concept ("tenant", "identifiers");
CREATE UNIQUE INDEX concept_uq_taxonomy_ordinal ON concept ("tenant", "taxonomy", "ordinal");
CREATE INDEX concept_ix_by_taxonomy ON concept ("tenant", "taxonomy", "ordinal", "id");
CREATE UNIQUE INDEX concept_alias_uq_taxonomy_alias ON concept_alias ("tenant", "taxonomy", "alias");
CREATE UNIQUE INDEX concept_disposition_uq_concept ON concept_disposition ("tenant", "concept");
CREATE UNIQUE INDEX concept_revision_uq_concept_revision ON concept_revision ("tenant", "concept", "revision");
CREATE INDEX concept_revision_ix_by_concept ON concept_revision ("tenant", "concept", "revision", "id");
CREATE UNIQUE INDEX taxonomy_uq_key ON taxonomy ("tenant", "key_");
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier ("tenant", "namespace", "issuer_scope", "value_");
CREATE INDEX identifier_ix_by_identifier_set ON identifier ("tenant", "identifier_set", "id");
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition ("tenant", "identifier");
CREATE UNIQUE INDEX issuer_uq_key ON issuer ("tenant", "key_");
CREATE UNIQUE INDEX job_family_uq_classifications ON job_family ("tenant", "classifications");
CREATE UNIQUE INDEX knowledge_article_uq_classifications ON knowledge_article ("tenant", "classifications");
CREATE UNIQUE INDEX product_uq_classifications ON product ("tenant", "classifications");
CREATE UNIQUE INDEX risk_scenario_uq_classifications ON risk_scenario ("tenant", "classifications");
