from pathlib import Path
import json,hashlib,subprocess,os
root=Path(__file__).resolve().parent;repo=root.parent.parent
cf=Path(os.environ.get('CF_FORGE_ROOT',str(Path.home()/'work/cf_forge/investigation')))
def command(args,cwd=repo):
 p=subprocess.run(args,cwd=cwd,capture_output=True,text=True);return {'exit':p.returncode,'stdout':p.stdout.strip(),'stderr':p.stderr.strip()}
def hashes(base,paths):return {p:hashlib.sha256((base/p).read_bytes()).hexdigest() for p in paths}
baseline={'version':'cf-forge-investigation/1','date':'2026-09-28','forgegraph':{'revision':command(['jj','--ignore-working-copy','log','-r','@-','--no-graph','-T','commit_id'])['stdout'],'baseline':'integrated main; isolated research workspace; production sources unchanged','hashes':hashes(repo,['Cargo.lock','pnpm-lock.yaml','crates/forgegraph-codegen/src/openapi_import.rs','packages/runtime/src/functions.ts'])},'cloudflareForge':{'upstreamRevision':command(['git','rev-parse','origin/main'],cf)['stdout'],'localRevision':command(['git','rev-parse','HEAD'],cf)['stdout'],'trackedDelta':command(['git','status','--short'],cf)['stdout'],'hashes':hashes(cf,['pnpm-lock.yaml','packages/forge/openapi-resolver.ts','packages/cloudflare-forge-transformer-sdk-ts/scripts/generate-from-openapi.ts','packages/cloudflare-forge-sdk-ts/custom/core/fetcher/unwrapCloudflareEnvelope.ts'])},'tools':{key:command(args) for key,args in {'node':['node','--version'],'rustc':['rustc','--version'],'pnpm':['pnpm','--version'],'docker':['docker','version','--format','{{.Server.Version}}'],'generatorImage':['docker','image','inspect','fernapi/fern-typescript-sdk:3.80.1','--format','{{.Id}}']}.items()},'packageAvailability':{name:command(['npm','view',name,'version','--registry=https://registry.npmjs.org']) for name in ['@cloudflare/forge','@cloudflare/forge-transformer-sdk-ts']},'buildWorkaround':'Pinned public Cloudflare release staged as both openapi.json inputs; no source patches. Missing optional baseline SDK skipped by builder. Fern 5.112.0 / TS generator 3.80.1, wrapper image patched by upstream build script.','workerdCompatibilityDate':'2026-09-25','fixtureProvenance':json.loads((root/'fixtures/provenance.json').read_text())}
(root/'baseline.json').write_text(json.dumps(baseline,indent=2)+'\n')
for name in ['github','cloudflare','github-next']:
 sdk=root/'.cache'/(name+'-sdk')/'sdk';m=json.loads((sdk/'sdk-map.json').read_text());(root/'results'/(name+'-sdk-map.json')).write_text(json.dumps(m,indent=2)+'\n')
 report={'sourceBytes':sum(p.stat().st_size for p in sdk.rglob('*') if p.is_file()),'files':sum(p.is_file() for p in sdk.rglob('*')),'map':m};(root/'results'/(name+'-sdk-summary.json')).write_text(json.dumps(report,indent=2)+'\n')
print('Recorded baseline, provenance, image identity and SDK summaries')
