-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE artifact (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE artifact_content (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  "upload_state" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C",
  "byte_count" BIGINT,
  "digest" TEXT COLLATE "C",
  "upload_attempt" BIGINT,
  "staged_media_type" TEXT COLLATE "C",
  "staged_byte_count" BIGINT,
  "content_generation" BIGINT,
  "sealed_generation" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE issuer (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier_set" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C",
  "issuer_scope" TEXT COLLATE "C" NOT NULL,
  "value_" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier_set") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES issuer ("tenant", "id")
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier") REFERENCES identifier ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES identifier ("tenant", "id")
);

CREATE TABLE participation_role (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE participation_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE thread (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participants" TEXT COLLATE "C" NOT NULL,
  "title" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participants") REFERENCES participation_set ("tenant", "id")
);

CREATE TABLE forge_graph_deployment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "discussion" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "discussion") REFERENCES thread ("tenant", "id")
);

CREATE TABLE kan_banger_issue (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "discussion" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "discussion") REFERENCES thread ("tenant", "id")
);

CREATE TABLE level_forge_candidate (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "discussion" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "discussion") REFERENCES thread ("tenant", "id")
);

CREATE TABLE party (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id")
);

CREATE TABLE participation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation_set" TEXT COLLATE "C" NOT NULL,
  "participant" TEXT COLLATE "C" NOT NULL,
  "role" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation_set") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "role") REFERENCES participation_role ("tenant", "id")
);

CREATE TABLE thread_participant (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "membership" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "membership") REFERENCES participation ("tenant", "id")
);

CREATE TABLE thread_entry (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "author" TEXT COLLATE "C" NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  "corrects" TEXT COLLATE "C",
  "recorded_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "author") REFERENCES thread_participant ("tenant", "id"),
  FOREIGN KEY ("tenant", "corrects") REFERENCES thread_entry ("tenant", "id")
);

CREATE TABLE mention (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "entry" TEXT COLLATE "C" NOT NULL,
  "participant" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "entry") REFERENCES thread_entry ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES thread_participant ("tenant", "id")
);

CREATE TABLE reaction (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "entry" TEXT COLLATE "C" NOT NULL,
  "author" TEXT COLLATE "C" NOT NULL,
  "code" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "entry") REFERENCES thread_entry ("tenant", "id"),
  FOREIGN KEY ("tenant", "author") REFERENCES thread_participant ("tenant", "id")
);

CREATE TABLE participation_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "revoked" BIGINT NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation") REFERENCES participation ("tenant", "id")
);

CREATE TABLE principal_representation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  "principal" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id")
);

CREATE TABLE representation_revocation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "representation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "representation") REFERENCES principal_representation ("tenant", "id")
);

CREATE TABLE repository (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "provider" TEXT COLLATE "C" NOT NULL,
  "locator" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE specification_pin (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "repository" TEXT COLLATE "C" NOT NULL,
  "anchor" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "repository") REFERENCES repository ("tenant", "id")
);

CREATE TABLE realization (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pin" TEXT COLLATE "C" NOT NULL,
  "build_hash" TEXT COLLATE "C" NOT NULL,
  "manifest_digest" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pin") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE artifact_component (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE artifact_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "artifact" TEXT COLLATE "C" NOT NULL,
  "content" TEXT COLLATE "C" NOT NULL,
  "digest" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C" NOT NULL,
  "byte_count" BIGINT NOT NULL,
  "specification_pin" TEXT COLLATE "C",
  "realization" TEXT COLLATE "C",
  "components" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "artifact") REFERENCES artifact ("tenant", "id"),
  FOREIGN KEY ("tenant", "content") REFERENCES artifact_content ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification_pin") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "realization") REFERENCES realization ("tenant", "id"),
  FOREIGN KEY ("tenant", "components") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE attachment_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "entry" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "entry") REFERENCES thread_entry ("tenant", "id"),
  FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE thread_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "thread" TEXT COLLATE "C" NOT NULL,
  "sequence" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "kind" TEXT COLLATE "C" NOT NULL,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "closed" BIGINT NOT NULL,
  "entry" TEXT COLLATE "C",
  "reaction" TEXT COLLATE "C",
  "mention" TEXT COLLATE "C",
  "attachment" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "thread") REFERENCES thread ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES thread_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "actor") REFERENCES thread_participant ("tenant", "id"),
  FOREIGN KEY ("tenant", "entry") REFERENCES thread_entry ("tenant", "id"),
  FOREIGN KEY ("tenant", "reaction") REFERENCES reaction ("tenant", "id"),
  FOREIGN KEY ("tenant", "mention") REFERENCES mention ("tenant", "id"),
  FOREIGN KEY ("tenant", "attachment") REFERENCES attachment_link ("tenant", "id")
);

ALTER TABLE artifact_component ADD FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id");

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX artifact_uq_key ON artifact ("tenant", "key_");
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision ("tenant", "content");
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision ("tenant", "artifact", "id");
CREATE UNIQUE INDEX attachment_link_uq_entry_revision ON attachment_link ("tenant", "entry", "revision");
CREATE UNIQUE INDEX mention_uq_entry_participant ON mention ("tenant", "entry", "participant");
CREATE UNIQUE INDEX reaction_uq_entry_author_code ON reaction ("tenant", "entry", "author", "code");
CREATE UNIQUE INDEX thread_entry_uq_corrects ON thread_entry ("tenant", "corrects");
CREATE UNIQUE INDEX thread_event_uq_attachment ON thread_event ("tenant", "attachment");
CREATE UNIQUE INDEX thread_event_uq_entry ON thread_event ("tenant", "entry");
CREATE UNIQUE INDEX thread_event_uq_mention ON thread_event ("tenant", "mention");
CREATE UNIQUE INDEX thread_event_uq_reaction ON thread_event ("tenant", "reaction");
CREATE UNIQUE INDEX thread_event_uq_thread_sequence ON thread_event ("tenant", "thread", "sequence");
CREATE INDEX thread_event_ix_by_thread ON thread_event ("tenant", "thread", "sequence", "id");
CREATE UNIQUE INDEX thread_participant_uq_thread_membership ON thread_participant ("tenant", "thread", "membership");
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier ("tenant", "namespace", "issuer_scope", "value_");
CREATE INDEX identifier_ix_by_identifier_set ON identifier ("tenant", "identifier_set", "id");
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition ("tenant", "identifier");
CREATE UNIQUE INDEX issuer_uq_key ON issuer ("tenant", "key_");
CREATE UNIQUE INDEX participation_uq_participationSet_participant_role_validFrom ON participation ("tenant", "participation_set", "participant", "role", "valid_from");
CREATE INDEX participation_ix_by_participant ON participation ("tenant", "participant", "id");
CREATE INDEX participation_ix_by_participation_set ON participation ("tenant", "participation_set", "id");
CREATE UNIQUE INDEX participation_end_uq_participation ON participation_end ("tenant", "participation");
CREATE UNIQUE INDEX participation_role_uq_namespace_name ON participation_role ("tenant", "namespace", "name");
CREATE UNIQUE INDEX party_uq_identifiers ON party ("tenant", "identifiers");
CREATE UNIQUE INDEX principal_representation_uq_principal_party_validFrom ON principal_representation ("tenant", "principal", "party", "valid_from");
CREATE INDEX principal_representation_ix_by_party ON principal_representation ("tenant", "party", "id");
CREATE INDEX principal_representation_ix_by_principal ON principal_representation ("tenant", "principal", "id");
CREATE UNIQUE INDEX representation_revocation_uq_representation ON representation_revocation ("tenant", "representation");
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization ("tenant", "pin", "build_hash", "manifest_digest");
CREATE INDEX realization_ix_by_pin ON realization ("tenant", "pin", "id");
CREATE UNIQUE INDEX repository_uq_key ON repository ("tenant", "key_");
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin ("tenant", "repository", "anchor", "revision");
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin ("tenant", "repository", "anchor", "id");
