[package]
name = "@foundation-app/latchflow"
version = "0.1.0"
edition = "2027"

[dependencies.operations]
path = "../../../../packages/foundation/operations"
deploy = true
[dependencies.specification]
path = "../../../../packages/foundation/specification"
deploy = true
