#!/usr/bin/env node
/**
 * Resolve `wrangler.jsonc` against your own account.
 *
 * The committed config carries placeholders, because a public repository must
 * not name someone else's D1 database or workers.dev subdomain. This writes a
 * gitignored copy with your values substituted and prints its path, so
 * `wrangler --config "$(node resolve-config.mjs)"` deploys to your account
 * without the placeholders ever being edited in place (and accidentally
 * committed).
 *
 *   FORGE_D1_DATABASE_ID   required: `wrangler d1 list` → the id of your forge-acme database
 *   FORGE_WORKERS_SUBDOMAIN optional: your workers.dev subdomain, for the CORS allowlist
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "wrangler.jsonc");
const out = join(here, "wrangler.local.jsonc");

const databaseId = process.env["FORGE_D1_DATABASE_ID"];
if (!databaseId) {
  console.error(
    "FORGE_D1_DATABASE_ID is not set.\n" +
      "  wrangler d1 create forge-acme    # once, if you have not already\n" +
      "  wrangler d1 list                 # then export the id of forge-acme",
  );
  process.exit(1);
}
if (!/^[0-9a-f-]{36}$/.test(databaseId)) {
  console.error(`FORGE_D1_DATABASE_ID=${databaseId} is not a database id (expected a uuid)`);
  process.exit(1);
}

let text = readFileSync(source, "utf8");
text = text.replace(/"database_id":\s*"[^"]*"/, `"database_id": "${databaseId}"`);
const subdomain = process.env["FORGE_WORKERS_SUBDOMAIN"];
if (subdomain) text = text.replace(/forge-acme-workspace\.example\.workers\.dev/g, `forge-acme-workspace.${subdomain}.workers.dev`);

writeFileSync(out, `// Generated by resolve-config.mjs from wrangler.jsonc. Gitignored; do not commit.\n${text}`);
console.log(out);
