[package]
name = "@forgegraph/foundation/publication"
version = "0.1.0"
edition = "2027"
[dependencies]
decision = { path = "../decision", deploy = true }
specification = { path = "../specification", deploy = true }
artifact = { path = "../artifact", deploy = true }
evaluations = { path = "../evaluation", deploy = true }
evidence = { path = "../evidence", deploy = true }
participation = { path = "../participation", deploy = true }
