-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE ledger_book (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE account (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "book" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "book") REFERENCES ledger_book ("tenant", "id")
);

CREATE TABLE entry (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "book" TEXT COLLATE "C" NOT NULL,
  "account" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "book") REFERENCES ledger_book ("tenant", "id"),
  FOREIGN KEY ("tenant", "account") REFERENCES account ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES entry ("tenant", "id")
);

CREATE TABLE posting_group (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "book" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "claim" TEXT COLLATE "C" NOT NULL,
  "head" TEXT COLLATE "C" NOT NULL,
  "policy" TEXT COLLATE "C" NOT NULL,
  "reversal_of" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "book") REFERENCES ledger_book ("tenant", "id"),
  FOREIGN KEY ("tenant", "head") REFERENCES entry ("tenant", "id"),
  FOREIGN KEY ("tenant", "reversal_of") REFERENCES posting_group ("tenant", "id")
);

CREATE TABLE compute_credits (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "account" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "account") REFERENCES account ("tenant", "id")
);

CREATE TABLE inventory (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "account" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "account") REFERENCES account ("tenant", "id")
);

CREATE TABLE money (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "account" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "account") REFERENCES account ("tenant", "id")
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX account_uq_book_key ON account ("tenant", "book", "key_");
CREATE UNIQUE INDEX ledger_book_uq_key ON ledger_book ("tenant", "key_");
CREATE UNIQUE INDEX posting_group_uq_book_claim ON posting_group ("tenant", "book", "claim");
CREATE UNIQUE INDEX posting_group_uq_book_key ON posting_group ("tenant", "book", "key_");
CREATE INDEX posting_group_ix_by_book ON posting_group ("tenant", "book", "id");
