import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { agreement } from './helpers/agreement.js';
import { Campaigns } from '../src/foundation/campaign.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Notifications } from '../src/foundation/notifications.js';
import { Collaborations } from '../src/foundation/collaboration.js';
import { Measurements } from '../src/foundation/measurement.js';
const p = '@forgegraph/foundation/campaign/_/', n = '@forgegraph/foundation/notifications/_/', b = '@forgegraph/foundation/planning-budget/_/', m = '@forgegraph/foundation/measurement/_/', c = '@forgegraph/foundation/collaboration/_/';
for (const adapter of foundationAdapters) it(`${adapter}: campaign lifecycle, reusable audiences, complete waves, interaction attribution and metrics`, async () => {
 const h = await foundation('campaign', adapter, true), run = Effect.runPromise;
 try {
  const { engine, call, ctx } = h, contract = await agreement(h), from = '2026-02-02T00:00:00Z', until = '2026-02-03T00:00:00Z';
  const service = new Campaigns(engine, (audience, route) => Effect.succeed(audience.selector === contract.pin.id && route.channel === contract.pin.id));
  const topic = await call(n + 'NotificationTopic.create', { key: 'outreach', label: 'Outreach' }), audience = await call(p + 'CampaignAudience.create', { key: 'eligible', selector: contract.pin.id, topic: topic.id });
  const plan = await call(b + 'Plan.create', { definition: contract.pin.id, label: 'Campaign plan', classification: null }), goal = await call(b + 'Goal.create', { plan: plan.id, metric: 'responses', unit: 'count', target: '1' }), subject = await call(m + 'MetricSubject.create', { key: 'campaign' });
  const campaign = await call(p + 'Campaign.create', { key: 'outreach', audience: audience.id, objective: goal.id, plan: plan.id, budget: null, content: null, offer: contract.contract.offer, channel: contract.pin.id, metricSubject: subject.id, from, until });
  expect((await run(service.state(String(campaign.id), ctx))).phase).toBe('draft');
  const active = await run(service.act({ campaign: String(campaign.id), previous: null, kind: 'activate', at: from }, ctx));
  const wave = await call(p + 'CampaignWave.create', { campaign: campaign.id, key: 'first', from, until, appointment: null, memberCount: 1 });
  await expect(run(service.act({ campaign: String(campaign.id), previous: String(active.id), kind: 'wave', wave: String(wave.id), at: from }, ctx))).rejects.toThrow();
  const destination = await call('@forgegraph/foundation/delivery/_/DeliveryDestination.create', { key: 'email', label: 'Email' }), endpoint = await call(n + 'NotificationEndpointLink.create', { recipient: contract.signers[1]!.id, destination: destination.id }), subscription = await call(n + 'NotificationSubscription.create', { topic: topic.id, recipient: contract.signers[1]!.id, endpoint: endpoint.id }), preference = await call(n + 'NotificationPreference.create', { subscription: subscription.id, revision: 1, previous: null, enabled: true, reason: 'Opted in' });
  const bundle = await call('@forgegraph/foundation/evidence/_/EvidenceBundle.create', { key: 'reachability', label: 'Contact evidence' }), seal = await run(new Evidence(engine).seal(String(bundle.id), null, ctx));
  const route = await call(p + 'CampaignRoute.create', { endpoint: endpoint.id, channel: contract.pin.id, from, until, support: seal.id });
  const notice = await run(new Notifications(engine).create({ key: 'first', subscription: String(subscription.id), preference: String(preference.id), at: from }, ctx));
  const member = await call(p + 'CampaignMember.create', { wave: wave.id, ordinal: 1, notification: notice.id, route: route.id });
  await expect(run(service.wave(String(wave.id), ctx))).rejects.toThrow();
  await expect(run(new Campaigns(engine, () => Effect.succeed(false)).act({ campaign: String(campaign.id), previous: String(active.id), kind: 'wave', wave: String(wave.id), at: from }, ctx))).rejects.toThrow();
  const admitted = await run(service.act({ campaign: String(campaign.id), previous: String(active.id), kind: 'wave', wave: String(wave.id), at: from }, ctx));
  expect((await run(service.wave(String(wave.id), ctx))).members).toHaveLength(1);
  const paused = await run(service.act({ campaign: String(campaign.id), previous: String(admitted.id), kind: 'pause', at: from }, ctx));
  await expect(run(service.act({ campaign: String(campaign.id), previous: String(admitted.id), kind: 'close', at: from }, ctx))).rejects.toThrow();
  expect((await run(service.wave(String(wave.id), ctx))).campaign.phase).toBe('paused');
  const thread = await call(c + 'Thread.create', { participants: contract.participants.id, title: 'Response' }), actor = await call(c + 'ThreadParticipant.create', { thread: thread.id, membership: contract.signers[1]!.id }), entry = await call(c + 'ThreadEntry.create', { thread: thread.id, author: actor.id, body: 'Interested', corrects: null, recordedAt: from });
  const event = await run(new Collaborations(engine).publish({ thread: String(thread.id), actor: String(actor.id), kind: 'Entry', fact: String(entry.id), previous: null, at: from }, ctx)), response = await call(p + 'CampaignResponse.create', { member: member.id, interaction: event.id, attribution: contract.pin.id, kind: 'interest' });
  expect((await run(service.response(String(response.id), ctx))).event.id).toBe(event.id);
  const wrongActor = await call(c + 'ThreadParticipant.create', { thread: thread.id, membership: contract.signers[0]!.id }), wrongEntry = await call(c + 'ThreadEntry.create', { thread: thread.id, author: wrongActor.id, body: 'Unrelated', corrects: null, recordedAt: from }), wrongEvent = await run(new Collaborations(engine).publish({ thread: String(thread.id), actor: String(wrongActor.id), kind: 'Entry', fact: String(wrongEntry.id), previous: String(event.id), at: from }, ctx)), wrongResponse = await call(p + 'CampaignResponse.create', { member: member.id, interaction: wrongEvent.id, attribution: contract.pin.id, kind: 'interest' });
  await expect(run(service.response(String(wrongResponse.id), ctx))).rejects.toThrow();
  const source = await call('@forgegraph/foundation/evidence/_/EvidenceSource.create', { key: 'responses', label: 'Response counter' }), metric = await call(m + 'MetricDefinition.create', { key: 'responses', definition: contract.pin.id, dimension: 'count', unit: 'count', semantics: contract.pin.id });
  const observation = await run(new Measurements(engine).record({ key: 'responses', metric: String(metric.id), subject: String(subject.id), observedAt: from, value: '1', unit: 'count', source: String(source.id), sourceRecord: String(response.id) }, ctx)), objective = await call(m + 'MetricObjective.create', { key: 'responses', metric: metric.id, subject: subject.id, policy: contract.pin.id, target: '1', minimum: '1', maximum: null, from, until }), assessment = await call(m + 'PerformanceAssessment.create', { objective: objective.id, observation: observation.id, evaluation: null }), performance = await call(p + 'CampaignPerformance.create', { campaign: campaign.id, assessment: assessment.id, objective: objective.id });
  expect((await run(service.performance(String(performance.id), ctx))).assessment.actual).toBe('1.000000');
  for (const name of ['MarketingCampaign', 'PublicHealthCampaign', 'RecruitingCampaign', 'SecurityAwarenessCampaign']) await call('@fixture/campaign-consumer/_/' + name + '.create', { campaign: campaign.id, purpose: name });
  await call(p + 'CampaignRouteEnd.create', { route: route.id, at: from, reason: 'Withdrawn' });
  await expect(run(service.wave(String(wave.id), ctx))).rejects.toThrow();
  const closed = await run(service.act({ campaign: String(campaign.id), previous: String(paused.id), kind: 'close', at: until }, ctx));
  await expect(run(service.act({ campaign: String(campaign.id), previous: String(closed.id), kind: 'resume', at: until }, ctx))).rejects.toThrow();
  await expect(run(service.state(String(campaign.id), { ...ctx, tenant: 'foreign' }))).rejects.toThrow();
 } finally { await h.close(); }
});
