import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { Cases, type CaseAction } from '../src/foundation/case-management.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Evaluations } from '../src/foundation/evaluation.js';
import { Decisions } from '../src/foundation/decision.js';
import { Participations } from '../src/foundation/participation.js';
import { Engine } from '../src/engine.js';
import { localAuthorizer } from '../src/gatekeeper.js';
const p = '@forgegraph/foundation/case-management/_/', s = '@forgegraph/foundation/specification/_/', e = '@forgegraph/foundation/evaluation/_/', f = '@forgegraph/foundation/fulfillment/_/';
for (const adapter of foundationAdapters) it(`${adapter}: adaptive case activity, responsibility, milestones, close/reopen and races`, async () => {
 const h = await foundation('case-management', adapter, true), run = Effect.runPromise;
 try {
  const { call, engine, ctx } = h, cases = new Cases(engine);
  const repository = await call(s + 'Repository.create', { key: 'cases', provider: 'git', locator: 'https://example.test/cases' });
  const pin = await call(s + 'SpecificationPin.create', { repository: repository.id, anchor: 'criteria', revision: 'd'.repeat(40) });
  const owner = await call('@forgegraph/foundation/party/_/Party.create', { label: 'Owner' }), specialist = await call('@forgegraph/foundation/party/_/Party.create', { label: 'Specialist' });
  const participants = await call('@forgegraph/foundation/participation/_/ParticipationSet.create', { label: 'Case team' });
  const subject = await call(p + 'CaseSubject.create', { key: 'subject' });
  const input = { subject: subject.id, context: pin.id, reason: 'Investigate an evolving problem', owner: owner.id, participants: participants.id, openedAt: '2026-01-01T00:00:00Z' };
  const record = await call(p + 'Case.create', { ...input, key: 'case' });
  const related = await call(p + 'Case.create', { ...input, key: 'specialist-case' });
  const id = String(record.id), at = '2026-01-02T12:00:00Z';
  const act = async (kind: CaseAction, fact?: string, newOwner?: string) => run(cases.act({ case: id, previous: (await run(cases.state(id, ctx))).head, kind, at, reason: kind, ...(fact ? { fact } : {}), ...(newOwner ? { owner: newOwner } : {}) }, ctx));
  for (const [name, field] of [['SupportCase', 'product'], ['CareEpisode', 'service'], ['InvestigationCase', 'allegation'], ['LegalMatter', 'jurisdiction']]) await call('@fixture/case-management-consumer/_/' + name + '.create', { case: record.id, [field!]: name });
  const bundle = await call('@forgegraph/foundation/evidence/_/EvidenceBundle.create', { key: 'file', label: 'Case file' });
  const seal = await run(new Evidence(engine).seal(String(bundle.id), null, ctx));
  const file = await call(p + 'CaseFile.create', { case: id, evidence: seal.id, document: null });
  expect((await run(cases.state(id, ctx))).events).toHaveLength(0);
  await act('file', String(file.id));
  const thread = await call('@forgegraph/foundation/collaboration/_/Thread.create', { participants: participants.id, title: 'Consultation' });
  const interaction = await call(p + 'CaseInteraction.create', { case: id, discussion: thread.id, purpose: pin.id, from: at, until: null });
  await act('interaction', String(interaction.id));
  const set = await call(f + 'FulfillmentSet.create', { label: 'Case work' }), executor = await call(f + 'FulfillmentExecutor.create', { key: 'worker' });
  const work = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 1, specificationPin: pin.id, executor: executor.id, requestedAt: at, evidence: null });
  await act('work', String(work.id));
  const membership = new Participations(engine, { namespace: 'case', roles: ['reviewer'] });
  await run(membership.registerRole('reviewer', ctx));
  const reviewer = await run(membership.add({ participationSet: String(participants.id), participant: String(owner.id), role: 'reviewer', validFrom: '2025-01-01T00:00:00Z', reason: 'Appointed' }, ctx));
  const decisions = new Decisions(engine);
  const decision = await run(decisions.open({ participationSet: String(participants.id), electors: [String(reviewer.id)], eligibilityAt: '2026-01-01T00:00:00Z', deadline: '2027-01-01T00:00:00Z', options: ['Satisfied', 'Unsatisfied'], rule: 'Single', threshold: 1 }, ctx));
  await act('decision', String(decision.id));
  const evaluationSet = await call(e + 'EvaluationSet.create', { label: 'Entry criteria' }), evalExecutor = await call(e + 'EvaluationExecutor.create', { key: 'assessor', label: 'Assessor' });
  const evaluations = new Evaluations(engine), evaluationRun = await run(evaluations.create({ evaluationSet: String(evaluationSet.id), definition: String(pin.id), executor: String(evalExecutor.id) }, ctx));
  await run(evaluations.start(String(evaluationRun.id), '2026-01-01T10:00:00Z', ctx));
  const finish = await run(evaluations.finish(String(evaluationRun.id), 'Completed', '2026-01-01T11:00:00Z', 'Assessment completed', ctx));
  const accepted = (await run(decisions.state(String(decision.id), ctx))).options[0]!;
  const milestone = await call(p + 'CaseMilestone.create', { case: id, key: 'triaged', criteria: pin.id, run: evaluationRun.id, evaluation: finish.id, support: seal.id, approval: decision.id, accepted: accepted.id });
  await expect(act('milestone', String(milestone.id))).rejects.toThrow();
  await run(decisions.respond(String(decision.id), String(reviewer.id), [0], ctx));
  await run(decisions.finalize(String(decision.id), ctx));
  await act('milestone', String(milestone.id));
  await expect(act('milestone', String(milestone.id))).rejects.toThrow();
  await act('transfer', undefined, String(specialist.id));
  expect((await run(cases.state(id, ctx))).owner).toBe(specialist.id);
  await act('escalate', String(related.id));
  await act('relate', String(related.id));
  const previous = (await run(cases.state(id, ctx))).head;
  const races = await Promise.allSettled(['close', 'file'].map(kind => run(cases.act({ case: id, previous, kind: kind as CaseAction, at, reason: 'race', ...(kind === 'file' ? { fact: String(file.id) } : {}) }, ctx))));
  expect(races.filter(r => r.status === 'fulfilled')).toHaveLength(1);
  if (!(await run(cases.state(id, ctx))).closed) await act('close');
  await expect(act('work', String(work.id))).rejects.toThrow();
  await act('reopen');
  expect((await run(cases.state(id, ctx))).closed).toBe(false);
  await expect(act('reopen')).rejects.toThrow();
  const foreignFile = await call(p + 'CaseFile.create', { case: related.id, evidence: seal.id, document: null });
  await expect(act('file', String(foreignFile.id))).rejects.toThrow();
  await expect(run(cases.state(id, { ...ctx, tenant: 'other' }))).rejects.toThrow();
  const guarded = new Engine(engine.model, engine.layer);
  guarded.gatekeeper.authorizer = localAuthorizer({ policies: engine.model.resources.filter(r => r.id !== p + 'CaseEvent').map(r => ({ id: r.id, actions: [r.id + '.*'], requires: [], where: [] })), pips: [], epoch: 2, knownObligations: [] });
  await expect(run(new Cases(guarded).state(id, ctx))).rejects.toThrow();
 } finally { await h.close(); }
});
