import { Effect } from 'effect';
import { expect,it } from 'vitest';
import { foundation,foundationAdapters } from './helpers/foundation.js';
import { Attestations } from '../src/foundation/attestation.js';
import { Qualifications } from '../src/foundation/qualification.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Artifacts } from '../src/foundation/artifact.js';
import { Engine } from '../src/engine.js';
import { localAuthorizer } from '../src/gatekeeper.js';
const p='@forgegraph/foundation/attestation/_/',q='@forgegraph/foundation/qualification/_/',sp='@forgegraph/foundation/specification/_/',e='@forgegraph/foundation/evidence/_/',a='@forgegraph/foundation/artifact/_/';
const start='2026-01-01T00:00:00Z',end='2026-02-01T00:00:00Z';
for(const adapter of foundationAdapters)it(`${adapter}: standalone assertions, typed qualification and proof profiles`,async()=>{
 const f=await foundation('attestation',adapter,true),run=Effect.runPromise;
 try{
  const {engine,call,ctx}=f,service=new Attestations(engine);
  const repo=await call(sp+'Repository.create',{key:'claims',provider:'git',locator:'https://example.test/claims'}),pin=await call(sp+'SpecificationPin.create',{repository:repo.id,anchor:'compliance',revision:'a'.repeat(40)});
  const party=await call('@forgegraph/foundation/party/_/Party.create',{label:'Issuer organization'});
  const issuer=await call(p+'AttestationSubject.create',{label:'Issuer'}),subject=await call(p+'AttestationSubject.create',{label:'Credential holder'});
  const issuerLink=await call(p+'AttestationPartySubject.create',{subject:issuer.id,party:party.id});
  const target=await call(q+'QualificationSubject.create',{label:'Holder'}),targetLink=await call(p+'AttestationQualificationSubject.create',{subject:subject.id,qualificationSubject:target.id});
  const bundle=await call(e+'EvidenceBundle.create',{key:'claims',label:'Claim support'}),seal=await run(new Evidence(engine).seal(String(bundle.id),null,ctx));
  const input={issuer:String(issuer.id),subject:String(subject.id),issuerRecord:'declaration',specification:String(pin.id),issuedAt:start,validFrom:start,validUntil:end,conclusion:'Issuer declares compliance',source:'issuer:declaration/1',support:String(seal.id)};
  const assertion=await run(service.issue(input,ctx));
  for(const [name,field] of [['ComplianceDeclaration','regulation'],['CredentialAssertion','credentialKey']])await call('@fixture/attestation-consumer/_/'+name+'.create',{assertion:assertion.id,[field!]:'typed-external-profile'});
  expect(await run(service.current(String(assertion.id),start,ctx))).toMatchObject({id:assertion.id});
  expect(await run(service.current(String(assertion.id),end,ctx))).toBeNull();
  await expect(run(service.issue(input,ctx))).rejects.toMatchObject({code:'UniqueConflict'});
  const definition=await call(q+'QualificationDefinition.create',{key:'compliance',pin:pin.id,label:'Compliance qualification'});
  const qualification=await run(new Qualifications(engine).award({subject:String(target.id),definition:String(definition.id),issuer:String(party.id),issuerRecord:'credential',issuedAt:start,expiresAt:end,support:String(seal.id)},ctx));
  const link=await call(p+'QualificationAttestation.create',{qualification:qualification.id,definition:definition.id,subject:targetLink.id,issuer:issuerLink.id,attestation:assertion.id});
  expect((await run(service.qualification(String(link.id),start,ctx))).valid).toBe(true);
  const artifact=await call(a+'Artifact.create',{key:'signed-provenance',label:'Signature envelope'}),content=await call(a+'ArtifactContent.create',{});
  const upload=await call(a+'ArtifactContent.beginUpload',{id:content.id,expectedVersion:1,mediaType:'application/octet-stream',byteCount:1});
  await f.objects.simulateUpload((upload.upload as {url:string}).url,new TextEncoder().encode('s'),'application/octet-stream');
  const sealed=await call(a+'ArtifactContent.finalizeUpload',{id:content.id,expectedVersion:2});
  const revision=await run(new Artifacts(engine).publish({artifact:String(artifact.id),content:String(content.id),digest:String(sealed.digest)},ctx));
  const software=await call(p+'AttestationSubject.create',{label:'Software artifact'}),softwareLink=await call(p+'AttestationArtifactSubject.create',{subject:software.id,revision:revision.id});
  const provenance=await run(service.issue({...input,issuerRecord:'software',subject:String(software.id),proof:String(revision.id)},ctx));
  await call('@fixture/attestation-consumer/_/SoftwareProvenance.create',{assertion:provenance.id,subject:softwareLink.id});
  await expect(call(p+'QualificationAttestation.create',{qualification:qualification.id,definition:definition.id,subject:targetLink.id,issuer:issuerLink.id,attestation:provenance.id})).rejects.toMatchObject({code:'ValidationFailed'});
  const replacement=await run(service.issue({...input,issuerRecord:'replacement',validFrom:'2026-01-15T00:00:00Z'},ctx));
  const ended=await Promise.allSettled([run(service.end(String(assertion.id),'2026-01-15T00:00:00Z','Superseded',ctx,String(replacement.id))),run(service.end(String(assertion.id),'2026-01-15T00:00:00Z','Revoked',ctx))]);
  expect(ended.filter(x=>x.status==='fulfilled')).toHaveLength(1);
  expect((await run(service.qualification(String(link.id),'2026-01-16T00:00:00Z',ctx))).valid).toBe(false);
  expect(await run(service.current(String(assertion.id),start,ctx))).not.toBeNull();
  await expect(call(p+'Attestation.delete',{id:assertion.id})).rejects.toThrow();
  await expect(run(service.current(String(assertion.id),start,{...ctx,tenant:'foreign'}))).rejects.toThrow();
  const guarded=new Engine(engine.model,engine.layer);guarded.gatekeeper.authorizer=localAuthorizer({policies:engine.model.resources.filter(r=>r.id!==p+'AttestationEnd').map(r=>({id:r.id,actions:[r.id+'.*'],requires:[],where:[]})),pips:[],epoch:2,knownObligations:[]});
  await expect(run(new Attestations(guarded).current(String(assertion.id),start,ctx))).rejects.toThrow();
 }finally{await f.close();}
});
