import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { agreement } from './helpers/agreement.js';
import { Incidents } from '../src/foundation/incident-problem.js';
import { Cases } from '../src/foundation/case-management.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Evaluations } from '../src/foundation/evaluation.js';
import { Fulfillments } from '../src/foundation/fulfillment.js';
import { ServiceLevels } from '../src/foundation/service-level.js';
const p = '@forgegraph/foundation/incident-problem/_/', c = '@forgegraph/foundation/case-management/_/', f = '@forgegraph/foundation/fulfillment/_/', e = '@forgegraph/foundation/evaluation/_/', sla = '@forgegraph/foundation/service-level/_/';
for (const adapter of foundationAdapters) it(`${adapter}: incident correlation, known problems, verified resolution, reopening and SLA`, async () => {
 const h = await foundation('incident-problem', adapter, true), run = Effect.runPromise;
 try {
  const { call, engine, ctx } = h, contract = await agreement(h), service = new Incidents(engine), cases = new Cases(engine), at = '2026-02-02T00:00:00Z', finished = '2026-02-02T01:00:00Z';
  const subject = await call(c + 'CaseSubject.create', { key: 'service' });
  const caseInput = { subject: subject.id, context: contract.pin.id, reason: 'Service degradation', owner: contract.supplier.id, participants: contract.participants.id, openedAt: at };
  const incidentCase = await call(c + 'Case.create', { ...caseInput, key: 'incident' }), problemCase = await call(c + 'Case.create', { ...caseInput, key: 'problem' });
  const bundle = await call('@forgegraph/foundation/evidence/_/EvidenceBundle.create', { key: 'outage', label: 'Evidence' }), seal = await run(new Evidence(engine).seal(String(bundle.id), null, ctx));
  const set = await call(f + 'FulfillmentSet.create', { label: 'Remediation' }), executor = await call(f + 'FulfillmentExecutor.create', { key: 'engineer' }), fulfillment = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 1, specificationPin: contract.pin.id, executor: executor.id, requestedAt: at, evidence: null });
  const issuance = (await run(contract.catalog.state(String(contract.contract.id), at, ctx))).issuance!;
  const policy = await call(sla + 'ServiceLevelPolicy.create', { key: 'response', specification: contract.pin.id, clock: 'UTC', calendar: null }), objective = await call(sla + 'ServiceLevelObjective.create', { policy: policy.id, name: 'restore', targetMinutes: 60, warningMinutes: 30 });
  const level = await run(new ServiceLevels(engine).start({ key: 'outage', objective: String(objective.id), agreement: String(contract.contract.id), right: String(issuance.right), fulfillment: String(fulfillment.id), startedAt: at, horizon: '2026-02-03T00:00:00Z' }, ctx));
  const incident = await call(p + 'Incident.create', { key: 'outage', case: incidentCase.id, occurredAt: at, description: 'Service unavailable', source: seal.id, serviceLevel: level.id, risk: null, finding: null });
  expect((await run(service.incident(String(incident.id), '2026-02-02T00:45:00Z', ctx))).serviceLevel!.verdict).toBe('AtRisk');
  const evalSet = await call(e + 'EvaluationSet.create', { label: 'Diagnosis' }), evaluator = await call(e + 'EvaluationExecutor.create', { key: 'reviewer', label: 'Reviewer' }), evaluations = new Evaluations(engine), diagnosis = await run(evaluations.create({ evaluationSet: String(evalSet.id), definition: String(contract.pin.id), executor: String(evaluator.id) }, ctx));
  await run(evaluations.start(String(diagnosis.id), at, ctx));
  const diagnosed = await run(evaluations.finish(String(diagnosis.id), 'Completed', finished, 'Diagnosed', ctx));
  const approval = await run(contract.decisions.open({ participationSet: String(contract.participants.id), electors: [String(contract.signers[0]!.id)], eligibilityAt: '2026-01-01T00:00:00Z', options: ['Accept', 'Reject'], rule: 'Single', deadline: '2027-01-01T00:00:00Z' }, ctx)), option = (await run(contract.decisions.state(String(approval.id), ctx))).options[0]!;
  const problem = await call(p + 'Problem.create', { key: 'root-cause', case: problemCase.id, hypothesis: contract.pin.id, support: seal.id, diagnosis: diagnosis.id, approval: approval.id, accepted: option.id });
  const correlation = await call(p + 'IncidentCorrelation.create', { incident: incident.id, problem: problem.id, rationale: 'Same dependency failure', support: seal.id });
  const known = await call(p + 'KnownProblem.create', { problem: problem.id, diagnosis: diagnosed.id, workaround: contract.pin.id, support: seal.id, at: finished });
  await expect(run(service.known(String(known.id), ctx))).rejects.toThrow();
  await run(contract.decisions.respond(String(approval.id), String(contract.signers[0]!.id), [0], ctx)); await run(contract.decisions.finalize(String(approval.id), ctx));
  expect((await run(service.known(String(known.id), ctx))).problem.row.id).toBe(problem.id);
  const verificationRun = await run(evaluations.create({ evaluationSet: String(evalSet.id), definition: String(contract.pin.id), executor: String(evaluator.id) }, ctx));
  const remediation = await call(p + 'ProblemRemediation.create', { problem: problem.id, fulfillment: fulfillment.id, change: null, verification: verificationRun.id, approval: approval.id, accepted: option.id });
  await run(evaluations.start(String(verificationRun.id), at, ctx));
  const verificationEnd = await run(evaluations.finish(String(verificationRun.id), 'Completed', finished, 'Verified', ctx)), verification = await call(p + 'ProblemVerification.create', { remediation: remediation.id, evaluation: verificationEnd.id, support: seal.id, at: finished });
  await expect(run(service.verification(String(verification.id), ctx))).rejects.toThrow();
  const fulfillments = new Fulfillments(engine);
  await run(fulfillments.start(String(fulfillment.id), at, ctx)); await run(fulfillments.finish(String(fulfillment.id), 'completed', 'complete', finished, 'Restored', ctx));
  const closure = await run(cases.act({ case: String(incidentCase.id), previous: null, kind: 'close', at: finished, reason: 'Verified restoration' }, ctx)), resolution = await call(p + 'IncidentResolution.create', { incident: incident.id, correlation: correlation.id, verification: verification.id, remediation: remediation.id, closure: closure.id });
  expect((await run(service.resolution(String(resolution.id), finished, ctx))).current).toBe(true);
  await run(cases.act({ case: String(incidentCase.id), previous: String(closure.id), kind: 'reopen', at: finished, reason: 'Recurrence' }, ctx));
  expect((await run(service.resolution(String(resolution.id), finished, ctx))).current).toBe(false);
  const secondCase = await call(c + 'Case.create', { ...caseInput, key: 'second-incident' }), second = await call(p + 'Incident.create', { key: 'second', case: secondCase.id, occurredAt: at, description: 'Related service failure', source: seal.id, serviceLevel: null, risk: null, finding: null }), secondLink = await call(p + 'IncidentCorrelation.create', { incident: second.id, problem: problem.id, rationale: 'Shared cause', support: seal.id });
  expect((await run(service.correlation(String(secondLink.id), finished, ctx))).problem.row.id).toBe(problem.id);
  for (const [name, field] of [['ServiceIncident', 'service'], ['SecurityIncident', 'category'], ['QualityIncident', 'line']]) await call('@fixture/incident-problem-consumer/_/' + name + '.create', { incident: incident.id, [field!]: name });
  await call('@fixture/incident-problem-consumer/_/CustomerProblem.create', { problem: problem.id, product: 'Service' });
  await expect(run(service.known(String(known.id), { ...ctx, tenant: 'other' }))).rejects.toThrow();
 } finally { await h.close(); }
});
