import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { Assets, type AssetAction } from '../src/foundation/asset-lifecycle.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Attestations } from '../src/foundation/attestation.js';
import { ResourceRelations } from '../src/foundation/resource-relations.js';
const p = '@forgegraph/foundation/asset-lifecycle/_/', s = '@forgegraph/foundation/specification/_/', r = '@forgegraph/foundation/resource-relations/_/', e = '@forgegraph/foundation/evidence/_/', a = '@forgegraph/foundation/attestation/_/';
for (const adapter of foundationAdapters) it(`${adapter}: resource lifecycle, custody history, commissioning and retirement`, async () => {
 const h = await foundation('asset-lifecycle', adapter, true), run = Effect.runPromise;
 try {
  const { call, engine, ctx } = h, assets = new Assets(engine);
  const repository = await call(s + 'Repository.create', { key: 'assets', provider: 'git', locator: 'https://example.test/assets' });
  const pin = await call(s + 'SpecificationPin.create', { repository: repository.id, anchor: 'device', revision: 'a'.repeat(40) });
  const resource = await call(r + 'ResourceSubject.create', { key: 'device', label: 'Medical device' });
  const attestSubject = await call(a + 'AttestationSubject.create', { label: 'Device' }), issuer = await call(a + 'AttestationSubject.create', { label: 'Inspector' });
  const relations = new ResourceRelations(engine, { namespace: 'asset', kinds: ['custodian'] });
  const kind = await run(relations.registerKind('custodian', String(pin.id), ctx));
  const asset = await call(p + 'AssetProfile.create', { resource: resource.id, specification: pin.id, attestationSubject: attestSubject.id, commissioningAttestationRequired: true, custodyKind: kind.id });
  const configuration = await call(p + 'AssetConfiguration.create', { resource: resource.id, definition: pin.id, snapshot: null });
  const evidence = new Evidence(engine), source = await call(e + 'EvidenceSource.create', { key: 'record', label: 'Receipt' }), bundle = await call(e + 'EvidenceBundle.create', { key: 'evidence', label: 'Lifecycle evidence' });
  const item = await run(evidence.record({ bundle: String(bundle.id), source: String(source.id), sourceRecord: 'receipt', kind: 'receipt', observedAt: '2025-01-01T00:00:00Z', provenance: 'Domain receipt' }, ctx));
  const member = await run(evidence.member(String(bundle.id), String(item.id), null, ctx)), seal = await run(evidence.seal(String(bundle.id), String(member.id), ctx));
  const relationSource = await call(r + 'RelationSource.create', { key: 'source', source: source.id, sourceRecord: 'receipt', occurredAt: '2025-01-01T00:00:00Z', evidence: seal.id, description: 'Receipt' });
  const party = await call('@forgegraph/foundation/party/_/Party.create', { label: 'Hospital' }), other = await call('@forgegraph/foundation/party/_/Party.create', { label: 'Service depot' });
  const scope = await call(r + 'RelationScope.create', { subject: resource.id, key: 'whole', label: 'Whole' });
  const custody = await run(relations.establish({ key: 'custody', subject: String(resource.id), party: String(party.id), kind: 'custodian', scope: String(scope.id), validFrom: '2025-01-01T00:00:00Z', source: String(relationSource.id), reason: 'Received' }, ctx));
  const ids = await call('@forgegraph/foundation/identifiers/_/IdentifierSet.create', { label: 'Locations' }), place = await call('@forgegraph/foundation/place/_/Place.create', { identifiers: ids.id, name: 'Hospital' }), depot = await call('@forgegraph/foundation/place/_/Place.create', { identifiers: (await call('@forgegraph/foundation/identifiers/_/IdentifierSet.create', { label: 'Depot' })).id, name: 'Depot' });
  const at = '2026-01-02T00:00:00Z';
  const input = { asset: String(asset.id), at, place: String(place.id), custody: String(custody.current), configuration: String(configuration.id), evidence: String(seal.id), reason: 'Lifecycle' };
  const act = async (action: AssetAction, extra: Record<string, string> = {}) => run(assets.act({ ...input, action, previous: (await run(assets.state(String(asset.id), ctx))).head, ...extra }, ctx));
  await expect(act('operate')).rejects.toThrow();
  await act('acquire');
  await expect(act('commission')).rejects.toThrow();
  const attestation = await run(new Attestations(engine).issue({ issuer: String(issuer.id), subject: String(attestSubject.id), issuerRecord: '1', specification: String(pin.id), issuedAt: '2025-01-01T00:00:00Z', validFrom: '2025-01-01T00:00:00Z', conclusion: 'Ready for operation', source: 'inspection', support: String(seal.id) }, ctx));
  await act('commission', { attestation: String(attestation.id) });
  await act('operate');
  await expect(act('retire')).rejects.toThrow();
  const previous = (await run(assets.state(String(asset.id), ctx))).head;
  const races = await Promise.allSettled([1, 2].map(i => run(assets.act({ ...input, action: 'deactivate', previous, reason: 'Deactivation ' + i }, ctx))));
  expect(races.filter(r => r.status === 'fulfilled')).toHaveLength(1);
  const moved = await run(relations.handoff({ key: 'handoff', prior: String(custody.current), party: String(other.id), effectiveAt: '2026-01-03T00:00:00Z', source: String(relationSource.id), reason: 'Service depot' }, ctx));
  await act('move', { at: '2026-01-03T00:00:00Z', place: String(depot.id), custody: String(moved.current) });
  const state = await run(assets.state(String(asset.id), ctx));
  expect(state.phase).toBe('inactive'); expect(state.custody).toBe(moved.current); expect(state.place).toBe(depot.id);
  const endInput = { ...input, at: '2026-01-03T00:00:00Z', place: String(depot.id), custody: String(moved.current) };
  for (const action of ['retire', 'decommission'] as const) await run(assets.act({ ...endInput, action, previous: (await run(assets.state(String(asset.id), ctx))).head }, ctx));
  expect((await run(assets.state(String(asset.id), ctx))).phase).toBe('decommissioned');
  await expect(run(assets.act({ ...endInput, action: 'operate', previous: (await run(assets.state(String(asset.id), ctx))).head }, ctx))).rejects.toThrow();
  for (const [name, field] of [['IndustrialAsset', 'machine'], ['MedicalAsset', 'device'], ['CloudAsset', 'service'], ['FleetAsset', 'vehicle']]) await call('@fixture/asset-lifecycle-consumer/_/' + name + '.create', { asset: asset.id, [field!]: name });
  await expect(run(assets.state(String(asset.id), { ...ctx, tenant: 'other' }))).rejects.toThrow();
 } finally { await h.close(); }
});
