import type { Wire } from '../src/decode.js';
import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { Projects } from '../src/foundation/project.js';
import { Fulfillments } from '../src/foundation/fulfillment.js';
import { Usage } from '../src/foundation/usage.js';
import { Budgets } from '../src/foundation/planning-budget.js';
import { Ledger } from '../src/foundation/ledger.js';
import { Allocations } from '../src/foundation/allocation.js';
import { Scheduling } from '../src/foundation/scheduling.js';
import { Availability } from '../src/foundation/availability.js';
const p = '@forgegraph/foundation/project/_/', b = '@forgegraph/foundation/planning-budget/_/', s = '@forgegraph/foundation/specification/_/', f = '@forgegraph/foundation/fulfillment/_/', u = '@forgegraph/foundation/usage/_/', l = '@forgegraph/foundation/ledger/_/', a = '@forgegraph/foundation/allocation/_/';
for (const adapter of foundationAdapters) it(`${adapter}: project graph, actual work, dependency progress, schedule and ledger budget`, async () => {
 const h = await foundation('project', adapter, true), run = Effect.runPromise;
 try {
  const { call, engine, ctx } = h, projects = new Projects(engine), from = '2026-01-02T00:00:00Z', until = '2026-01-03T00:00:00Z';
  const repo = await call(s + 'Repository.create', { key: 'project', provider: 'git', locator: 'https://example.test/project' });
  const pin = await call(s + 'SpecificationPin.create', { repository: repo.id, anchor: 'scope', revision: 'a'.repeat(40) });
  const owner = await call('@forgegraph/foundation/party/_/Party.create', { label: 'Owner' }), participants = await call('@forgegraph/foundation/participation/_/ParticipationSet.create', { label: 'Team' });
  const plan = await call(b + 'Plan.create', { definition: pin.id, label: 'Execution plan' }), goal = await call(b + 'Goal.create', { plan: plan.id, metric: 'Delivered', unit: 'unit', target: '2' });
  const forecast = await call(b + 'ForecastScenario.create', { plan: plan.id, revision: 1, previous: null, assumptions: pin.id, label: 'Expected delivery' });
  const book = await call(l + 'LedgerBook.create', { key: 'project' }), account = await call(l + 'Account.create', { book: book.id, key: 'expense', unit: 'USD' }), cash = await call(l + 'Account.create', { book: book.id, key: 'cash', unit: 'USD' });
  const budget = await call(b + 'FundingEnvelope.create', { plan: plan.id, account: account.id, limit: '100', unit: 'USD' });
  const program = await call(p + 'Program.create', { key: 'program', sponsor: owner.id, scope: pin.id });
  const input = { program: program.id, scope: pin.id, sponsor: owner.id, owner: owner.id, participants: participants.id, plan: plan.id, goal: goal.id, budget: budget.id, forecast: forecast.id, workCount: 2, dependencyCount: 1 };
  const project = await call(p + 'Project.create', { ...input, key: 'project' });
  await expect(run(projects.progress(String(project.id), until, ctx))).rejects.toThrow();
  const set = await call(f + 'FulfillmentSet.create', { label: 'Execution' }), executor = await call(f + 'FulfillmentExecutor.create', { key: 'team' });
  const first = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 1, specificationPin: pin.id, executor: executor.id, requestedAt: from, evidence: null });
  const second = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 2, specificationPin: pin.id, executor: executor.id, requestedAt: from, evidence: null });
  const milestone = await call(b + 'Milestone.create', { plan: plan.id, goal: goal.id, dueAt: until, fulfillmentSet: set.id });
  const dimension = await call(u + 'UsageDimension.create', { key: 'hours', unit: 'hour' }), stream = await call(u + 'UsageStream.create', { dimension: dimension.id, label: 'Effort' }), source = await call(u + 'UsageSource.create', { key: 'timesheet' });
  const pool = await call(a + 'AllocationPool.create', { key: 'team', mode: 'fungible', capacity: '2', unit: 'person' });
  const reservation = await call(a + 'AllocationReservation.create', { pool: pool.id, key: 'first', quantity: '1', unit: 'person', from, until, holdUntil: from });
  await run(new Allocations(engine).act(String(reservation.id), 'book', ctx));
  const ids = await call('@forgegraph/foundation/identifiers/_/IdentifierSet.create', { label: 'Site' }), place = await call('@forgegraph/foundation/place/_/Place.create', { identifiers: ids.id, name: 'Site' });
  const availability = new Availability(engine), calendar = await run(availability.createCalendar('Team', ctx)), revision = await run(availability.createRevision({ calendar: String(calendar.id), timezone: 'UTC', weekly: [{ weekday: 5, startMinute: 0, endMinute: 1440 }] }, ctx));
  const scheduling = new Scheduling(engine), requirement = await run(scheduling.requirement({ key: 'review', durationMinutes: 60, participants: String(participants.id), place: String(place.id), needs: [{ pool: String(pool.id), calendar: String(revision.id), quantity: '1' }] }, ctx));
  const slot = await run(scheduling.slot(String(requirement.id), '2026-01-02T12:00:00Z', ctx)), appointment = await run(scheduling.book({ key: 'review', slot: String(slot.id), fulfillment: String(set.id) }, ctx));
  const workInput = { project: project.id, parent: null, depth: 1, scope: pin.id, planned: '8', unit: 'hour', from, until, milestone: milestone.id, allocation: null, appointment: null, usage: null };
  const w1 = await call(p + 'WorkPackage.create', { ...workInput, key: 'build', ordinal: 1, fulfillment: first.id, usage: stream.id, allocation: reservation.id });
  const w2 = await call(p + 'WorkPackage.create', { ...workInput, key: 'review', ordinal: 2, fulfillment: second.id, from: until, until: '2026-01-04T00:00:00Z', appointment: appointment.id });
  await call(p + 'ProjectDependency.create', { project: project.id, ordinal: 1, predecessor: w1.id, successor: w2.id, kind: 'finishToStart' });
  const initial = await run(projects.progress(String(project.id), until, ctx));
  expect(initial.completedLeafCount).toBe(0); expect(initial.dependencies[0]!.ready).toBe(false);
  const fulfillments = new Fulfillments(engine);
  await run(fulfillments.start(String(first.id), from, ctx));
  await run(fulfillments.finish(String(first.id), 'completed', 'complete', '2026-01-02T12:00:00Z', 'Delivered', ctx));
  await run(new Usage(engine).ingest({ stream: String(stream.id), dimension: String(dimension.id), unit: 'hour', quantity: '7.5', ordinal: 1, source: String(source.id), eventKey: 'hours', occurredAt: from }, ctx));
  const encumbrance = await call(b + 'Encumbrance.create', { envelope: budget.id, key: 'work', amount: '30', reservation: null });
  const budgets = new Budgets(engine), commit = await run(budgets.publish({ encumbrance: String(encumbrance.id), action: 'Commit', previous: null }, ctx));
  const posting = await run(new Ledger(engine).post({ book: String(book.id), key: 'actual', policy: 'balanced', reason: 'Cost', entries: [{ account: String(account.id), quantity: '25' }, { account: String(cash.id), quantity: '-25' }] }, ctx));
  const actual = await call(b + 'BudgetActual.create', { encumbrance: encumbrance.id, amount: '25', posting: posting.id, account: account.id, usage: null, fulfillment: first.id });
  await run(budgets.publish({ encumbrance: String(encumbrance.id), action: 'Spend', previous: String(commit.id), actual: String(actual.id) }, ctx));
  const progress = await run(projects.progress(String(project.id), until, ctx));
  expect(progress.completedLeafCount).toBe(1); expect(progress.dependencies[0]!.ready).toBe(true);
  expect(progress.work[0]!.variance).toBe('-0.500000'); expect(progress.budget!.spent).toBe('25.000000');
  expect((await run(projects.progress(String(project.id), from, ctx))).completedLeafCount).toBe(0);
  for (const [name, field] of [['SoftwareProject', 'repository'], ['CapitalProject', 'site'], ['ResearchStudy', 'protocol']]) await call('@fixture/project-consumer/_/' + name + '.create', { project: project.id, [field!]: name });
  await expect(call(p + 'ProjectDependency.create', { project: project.id, ordinal: 2, predecessor: w2.id, successor: w1.id, kind: 'finishToStart' })).rejects.toThrow();
  const cyclic = await call(p + 'Project.create', { ...input, key: 'cyclic', dependencyCount: 2 });
  const cycleWork: Wire[] = [];
  for (let i = 0; i < 2; i++) {
   const execution = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: i + 3, specificationPin: pin.id, executor: executor.id, requestedAt: from, evidence: null });
   cycleWork.push(await call(p + 'WorkPackage.create', { ...workInput, project: cyclic.id, key: 'w' + i, ordinal: i + 1, fulfillment: execution.id, parent: i ? cycleWork[0]!.id : null, depth: i + 1 }));
  }
  for (let i = 0; i < 2; i++) await call(p + 'ProjectDependency.create', { project: cyclic.id, ordinal: i + 1, predecessor: cycleWork[i]!.id, successor: cycleWork[1 - i]!.id, kind: 'finishToStart' });
  await expect(run(projects.progress(String(cyclic.id), until, ctx))).rejects.toThrow();
  await expect(run(projects.progress(String(project.id), until, { ...ctx, tenant: 'other' }))).rejects.toThrow();
 } finally { await h.close(); }
});
