import {Effect} from 'effect';
import {it,expect} from 'vitest';
import {Risks} from '../src/foundation/risk.js';
import {Evaluations} from '../src/foundation/evaluation.js';
import {Decisions} from '../src/foundation/decision.js';
import {Participations} from '../src/foundation/participation.js';
import {foundation,foundationAdapters} from './helpers/foundation.js';
const p='@forgegraph/foundation/risk/_/',e='@forgegraph/foundation/evaluation/_/',s='@forgegraph/foundation/specification/_/',v='@forgegraph/foundation/evidence/_/',d='@fixture/risk-consumer/_/';
for(const adapter of foundationAdapters)it(`${adapter}: domain scales, immutable residual history and authoritative risk acceptance`,async()=>{
 const f=await foundation('risk',adapter,true),{call,ctx,engine}=f;try{
  const risk=await call(p+'Risk.create',{scenario:'A future dependency failure delays delivery'});
  for(const [name,payload] of [['ProjectRisk',{project:'release',daysExposed:10}],['SecurityRisk',{threat:'credential compromise',asset:'build pipeline'}],['VendorRisk',{vendor:'Parts Ltd',region:'EU'}]] as const)await call(d+name+'.create',{risk:risk.id,...payload});
  const probability=await call(p+'RiskScale.create',{key:'probability-v1',label:'Domain likelihood'}),severity=await call(p+'RiskScale.create',{key:'impact-v1',label:'Domain impact'});
  const likely=await call(p+'RiskLevel.create',{scale:probability.id,code:'likely',rank:3}),rare=await call(p+'RiskLevel.create',{scale:probability.id,code:'rare',rank:1}),high=await call(p+'RiskLevel.create',{scale:severity.id,code:'high',rank:9});
  const repo=await call(s+'Repository.create',{key:'methods',provider:'git',locator:'https://example.test/methods'}),pin=await call(s+'SpecificationPin.create',{repository:repo.id,anchor:'assessment',revision:'a'.repeat(40)});
  const set=await call(e+'EvaluationSet.create',{label:'Risk monitoring'}),executor=await call(e+'EvaluationExecutor.create',{key:'assessor',label:'Assessor'}),evals=new Evaluations(engine);
  const run=await Effect.runPromise(evals.create({evaluationSet:String(set.id),definition:String(pin.id),executor:String(executor.id)},ctx));
  await Effect.runPromise(evals.start(String(run.id),'2026-01-01T00:00:00Z',ctx));
  const finish=await Effect.runPromise(evals.finish(String(run.id),'Completed','2026-01-01T01:00:00Z','assessment executed',ctx));
  const bundle=await call(v+'EvidenceBundle.create',{key:'support',label:'Evidence'}),seal=await call(v+'EvidenceSeal.create',{bundle:bundle.id,head:null,recordedBy:ctx.actor});
  const service=new Risks(engine),input={risk:String(risk.id),likelihood:String(likely.id),impact:String(high.id),confidence:'0.700',evaluation:String(finish.id),support:String(seal.id),assessedAt:'2026-01-01T02:00:00Z'};
  const original=await Effect.runPromise(service.assess(input,ctx));
  const fulfillment=await call('@forgegraph/foundation/fulfillment/_/FulfillmentSet.create',{label:'Mitigation work'});
  const treatment=await call(p+'RiskTreatment.create',{assessment:original.id,fulfillmentSet:fulfillment.id,action:'Add a second supplier'});
  const concurrent=await Promise.allSettled([0,1].map(()=>Effect.runPromise(service.assess({...input,predecessor:String(original.id),likelihood:String(rare.id),assessedAt:'2026-01-02T00:00:00Z'},ctx))));
  expect(concurrent.filter(x=>x.status==='fulfilled')).toHaveLength(1);
  const residual=concurrent.find(x=>x.status==='fulfilled')!;if(residual.status!=='fulfilled')throw new Error('missing residual');
  await call(p+'ResidualRisk.create',{treatment:treatment.id,baseline:original.id,residual:residual.value.id});
  expect((await call(p+'RiskAssessment.get',{id:original.id})).likelihood).toBe(likely.id);
  await expect(call(p+'ResidualRisk.create',{treatment:treatment.id,baseline:residual.value.id,residual:original.id})).rejects.toThrow();
  await expect(call(p+'RiskAssessment.update',{id:original.id,patch:{confidence:'1.000'}})).rejects.toThrow();
  const pp='@forgegraph/foundation/participation/_/',party=await call('@forgegraph/foundation/party/_/Party.create',{label:'Owner'}),members=new Participations(engine,{namespace:'risk',roles:['owner']});
  const group=await call(pp+'ParticipationSet.create',{label:'Risk owners'});await Effect.runPromise(members.registerRole('owner',ctx));
  const membership=await Effect.runPromise(members.add({participationSet:String(group.id),participant:String(party.id),role:'owner',validFrom:'2025-01-01T00:00:00Z',reason:'Risk owner'},ctx));
  const decisions=new Decisions(engine),decision=await Effect.runPromise(decisions.open({participationSet:String(group.id),electors:[String(membership.id)],eligibilityAt:'2026-01-01T00:00:00Z',deadline:'2027-01-01T00:00:00Z',options:['Accept','Reject'],rule:'Single',threshold:1},ctx));
  const before=await Effect.runPromise(decisions.state(String(decision.id),ctx)),option=String(before.options[0]!.id);
  await expect(Effect.runPromise(service.accept(String(original.id),String(decision.id),option,'accept',ctx))).rejects.toThrow();
  await Effect.runPromise(decisions.respond(String(decision.id),String(membership.id),[0],ctx));await Effect.runPromise(decisions.finalize(String(decision.id),ctx));
  const accepted=await Effect.runPromise(service.accept(String(original.id),String(decision.id),option,'Domain accepts assessed residual exposure',ctx));
  expect(await Effect.runPromise(service.acceptance(String(accepted.id),option,ctx))).toMatchObject({assessment:original.id});
  await expect(Effect.runPromise(service.acceptance(String(accepted.id),String(before.options[1]!.id),ctx))).rejects.toThrow();
  await call(e+'EvaluationQuarantine.create',{run:run.id,sourceDigest:'a'.repeat(64),reason:'Legacy chronology',recordedBy:ctx.actor});
  const quarantined={code:'ValidationFailed',detail:'Evaluation is quarantined; execute a new run with fresh bindings'};
  await expect(Effect.runPromise(service.accept(String(original.id),String(decision.id),option,'New acceptance',ctx))).rejects.toMatchObject(quarantined);
  await expect(Effect.runPromise(service.acceptance(String(accepted.id),option,ctx))).rejects.toMatchObject(quarantined);
  expect((await call(p+'RiskAcceptance.get',{id:accepted.id})).assessment).toBe(original.id);
  expect(await Effect.runPromise(evals.phase(String(run.id),ctx))).toBe('Completed');
  await expect(call(p+'Risk.get',{id:risk.id},{...ctx,tenant:'other'})).rejects.toThrow();
 }finally{await f.close();}
});
