import {Effect} from 'effect';
import {expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {foundation,foundationAdapters} from './helpers/foundation.js';
import {Reconciliations} from '../src/foundation/reconciliation.js';
import {Evaluations} from '../src/foundation/evaluation.js';
import {Evidence} from '../src/foundation/evidence.js';
import {ActorHost,type ActorReducer} from '../src/actors.js';
import {Model,type AppBundle} from '../src/model.js';
import {Storage} from '../src/services.js';
import {err} from '../src/errors.js';
import {localAuthorizer} from '../src/gatekeeper.js';
const p='@forgegraph/foundation/reconciliation/_/',s='@forgegraph/foundation/specification/_/',e='@forgegraph/foundation/evidence/_/',v='@forgegraph/foundation/evaluation/_/',fuf='@forgegraph/foundation/fulfillment/_/',d='@fixture/reconciliation-consumer/_/';
const at='2026-01-01T00:00:00Z';
for(const adapter of foundationAdapters)it(`${adapter}: desired journal fences attempts/results and real keyed actor resumes effects without rewriting newer intent`,async()=>{
 const f=await foundation('reconciliation',adapter,true);const {call,ctx,engine}=f;
 try{
  const service=new Reconciliations(engine),evaluations=new Evaluations(engine);
  const scope=await call(p+'ReconciliationScope.create',{key:'deployment'});
  for(const [name,field]of [['Deployment','environment'],['DeviceConfiguration','deviceSerial'],['RepositoryPolicy','repositoryName']])await call(d+name+'.create',{reconciliation:scope.id,[field!]:'typed-target'});
  const repo=await call(s+'Repository.create',{key:'spec',provider:'git',locator:'https://example.test/spec'});
  const pin=await call(s+'SpecificationPin.create',{repository:repo.id,anchor:'deployment',revision:'a'.repeat(40)});
  const pin2=await call(s+'SpecificationPin.create',{repository:repo.id,anchor:'deployment',revision:'b'.repeat(40)});
  const desired=await call(p+'DesiredRevision.create',{scope:scope.id,sequence:1,pin:pin.id});
  const newer=await call(p+'DesiredRevision.create',{scope:scope.id,sequence:2,pin:pin2.id});
  const first=await Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Desired',null,{...ctx,idempotencyKey:'desired-1'}));
  expect(await Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Desired',null,{...ctx,idempotencyKey:'desired-1'}))).toEqual(first);
  const bundle=await call(e+'EvidenceBundle.create',{key:'observation',label:'Observation'}),seal=await Effect.runPromise(new Evidence(engine).seal(String(bundle.id),null,ctx));
  const set=await call(v+'EvaluationSet.create',{label:'Observed target'}),executor=await call(v+'EvaluationExecutor.create',{key:'controller',label:'Controller'});
  const run=await Effect.runPromise(evaluations.create({evaluationSet:String(set.id),definition:String(pin.id),executor:String(executor.id)},ctx));
  await Effect.runPromise(evaluations.start(String(run.id),at,ctx));
  const finish=await Effect.runPromise(evaluations.finish(String(run.id),'Completed',at,'Observed',ctx,String(seal.id)));
  const observation=await call(p+'Observation.create',{desired:desired.id,run:run.id,finish:finish.id,support:seal.id,observedAt:at});
  await call(d+'ObservedDeployment.create',{observation:observation.id,replicas:1});
  const drift=await call(p+'Drift.create',{observation:observation.id,desired:desired.id,pin:pin.id,anchor:'deployment',field:'replicas',explanation:'Expected three observed one'});
  await call(d+'ReplicaDrift.create',{drift:drift.id,actual:1,desired:3});
  await expect(call(p+'Drift.create',{observation:observation.id,desired:desired.id,pin:pin.id,anchor:'wrong-anchor',field:'replicas',explanation:'Wrong'})).rejects.toThrow();
  const fulfillmentSet=await call(fuf+'FulfillmentSet.create',{label:'Corrective work'}),worker=await call(fuf+'FulfillmentExecutor.create',{key:'controller'});
  const fulfillment=await call(fuf+'Fulfillment.create',{fulfillmentSet:fulfillmentSet.id,ordinal:1,specificationPin:pin.id,executor:worker.id,requestedAt:at});
  const attempt=await call(p+'ReconciliationAttempt.create',{desired:desired.id,observation:observation.id,fulfillment:fulfillment.id,key:'attempt-1'});
  const active=await Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Attempt',String(first.id),ctx,String(attempt.id)));
  await Effect.runPromise(service.assertCurrent(String(scope.id),String(desired.id),String(active.id),ctx));
  // New desired intent occupies the same serialization journal as results.
  const advanced=await Effect.runPromise(service.publish(String(scope.id),String(newer.id),'Desired',String(active.id),ctx));
  const result=await Effect.runPromise(service.recordResult(String(attempt.id),'Converged',String(seal.id),'Late old observation',ctx));
  await expect(Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Result',String(active.id),ctx,String(attempt.id),String(result.id)))).rejects.toThrow();
  await expect(Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Result',String(advanced.id),ctx,String(attempt.id),String(result.id)))).rejects.toThrow();
  await expect(Effect.runPromise(service.assertCurrent(String(scope.id),String(desired.id),String(active.id),ctx))).rejects.toMatchObject({code:'VersionConflict'});
  expect((await Effect.runPromise(new Reconciliations(engine).state(String(scope.id),ctx))).latest).toMatchObject({desired:newer.id});
  expect((await call(p+'ReconciliationResult.get',{id:result.id})).detail).toBe('Late old observation');
  await expect(Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Desired',String(advanced.id),ctx))).rejects.toThrow();
  const run2=await Effect.runPromise(evaluations.create({evaluationSet:String(set.id),definition:String(pin2.id),executor:String(executor.id)},ctx));
  await Effect.runPromise(evaluations.start(String(run2.id),at,ctx));
  const finish2=await Effect.runPromise(evaluations.finish(String(run2.id),'Completed',at,'Reobserved',ctx,String(seal.id)));
  const observation2=await call(p+'Observation.create',{desired:newer.id,run:run2.id,finish:finish2.id,support:seal.id,observedAt:at});
  const fulfillment2=await call(fuf+'Fulfillment.create',{fulfillmentSet:fulfillmentSet.id,ordinal:2,specificationPin:pin2.id,executor:worker.id,requestedAt:at});
  const attempt2=await call(p+'ReconciliationAttempt.create',{desired:newer.id,observation:observation2.id,fulfillment:fulfillment2.id,key:'attempt-2'});
  const contenders=await Promise.allSettled([service.publish(String(scope.id),String(newer.id),'Attempt',String(advanced.id),ctx,String(attempt2.id)),service.publish(String(scope.id),String(newer.id),'Attempt',String(advanced.id),ctx,String(attempt2.id))].map(effect=>Effect.runPromise(effect)));
  expect(contenders.filter(outcome=>outcome.status==='fulfilled')).toHaveLength(1);
  expect(contenders.filter(outcome=>outcome.status==='rejected')).toHaveLength(1);
  const selected=(await Effect.runPromise(service.state(String(scope.id),ctx))).latest!;
  const result2=await Effect.runPromise(service.recordResult(String(attempt2.id),'Converged',String(seal.id),'Observed current desired revision',{...ctx,idempotencyKey:'result-2'}));
  expect(await Effect.runPromise(new Reconciliations(engine).recordResult(String(attempt2.id),'Converged',String(seal.id),'Observed current desired revision',{...ctx,idempotencyKey:'result-2'}))).toEqual(result2);
  const completed=await Effect.runPromise(service.publish(String(scope.id),String(newer.id),'Result',String(selected.id),{...ctx,idempotencyKey:'publish-result-2'},String(attempt2.id),String(result2.id)));
  expect(await Effect.runPromise(new Reconciliations(engine).publish(String(scope.id),String(newer.id),'Result',String(selected.id),{...ctx,idempotencyKey:'publish-result-2'},String(attempt2.id),String(result2.id)))).toEqual(completed);
  expect((await Effect.runPromise(service.state(String(scope.id),ctx))).events).toHaveLength(5);
  const path=process.env['FORGE_RECONCILIATION_CONTROLLER']??resolve(import.meta.dirname,'../../../conformance/fixtures/reconciliation-controller');
  const actorModel=new Model(JSON.parse(readFileSync(resolve(path,'app.json'),'utf8')) as AppBundle);
  const definition=actorModel.bundle.ir.modules.flatMap(m=>m.actors??[])[0]!;
  const storage=await Effect.runPromise(Effect.service(Storage).pipe(Effect.provide(engine.layer)));
  const reducer:ActorReducer=(state,message)=>{if(Number(message.sequence)<=Number(state.desiredSequence))throw err('VersionConflict','Stale controller desired sequence');return {state:{desiredSequence:message.sequence},effects:[{kind:'reconcile-desired',payload:{scope:message.scope,desired:message.desired}}]};};
  const host=new ActorHost(actorModel,storage,definition,{Desired:reducer});
  await Effect.runPromise(host.initialize(ctx.tenant,String(scope.id),{desiredSequence:0}));
  await Effect.runPromise(host.command(ctx.tenant,String(scope.id),'desired-message','Desired',{sequence:2,scope:scope.id,desired:newer.id},1));
  expect(await Effect.runPromise(host.command(ctx.tenant,String(scope.id),'desired-message','Desired',{sequence:2,scope:scope.id,desired:newer.id},1))).toMatchObject({duplicate:true});
  const recovered=new ActorHost(actorModel,storage,definition,{Desired:reducer});
  const pending=await Effect.runPromise(recovered.load(ctx.tenant,String(scope.id)));expect(pending.effects).toHaveLength(1);
  // Recovered effect validates durable typed revision/fence before acknowledging.
  await Effect.runPromise(service.assertCurrent(String(scope.id),String(pending.effects[0]!.payload.desired),String(completed.id),ctx));
  await Effect.runPromise(recovered.acknowledgeEffect(ctx.tenant,String(scope.id),pending.effects[0]!.id,1));
  expect((await Effect.runPromise(recovered.load(ctx.tenant,String(scope.id)))).effects).toEqual([]);
  const generation=await Effect.runPromise(recovered.takeover(ctx.tenant,String(scope.id),1));
  await expect(Effect.runPromise(host.command(ctx.tenant,String(scope.id),'stale','Desired',{sequence:1,scope:scope.id,desired:desired.id},1))).rejects.toThrow();
  await expect(Effect.runPromise(recovered.command(ctx.tenant,String(scope.id),'old-sequence','Desired',{sequence:1,scope:scope.id,desired:desired.id},generation))).rejects.toThrow();
  await expect(Effect.runPromise(service.state(String(scope.id),{...ctx,tenant:'foreign'}))).rejects.toThrow();
  await expect(Effect.runPromise(engine.call(p+'DesiredRevision.create',{scope:scope.id,sequence:3,pin:pin.id},{...ctx,tenant:'foreign'}))).rejects.toThrow();
  const quarantined={code:'ValidationFailed',detail:'Evaluation is quarantined; execute a new run with fresh bindings'};
  await call(v+'EvaluationQuarantine.create',{run:run.id,sourceDigest:'a'.repeat(64),reason:'Legacy observation',recordedBy:ctx.actor});
  expect((await Effect.runPromise(service.state(String(scope.id),ctx))).latest!.id).toBe(completed.id); // obsolete history is inspectable
  await expect(Effect.runPromise(service.recordResult(String(attempt.id),'Converged',String(seal.id),'Reused legacy observation',ctx))).rejects.toMatchObject(quarantined);
  await expect(Effect.runPromise(service.publish(String(scope.id),String(desired.id),'Attempt',String(completed.id),ctx,String(attempt.id)))).rejects.toMatchObject(quarantined);
  await call(v+'EvaluationQuarantine.create',{run:run2.id,sourceDigest:'b'.repeat(64),reason:'Current legacy observation',recordedBy:ctx.actor});
  await expect(Effect.runPromise(service.state(String(scope.id),ctx))).rejects.toMatchObject(quarantined);
  await expect(Effect.runPromise(service.assertCurrent(String(scope.id),String(newer.id),String(completed.id),ctx))).rejects.toMatchObject(quarantined);
  await expect(Effect.runPromise(service.publish(String(scope.id),String(newer.id),'Result',String(selected.id),ctx,String(attempt2.id),String(result2.id)))).rejects.toMatchObject(quarantined);
  expect((await call(p+'ReconciliationResult.get',{id:result2.id})).outcome).toBe('Converged');
  const newest=await call(p+'DesiredRevision.create',{scope:scope.id,sequence:3,pin:pin2.id});
  await Effect.runPromise(service.publish(String(scope.id),String(newest.id),'Desired',String(completed.id),ctx));
  expect((await Effect.runPromise(service.state(String(scope.id),ctx))).latest!.desired).toBe(newest.id);
  engine.gatekeeper.authorizer=localAuthorizer({policies:[{id:'scope',actions:[p+'ReconciliationScope.*'],requires:[],where:[]}],pips:[],epoch:1,knownObligations:[]});
  await expect(Effect.runPromise(service.state(String(scope.id),ctx))).rejects.toThrow();
  await expect(Effect.runPromise(service.publish(String(scope.id),String(newer.id),'Desired',null,ctx))).rejects.toThrow();
 }finally{await f.close();}
});
