import { Effect } from "effect";
import { expect,it } from "vitest";
import { mkdtemp,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { foundation,foundationAdapters } from "./helpers/foundation.js";
import { withFoundationProduction } from "../../../examples/foundation/apps/levelforge/adapter.js";
import { Engine } from "../src/engine.js";
import { localAuthorizer } from "../src/gatekeeper.js";
import { Evaluations } from "../src/foundation/evaluation.js";
const root=process.env.FORGE_FOUNDATION_LEVELFORGE_ROOT;
if(!root)throw new Error("FORGE_FOUNDATION_LEVELFORGE_ROOT must name the pinned real LevelForge checkout");
const runtime=await import(resolve(root,"packages/recipe/src/artifact-job-runtime.ts"));
const graphSource=await import(resolve(root,"packages/recipe/src/artifact-graph.ts"));
const registrySource=await import(resolve(root,"packages/recipe/src/artifact-executor-registry.ts"));
const fileStore=await import(resolve(root,"packages/recipe/src/artifact-job-store.ts"));
process.env.FORGE_FOUNDATION_FIXTURE=process.env.FORGE_FOUNDATION_LEVELFORGE_BUNDLE??resolve(import.meta.dirname,"../../../examples/foundation/apps/levelforge/generated");
for(const provider of foundationAdapters)it(`${provider}: real LevelForge recipe job persists typed Foundation execution`,async()=>{
 const f=await foundation("levelforge",provider),directory=await mkdtemp(resolve(tmpdir(),"foundation-levelforge-"));
 try{
  const sp="@forgegraph/foundation/specification/_/",ep="@forgegraph/foundation/evaluation/_/",p="@foundation-app/levelforge/_/";
  const repository=await f.call(sp+"Repository.create",{key:"game",provider:"git",locator:"https://example.test/game"});
  const definition=await f.call(sp+"SpecificationPin.create",{repository:repository.id,anchor:"Artifacts/forest-guide",revision:"a".repeat(40)});
  const set=await f.call(ep+"EvaluationSet.create",{label:"Artifact production"}),executor=await f.call(ep+"EvaluationExecutor.create",{key:"recipe",label:"LevelForge recipe runtime"});
  const raw=fileStore.createFileArtifactJobStore({projectDir:directory});
  const store=withFoundationProduction(raw,f.engine,{projectId:"game-project",definition:String(definition.id),evaluationSet:String(set.id),executor:String(executor.id)},f.ctx);
  const graph=graphSource.compileArtifactProductionGraph([{schema:"levelforge.artifact-plan.v1",artifactId:"forest-guide",revision:1,tasks:[{id:"package",kind:"manifest",executor:"manifest.packager",dependsOn:[],consumes:[],produces:["manifest"],parameters:{}}]}]);
  const registry=new registrySource.ArtifactExecutorRegistry();let calls=0;
  registry.register({descriptor:{id:"manifest.packager",version:"1.0.0",displayName:"Manifest packager"},handler:{execute:async()=>{calls++;return{outputs:{manifest:{asset:"forest-guide"}}};}}});
  let time=Date.parse("2026-01-02T00:00:00Z");const now=()=>new Date(time+=1000).toISOString();
  const created=await runtime.createArtifactProductionJob(graph,registry,store,{jobId:"forest-guide-production",provenance:{createdBy:"artist",sourceRevision:"a".repeat(40)},now});
  const before=await f.call(p+"ProductionAttempt.find.byProjectIdJobIdAttempt",{params:{projectId:"game-project",jobId:created.jobId,attempt:1}});
  expect(await Effect.runPromise(new Evaluations(f.engine).phase(String(before.run),f.ctx))).toBe("Planned");
  const finished=await runtime.runArtifactProductionJob(created.jobId,registry,store,{now});
  expect(finished.status).toBe("completed");expect(calls).toBe(1);
  expect(await Effect.runPromise(new Evaluations(f.engine).phase(String(before.run),f.ctx))).toBe("Completed");
  await runtime.runArtifactProductionJob(created.jobId,registry,store,{now});expect(calls).toBe(1);
  const rebound=withFoundationProduction(raw,f.engine,{projectId:"game-project",definition:String(definition.id),evaluationSet:String(set.id),executor:String(executor.id)},f.ctx);
  expect((await rebound.load(created.jobId))?.status).toBe("completed");
  await expect(store.save({...finished,provenance:{...finished.provenance,sourceRevision:"b".repeat(40)}},finished.revision)).rejects.toThrow("source revision");
  expect((await raw.load(created.jobId)).provenance.sourceRevision).toBe("a".repeat(40));
  const flaky=new registrySource.ArtifactExecutorRegistry();let attempts=0;
  flaky.register({descriptor:{id:"manifest.packager",version:"1.0.0",displayName:"Manifest packager"},handler:{execute:async()=>{if(++attempts===1)throw new Error("Transient executor failure");return{outputs:{manifest:{asset:"forest-guide"}}};}}});
  const retry=await runtime.createArtifactProductionJob(graph,flaky,store,{jobId:"retry-production",provenance:{createdBy:"artist",sourceRevision:"a".repeat(40)},now});
  expect((await runtime.runArtifactProductionJob(retry.jobId,flaky,store,{now,maximumAttempts:1})).status).toBe("failed");
  const firstAttempt=await f.call(p+"ProductionAttempt.find.byProjectIdJobIdAttempt",{params:{projectId:"game-project",jobId:retry.jobId,attempt:1}});
  expect(await Effect.runPromise(new Evaluations(f.engine).phase(String(firstAttempt.run),f.ctx))).toBe("Failed");
  expect((await runtime.runArtifactProductionJob(retry.jobId,flaky,store,{now,resume:true,maximumAttempts:2})).status).toBe("completed");
  const secondAttempt=await f.call(p+"ProductionAttempt.find.byProjectIdJobIdAttempt",{params:{projectId:"game-project",jobId:retry.jobId,attempt:2}});
  expect((await f.call(ep+"EvaluationRun.get",{id:secondAttempt.run})).parent).toBe(firstAttempt.run);
  const guarded=new Engine(f.engine.model,f.engine.layer);
  guarded.gatekeeper.authorizer=localAuthorizer({policies:f.engine.model.resources.map(r=>({id:r.id,actions:[r.id+(r.id===ep+"EvaluationFinish"?".get":".*")],requires:[],where:[]})),pips:[],epoch:1,knownObligations:[]});
  const interrupted=withFoundationProduction(raw,guarded,{projectId:"game-project",definition:String(definition.id),evaluationSet:String(set.id),executor:String(executor.id)},f.ctx);
  const pending=await runtime.createArtifactProductionJob(graph,registry,interrupted,{jobId:"interrupted-mirror",provenance:{createdBy:"artist",sourceRevision:"a".repeat(40)},now});
  await expect(runtime.runArtifactProductionJob(pending.jobId,registry,interrupted,{now})).rejects.toThrow();
  const countBeforeRecovery=calls;
  expect((await store.load(pending.jobId))?.status).toBe("completed");expect(calls).toBe(countBeforeRecovery);
  const recovered=await f.call(p+"ProductionAttempt.find.byProjectIdJobIdAttempt",{params:{projectId:"game-project",jobId:pending.jobId,attempt:1}});
  expect(await Effect.runPromise(new Evaluations(f.engine).phase(String(recovered.run),f.ctx))).toBe("Completed");
  await expect(store.create({...finished,jobId:"posthoc"})).rejects.toThrow("before execution");
  const foreign=withFoundationProduction(raw,f.engine,{projectId:"game-project",definition:String(definition.id),evaluationSet:String(set.id),executor:String(executor.id)},{...f.ctx,tenant:"foreign"});
  await expect(foreign.load(created.jobId)).rejects.toThrow();
 }finally{await f.close();await rm(directory,{recursive:true,force:true});}
});
