import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { agreement } from './helpers/agreement.js';
import { Returns } from '../src/foundation/returns.js';
import { Inventory } from '../src/foundation/inventory.js';
import { Entitlements } from '../src/foundation/entitlement.js';
import { Fulfillments } from '../src/foundation/fulfillment.js';
import { Evaluations } from '../src/foundation/evaluation.js';
import { Evidence } from '../src/foundation/evidence.js';
import { Billing } from '../src/foundation/billing.js';
const p = '@forgegraph/foundation/returns/_/', inv = '@forgegraph/foundation/inventory/_/', f = '@forgegraph/foundation/fulfillment/_/', e = '@forgegraph/foundation/evaluation/_/';
for (const adapter of foundationAdapters) it(`${adapter}: partial returns, reverse custody, inspected restock and independent credit`, async () => {
 const h = await foundation('returns', adapter, true), run = Effect.runPromise;
 try {
  const { call, engine, ctx } = h, contract = await agreement(h), service = new Returns(engine), inventory = new Inventory(engine), fulfillments = new Fulfillments(engine);
  const at = '2026-02-02T00:00:00Z', returnedAt = '2026-02-03T00:00:00Z', inspectedAt = '2026-02-03T01:00:00Z';
  const set = await call(f + 'FulfillmentSet.create', { label: 'Original delivery' }), executor = await call(f + 'FulfillmentExecutor.create', { key: 'delivery' });
  const original = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 1, specificationPin: contract.pin.id, executor: executor.id, requestedAt: '2026-02-01T00:00:00Z', evidence: null });
  await run(fulfillments.start(String(original.id), '2026-02-01T00:00:00Z', ctx)); await run(fulfillments.finish(String(original.id), 'completed', 'complete', at, 'Delivered', ctx));
  const ids = await call('@forgegraph/foundation/identifiers/_/IdentifierSet.create', { label: 'Stock' }), place = await call('@forgegraph/foundation/place/_/Place.create', { identifiers: ids.id, name: 'Warehouse' });
  const spec = await call(inv + 'StockItemSpecification.create', { key: 'product', definition: contract.pin.id, unit: 'each' }), item = await call(inv + 'StockItem.create', { key: 'lot', specification: spec.id, identifiers: ids.id, kind: 'lot', serial: null, lot: '1' });
  const positions = [];
  for (const condition of ['usable', 'returned']) {
   const pool = await call('@forgegraph/foundation/allocation/_/AllocationPool.create', { key: condition, mode: 'fungible', capacity: '10', unit: 'each' });
   positions.push(await call(inv + 'InventoryPosition.create', { item: item.id, place: place.id, custodian: contract.supplier.id, condition, pool: pool.id, reorderPoint: '0' }));
  }
  const move = { item: String(item.id), at, position: String(positions[0]!.id), quantity: '4', source: String(contract.pin.id) };
  const receipt = await run(inventory.move({ ...move, key: 'receipt', previous: null, kind: 'receipt' }, ctx)), issue = await run(inventory.move({ ...move, key: 'issue', previous: String(receipt.id), kind: 'issue' }, ctx));
  const entitlement = await run(new Entitlements(engine).issue({ holder: String(contract.customer.id), right: String(contract.right.id), scope: String(contract.scope.id), quantity: '4', unit: 'each', validFrom: at, validUntil: '2026-03-01T00:00:00Z', reason: 'Return policy' }, ctx));
  const origin = await call(p + 'ReturnOrigin.create', { issue: issue.id, customer: contract.customer.id, supplier: contract.supplier.id, agreement: contract.contract.id, fulfillment: original.id, entitlement: entitlement.id, right: contract.right.id, scope: contract.scope.id });
  const evalSet = await call(e + 'EvaluationSet.create', { label: 'Returns' }), inspector = await call(e + 'EvaluationExecutor.create', { key: 'inspector', label: 'Inspector' }), evaluations = new Evaluations(engine), inspection = await run(evaluations.create({ evaluationSet: String(evalSet.id), definition: String(contract.pin.id), executor: String(inspector.id) }, ctx));
  const base = { origin: origin.id, entitlement: entitlement.id, quantity: '2', reason: 'Partial return', requestedAt: at, authorization: contract.approval.id, authorizedOption: contract.accepted.id, inspection: inspection.id, dispositionDecision: contract.approval.id, dispositionOption: contract.accepted.id, disposition: 'restock', remedy: 'credit', amount: '5', unit: 'USD' };
  const first = await call(p + 'ReturnRequest.create', { ...base, key: 'first' }), second = await call(p + 'ReturnRequest.create', { ...base, key: 'second', remedy: 'replacement', amount: '0', disposition: 'replace' }), excess = await call(p + 'ReturnRequest.create', { ...base, key: 'excess', quantity: '3' });
  const authorized = await run(service.authorize(String(first.id), null, at, ctx));
  await expect(run(service.authorize(String(excess.id), String(authorized.id), at, ctx))).rejects.toThrow();
  const authorizedSecond = await run(service.authorize(String(second.id), String(authorized.id), at, ctx));
  expect((await run(service.claims(String(origin.id), ctx))).quantity).toBe('4.000000');
  const returned = await run(inventory.move({ ...move, key: 'returned', previous: String(issue.id), at: returnedAt, position: String(positions[1]!.id), quantity: '2', kind: 'returned' }, ctx));
  const received = await call(p + 'ReturnReceipt.create', { authorization: authorized.id, movement: returned.id });
  await expect(call(p + 'ReturnReceipt.create', { authorization: authorizedSecond.id, movement: returned.id })).rejects.toThrow();
  expect((await run(service.receipt(String(received.id), ctx))).request.quantity).toBe('2.000000');
  await run(evaluations.start(String(inspection.id), returnedAt, ctx));
  const finish = await run(evaluations.finish(String(inspection.id), 'Completed', inspectedAt, 'Inspected', ctx));
  const restocked = await run(inventory.move({ ...move, key: 'restock', previous: String(returned.id), at: inspectedAt, position: String(positions[1]!.id), destination: String(positions[0]!.id), quantity: '2', kind: 'transfer' }, ctx));
  const bundle = await call('@forgegraph/foundation/evidence/_/EvidenceBundle.create', { key: 'inspection', label: 'Inspection evidence' }), seal = await run(new Evidence(engine).seal(String(bundle.id), null, ctx));
  const disposition = await call(p + 'ReturnDisposition.create', { receipt: received.id, inspection: finish.id, support: seal.id, movement: restocked.id, work: null, at: inspectedAt });
  expect((await run(service.disposition(String(disposition.id), ctx))).request.disposition).toBe('restock');
  const billing = new Billing(engine), b = '@forgegraph/foundation/billing/_/', l = '@forgegraph/foundation/ledger/_/', price = '@forgegraph/foundation/quotation-pricing/_/';
  const period = await call(b + 'BillingPeriod.create', { agreement: contract.contract.id, terms: contract.pin.id, from: '2026-02-01T00:00:00Z', until: '2026-03-01T00:00:00Z' }), book = await call(l + 'LedgerBook.create', { key: 'billing' }), account = await call(l + 'Account.create', { book: book.id, key: 'receivable', unit: 'USD' }), rate = await call(price + 'PricingRate.create', { key: 'price', definition: contract.pin.id, account: account.id, unitPrice: '10', validFrom: '2026-02-01T00:00:00Z', validUntil: '2026-03-01T00:00:00Z' });
  const charge = await run(billing.rate({ period: String(period.id), sourceKey: 'original', kind: 'oneOff', rate: String(rate.id), quantity: '1', ratedAt: at, source: 'original order' }, ctx)), originalBill = await run(billing.draft({ key: 'invoice', period: String(period.id), charges: [String(charge.id)], reason: 'Original' }, ctx)); await run(billing.issue(String(originalBill.id), ctx));
  const adjustment = await call(price + 'PriceAdjustment.create', { key: 'return-credit', definition: contract.pin.id, account: account.id, amount: '-5', reason: 'Returned goods' }), credit = await run(billing.rate({ period: String(period.id), sourceKey: 'credit', kind: 'adjustment', adjustment: String(adjustment.id), adjustmentFor: String(charge.id), ratedAt: inspectedAt, source: 'return' }, ctx)), creditBill = await run(billing.draft({ key: 'credit-note', period: String(period.id), charges: [String(credit.id)], corrects: String(originalBill.id), reason: 'Return credit' }, ctx));
  const remedy = await call(p + 'ReturnRemedy.create', { disposition: disposition.id, replacement: null, refund: null, creditBill: creditBill.id, credit: credit.id, at: inspectedAt });
  await expect(run(service.remedy(String(remedy.id), ctx))).rejects.toThrow();
  await run(billing.issue(String(creditBill.id), ctx));
  expect((await run(service.remedy(String(remedy.id), ctx))).row.credit).toBe(credit.id);
  const secondReturn = await run(inventory.move({ ...move, key: 'second-return', previous: String(restocked.id), at: inspectedAt, position: String(positions[1]!.id), quantity: '2', kind: 'returned' }, ctx));
  const secondReceipt = await call(p + 'ReturnReceipt.create', { authorization: authorizedSecond.id, movement: secondReturn.id });
  const secondDisposition = await call(p + 'ReturnDisposition.create', { receipt: secondReceipt.id, inspection: finish.id, support: seal.id, movement: null, work: null, at: inspectedAt });
  const replacement = await call(f + 'Fulfillment.create', { fulfillmentSet: set.id, ordinal: 2, specificationPin: contract.pin.id, executor: executor.id, requestedAt: inspectedAt, evidence: null });
  const replacementRemedy = await call(p + 'ReturnRemedy.create', { disposition: secondDisposition.id, replacement: replacement.id, refund: null, creditBill: null, credit: null, at: inspectedAt });
  await expect(run(service.remedy(String(replacementRemedy.id), ctx))).rejects.toThrow();
  await run(fulfillments.start(String(replacement.id), inspectedAt, ctx));
  await run(fulfillments.finish(String(replacement.id), 'completed', 'complete', inspectedAt, 'Replacement delivered', ctx));
  expect((await run(service.remedy(String(replacementRemedy.id), ctx))).row.replacement).toBe(replacement.id);
  for (const [name, field] of [['CommerceReturn', 'orderNumber'], ['WarrantyReturn', 'warranty'], ['MaterialReturn', 'lot'], ['LoanReturn', 'loan']]) await call('@fixture/returns-consumer/_/' + name + '.create', { request: first.id, [field!]: name });
  await expect(run(service.claims(String(origin.id), { ...ctx, tenant: 'other' }))).rejects.toThrow();
 } finally { await h.close(); }
});
