import { Effect } from 'effect';
import { expect, it } from 'vitest';
import { foundation, foundationAdapters } from './helpers/foundation.js';
import { Budgets } from '../src/foundation/planning-budget.js';
import { Ledger } from '../src/foundation/ledger.js';
import { Usage } from '../src/foundation/usage.js';
import { Allocations } from '../src/foundation/allocation.js';
const p = '@forgegraph/foundation/planning-budget/_/', l = '@forgegraph/foundation/ledger/_/', a = '@forgegraph/foundation/allocation/_/', s = '@forgegraph/foundation/specification/_/', u = '@forgegraph/foundation/usage/_/';
const run = Effect.runPromise;
for (const adapter of foundationAdapters) it(`${adapter}: forecasts stay distinct from atomic encumbrances, exact actuals and reversals`, async () => {
  const f = await foundation('planning-budget', adapter, true), { call, ctx, engine } = f;
  try {
    const repository = await call(s + 'Repository.create', { key: 'planning', provider: 'git', locator: 'https://example.test/planning' });
    const pin = await call(s + 'SpecificationPin.create', { repository: repository.id, anchor: 'plan', revision: 'a'.repeat(40) });
    const plan = await call(p + 'Plan.create', { definition: pin.id, label: 'Plan' });
    const goal = await call(p + 'Goal.create', { plan: plan.id, metric: 'Units delivered', unit: 'unit', target: '10' });
    const work = await call('@forgegraph/foundation/fulfillment/_/FulfillmentSet.create', { label: 'Milestone work' });
    await call(p + 'Milestone.create', { plan: plan.id, goal: goal.id, dueAt: '2026-02-01T00:00:00Z', fulfillmentSet: work.id });
    const forecast = await call(p + 'ForecastScenario.create', { plan: plan.id, revision: 1, assumptions: pin.id, label: 'Baseline' });
    await call(p + 'ForecastValue.create', { scenario: forecast.id, goal: goal.id, quantity: '12' });
    const updated = await call(p + 'ForecastScenario.create', { plan: plan.id, revision: 2, previous: forecast.id, assumptions: pin.id, label: 'Optimistic' });
    await call(p + 'ForecastValue.create', { scenario: updated.id, goal: goal.id, quantity: '15' });
    for (const name of ['ProjectPlan', 'ProcurementBudget', 'CapacityPlan']) await call('@fixture/planning-consumer/_/' + name + '.create', { plan: plan.id, label: name });
    const book = await call(l + 'LedgerBook.create', { key: 'finance' });
    const account = await call(l + 'Account.create', { book: book.id, key: 'expense', unit: 'USD' });
    const cash = await call(l + 'Account.create', { book: book.id, key: 'cash', unit: 'USD' });
    const envelope = await call(p + 'FundingEnvelope.create', { plan: plan.id, account: account.id, limit: '100', unit: 'USD' });
    const pool = await call(a + 'AllocationPool.create', { key: 'funded-capacity', mode: 'fungible', capacity: '2', unit: 'slot' });
    const reservations = [];
    for (const key of ['first', 'second']) reservations.push(await call(a + 'AllocationReservation.create', { pool: pool.id, key, quantity: '1', unit: 'slot', from: '2026-01-02T00:00:00Z', until: '2026-02-01T00:00:00Z', holdUntil: '2026-01-02T00:00:00Z' }));
    const candidates = [];
    for (let i = 0; i < 2; i++) candidates.push(await call(p + 'Encumbrance.create', { envelope: envelope.id, key: String(i), amount: '70', reservation: reservations[i]!.id }));
    const api = new Budgets(engine);
    const race = await Promise.allSettled(candidates.map(row => run(api.publish({ encumbrance: String(row.id), action: 'Commit', previous: null }, ctx))));
    expect(race.filter(r => r.status === 'fulfilled')).toHaveLength(1);
    let state = await run(api.state(String(envelope.id), ctx));
    expect(state.available).toBe('30.000000'); expect(state.spent).toBe('0.000000');
    const winning = [...state.claims.values()][0]!.row;
    const loser = candidates.find(c => c.id !== winning.id)!;
    await expect(run(api.publish({ encumbrance: String(loser.id), action: 'Commit', previous: String(state.events.at(-1)!.id) }, ctx))).rejects.toThrow();
    const ledger = new Ledger(engine);
    const posting = await run(ledger.post({ book: String(book.id), key: 'actual', policy: 'balanced', reason: 'Actual cost', entries: [{ account: String(account.id), quantity: '60' }, { account: String(cash.id), quantity: '-60' }] }, ctx));
    const dimension = await call(u + 'UsageDimension.create', { key: 'cost', unit: 'USD' });
    const stream = await call(u + 'UsageStream.create', { label: 'Actual usage', dimension: dimension.id });
    const source = await call(u + 'UsageSource.create', { key: 'billing' });
    const usage = await run(new Usage(engine).ingest({ stream: String(stream.id), dimension: String(dimension.id), unit: 'USD', quantity: '60', ordinal: 1, source: String(source.id), eventKey: 'usage-1', occurredAt: '2026-01-02T00:00:00Z' }, ctx));
    const actual = await call(p + 'BudgetActual.create', { encumbrance: winning.id, amount: '60', posting: posting.id, account: account.id, usage: usage.id });
    await run(api.publish({ encumbrance: String(winning.id), action: 'Spend', previous: String(state.events.at(-1)!.id), actual: String(actual.id) }, ctx));
    state = await run(api.state(String(envelope.id), ctx));
    expect(state).toMatchObject({ committed: '0.000000', spent: '60.000000', available: '40.000000' });
    await expect(run(api.publish({ encumbrance: String(loser.id), action: 'Commit', previous: String(state.events.at(-1)!.id) }, ctx))).rejects.toThrow();
    const reverse = await run(ledger.reverse(String(book.id), String(posting.id), 'reverse', 'Cost reversed', ctx));
    await run(api.publish({ encumbrance: String(winning.id), action: 'Reverse', previous: String(state.events.at(-1)!.id), actual: String(actual.id), reversal: String(reverse.id) }, ctx));
    state = await run(api.state(String(envelope.id), ctx)); expect(state.available).toBe('100.000000');
    await run(api.publish({ encumbrance: String(loser.id), action: 'Commit', previous: String(state.events.at(-1)!.id) }, ctx));
    state = await run(api.state(String(envelope.id), ctx));
    await run(api.publish({ encumbrance: String(loser.id), action: 'Release', previous: String(state.events.at(-1)!.id) }, ctx));
    expect((await run(api.state(String(envelope.id), ctx))).available).toBe('100.000000');
    expect((await call(p + 'ForecastValue.get', { id: (await call(p + 'ForecastValue.create', { scenario: updated.id, goal: (await call(p + 'Goal.create', { plan: plan.id, metric: 'Other', unit: 'unit', target: '1' })).id, quantity: '99' })).id })).quantity).toBe('99.000000');
    await expect(run(api.state(String(envelope.id), { ...ctx, tenant: 'foreign' }))).rejects.toThrow();
  } finally { await f.close(); }
});
