-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE configuration (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "layer" TEXT NOT NULL,
  "layer_ordinal" INTEGER NOT NULL,
  "parent" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, layer) REFERENCES configuration_layer (tenant, id),
  FOREIGN KEY (tenant, parent) REFERENCES configuration (tenant, id)
);

CREATE TABLE configuration_layer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE parameter_assignment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "configuration" TEXT NOT NULL,
  "parameter" TEXT NOT NULL,
  "value_" TEXT,
  "secret_ref" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, configuration) REFERENCES configuration (tenant, id),
  FOREIGN KEY (tenant, parameter) REFERENCES parameter_definition (tenant, id),
  FOREIGN KEY (tenant, secret_ref) REFERENCES secret_binding (tenant, id)
);

CREATE TABLE parameter_definition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "value_type" TEXT NOT NULL,
  "secret" INTEGER NOT NULL,
  "required" INTEGER NOT NULL,
  "default_value" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, value_type) REFERENCES parameter_type (tenant, id)
);

CREATE TABLE parameter_type (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "secret" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE resolved_configuration (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "configuration" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "resolved_at" TEXT NOT NULL,
  "entry_count" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, configuration) REFERENCES configuration (tenant, id)
);

CREATE TABLE resolved_value (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "resolved" TEXT NOT NULL,
  "parameter" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "value_" TEXT,
  "secret_ref" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, resolved) REFERENCES resolved_configuration (tenant, id),
  FOREIGN KEY (tenant, parameter) REFERENCES parameter_definition (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES configuration (tenant, id),
  FOREIGN KEY (tenant, secret_ref) REFERENCES secret_binding (tenant, id)
);

CREATE TABLE secret_binding (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "reference" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE realization (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "build_hash" TEXT NOT NULL,
  "manifest_digest" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE repository (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "locator" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE specification_pin (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "anchor" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, repository) REFERENCES repository (tenant, id)
);

CREATE TABLE deployment_configuration (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "environment" TEXT NOT NULL,
  "resolved" TEXT NOT NULL,
  "deployed_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, resolved) REFERENCES resolved_configuration (tenant, id)
);

CREATE TABLE drift_observation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "deployment" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "matches" INTEGER NOT NULL,
  "detail" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, deployment) REFERENCES deployment_configuration (tenant, id)
);

CREATE TABLE process_unit (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "settings" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, settings) REFERENCES configuration (tenant, id)
);

CREATE TABLE tenant_plan (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "account" TEXT NOT NULL,
  "settings" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, settings) REFERENCES configuration (tenant, id)
);

CREATE TABLE workspace_agent (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "settings" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, settings) REFERENCES configuration (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX configuration_uq_pin_key_layer ON configuration (tenant, pin, key_, layer);
CREATE INDEX configuration_ix_by_pin ON configuration (tenant, pin, id);
CREATE UNIQUE INDEX configuration_layer_uq_key ON configuration_layer (tenant, key_);
CREATE UNIQUE INDEX configuration_layer_uq_ordinal ON configuration_layer (tenant, ordinal);
CREATE INDEX configuration_layer_ix_by_ordinal ON configuration_layer (tenant, ordinal, id);
CREATE UNIQUE INDEX parameter_assignment_uq_configuration_parameter ON parameter_assignment (tenant, configuration, parameter);
CREATE INDEX parameter_assignment_ix_by_configuration ON parameter_assignment (tenant, configuration, id);
CREATE UNIQUE INDEX parameter_definition_uq_pin_key ON parameter_definition (tenant, pin, key_);
CREATE INDEX parameter_definition_ix_by_pin ON parameter_definition (tenant, pin, id);
CREATE UNIQUE INDEX parameter_type_uq_key ON parameter_type (tenant, key_);
CREATE UNIQUE INDEX resolved_configuration_uq_configuration_digest ON resolved_configuration (tenant, configuration, digest);
CREATE INDEX resolved_configuration_ix_by_configuration ON resolved_configuration (tenant, configuration, id);
CREATE UNIQUE INDEX resolved_value_uq_resolved_parameter ON resolved_value (tenant, resolved, parameter);
CREATE INDEX resolved_value_ix_by_resolved ON resolved_value (tenant, resolved, id);
CREATE UNIQUE INDEX secret_binding_uq_key ON secret_binding (tenant, key_);
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization (tenant, pin, build_hash, manifest_digest);
CREATE INDEX realization_ix_by_pin ON realization (tenant, pin, id);
CREATE UNIQUE INDEX repository_uq_key ON repository (tenant, key_);
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin (tenant, repository, anchor, revision);
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin (tenant, repository, anchor, id);
CREATE UNIQUE INDEX deployment_configuration_uq_resolved ON deployment_configuration (tenant, resolved);
CREATE INDEX deployment_configuration_ix_by_environment ON deployment_configuration (tenant, environment, id);
CREATE INDEX drift_observation_ix_by_deployment ON drift_observation (tenant, deployment, id);
CREATE UNIQUE INDEX process_unit_uq_settings ON process_unit (tenant, settings);
CREATE UNIQUE INDEX process_unit_uq_tag ON process_unit (tenant, tag);
CREATE UNIQUE INDEX tenant_plan_uq_account ON tenant_plan (tenant, account);
CREATE UNIQUE INDEX tenant_plan_uq_settings ON tenant_plan (tenant, settings);
CREATE UNIQUE INDEX workspace_agent_uq_settings ON workspace_agent (tenant, settings);
