-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE customer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT,
  "tier" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "deleted_at" TEXT,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE department (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "parent" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, customer) REFERENCES customer (tenant, id),
  FOREIGN KEY (tenant, parent) REFERENCES department (tenant, id)
);

CREATE TABLE order_ (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "site" TEXT NOT NULL,
  "subtotal" INTEGER NOT NULL,
  "tax" INTEGER NOT NULL,
  "requested_on" TEXT NOT NULL,
  "notes" TEXT,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, customer) REFERENCES customer (tenant, id),
  FOREIGN KEY (tenant, site) REFERENCES site (tenant, id),
  CONSTRAINT order__status CHECK (status IN ('Draft', 'Completed', 'Cancelled', 'Submitted', 'Approved'))
);

CREATE TABLE order_document (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "order_" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "upload_state" TEXT NOT NULL,
  "media_type" TEXT,
  "byte_count" INTEGER,
  "digest" TEXT,
  "upload_attempt" INTEGER,
  "staged_media_type" TEXT,
  "staged_byte_count" INTEGER,
  "content_generation" INTEGER,
  "sealed_generation" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, order_) REFERENCES order_ (tenant, id)
);

CREATE TABLE site (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "timezone" TEXT NOT NULL,
  "enabled" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, customer) REFERENCES customer (tenant, id)
);

CREATE TABLE site_policy (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "site" TEXT NOT NULL,
  "max_order_total" INTEGER NOT NULL,
  "requires_approval" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "effective_from" TEXT NOT NULL,
  "effective_until" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, site) REFERENCES site (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX customer_uq_code ON customer (tenant, code);
CREATE INDEX customer_ix_by_tier ON customer (tenant, tier, name, id);
CREATE INDEX department_ix_by_customer ON department (tenant, customer, name, id);
CREATE INDEX order__ix_by_customer ON order_ (tenant, customer, created_at, id);
CREATE INDEX order__ix_by_site_status ON order_ (tenant, site, status, created_at, id);
CREATE INDEX order_document_ix_by_order ON order_document (tenant, order_, created_at, id);
CREATE UNIQUE INDEX site_uq_code_within_customer ON site (tenant, customer, code);
CREATE INDEX site_ix_by_customer ON site (tenant, customer, name, id);
CREATE INDEX site_policy_ix_by_site ON site_policy (tenant, site, effective_from, id);
