-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE usage_correction (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "event" TEXT NOT NULL,
  "replacement" TEXT,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, event) REFERENCES usage_event (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES usage_event (tenant, id)
);

CREATE TABLE usage_dimension (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "unit" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE usage_event (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "stream" TEXT NOT NULL,
  "dimension" TEXT NOT NULL,
  "unit" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "source" TEXT NOT NULL,
  "event_key" TEXT NOT NULL,
  "occurred_at" TEXT,
  "interval_start" TEXT,
  "interval_end" TEXT,
  "replacement_for" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, stream) REFERENCES usage_stream (tenant, id),
  FOREIGN KEY (tenant, dimension) REFERENCES usage_dimension (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES usage_source (tenant, id),
  FOREIGN KEY (tenant, replacement_for) REFERENCES usage_event (tenant, id)
);

CREATE TABLE usage_source (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE usage_stream (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "dimension" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, dimension) REFERENCES usage_dimension (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX usage_correction_uq_event ON usage_correction (tenant, event);
CREATE UNIQUE INDEX usage_dimension_uq_key ON usage_dimension (tenant, key_);
CREATE UNIQUE INDEX usage_event_uq_source_eventKey ON usage_event (tenant, source, event_key);
CREATE UNIQUE INDEX usage_event_uq_stream_ordinal ON usage_event (tenant, stream, ordinal);
CREATE INDEX usage_event_ix_by_stream ON usage_event (tenant, stream, ordinal, id);
CREATE UNIQUE INDEX usage_source_uq_key ON usage_source (tenant, key_);
