-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE artifact (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE artifact_content (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  "upload_state" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C",
  "byte_count" BIGINT,
  "digest" TEXT COLLATE "C",
  "upload_attempt" BIGINT,
  "staged_media_type" TEXT COLLATE "C",
  "staged_byte_count" BIGINT,
  "content_generation" BIGINT,
  "sealed_generation" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evaluation_executor (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evaluation_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evidence_source (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE issuer (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier_set" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C",
  "issuer_scope" TEXT COLLATE "C" NOT NULL,
  "value_" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier_set") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES issuer ("tenant", "id")
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier") REFERENCES identifier ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES identifier ("tenant", "id")
);

CREATE TABLE participation_role (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE participation_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE party (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id")
);

CREATE TABLE participation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation_set" TEXT COLLATE "C" NOT NULL,
  "participant" TEXT COLLATE "C" NOT NULL,
  "role" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation_set") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "role") REFERENCES participation_role ("tenant", "id")
);

CREATE TABLE participation_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "revoked" BIGINT NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation") REFERENCES participation ("tenant", "id")
);

CREATE TABLE decision_elector (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation" TEXT COLLATE "C" NOT NULL,
  "ended" TEXT COLLATE "C",
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation") REFERENCES participation ("tenant", "id"),
  FOREIGN KEY ("tenant", "ended") REFERENCES participation_end ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES decision_elector ("tenant", "id")
);

CREATE TABLE principal_representation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  "principal" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id")
);

CREATE TABLE representation_revocation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "representation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "representation") REFERENCES principal_representation ("tenant", "id")
);

CREATE TABLE publication_series (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE publication_channel (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "series" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "audience" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "series") REFERENCES publication_series ("tenant", "id"),
  FOREIGN KEY ("tenant", "audience") REFERENCES participation_set ("tenant", "id")
);

CREATE TABLE repository (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "provider" TEXT COLLATE "C" NOT NULL,
  "locator" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE specification_pin (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "repository" TEXT COLLATE "C" NOT NULL,
  "anchor" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "repository") REFERENCES repository ("tenant", "id")
);

CREATE TABLE evaluation_run (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "evaluation_set" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "executor" TEXT COLLATE "C" NOT NULL,
  "parent" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation_set") REFERENCES evaluation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "executor") REFERENCES evaluation_executor ("tenant", "id"),
  FOREIGN KEY ("tenant", "parent") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE evaluation_start (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "started_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE realization (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pin" TEXT COLLATE "C" NOT NULL,
  "build_hash" TEXT COLLATE "C" NOT NULL,
  "manifest_digest" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pin") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE artifact_component (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE artifact_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "artifact" TEXT COLLATE "C" NOT NULL,
  "content" TEXT COLLATE "C" NOT NULL,
  "digest" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C" NOT NULL,
  "byte_count" BIGINT NOT NULL,
  "specification_pin" TEXT COLLATE "C",
  "realization" TEXT COLLATE "C",
  "components" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "artifact") REFERENCES artifact ("tenant", "id"),
  FOREIGN KEY ("tenant", "content") REFERENCES artifact_content ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification_pin") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "realization") REFERENCES realization ("tenant", "id"),
  FOREIGN KEY ("tenant", "components") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE decision_case (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation_set" TEXT COLLATE "C" NOT NULL,
  "eligibility_at" TEXT COLLATE "C" NOT NULL,
  "electors" TEXT COLLATE "C" NOT NULL,
  "rule" TEXT COLLATE "C" NOT NULL,
  "rule_version" TEXT COLLATE "C" NOT NULL,
  "threshold" BIGINT NOT NULL,
  "option_count" BIGINT NOT NULL,
  "deadline" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "evaluation" TEXT COLLATE "C",
  "reconsideration" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation_set") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "electors") REFERENCES decision_elector ("tenant", "id"),
  FOREIGN KEY ("tenant", "reconsideration") REFERENCES decision_case ("tenant", "id")
);

CREATE TABLE decision_option (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id")
);

CREATE TABLE decision_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "kind" TEXT COLLATE "C" NOT NULL,
  "response" TEXT COLLATE "C",
  "outcome" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES decision_event ("tenant", "id")
);

CREATE TABLE decision_outcome (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "selected" TEXT COLLATE "C" NOT NULL,
  "responses" TEXT COLLATE "C" NOT NULL,
  "snapshot_digest" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "selected") REFERENCES decision_option ("tenant", "id")
);

CREATE TABLE decision_outcome_member (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES decision_outcome_member ("tenant", "id")
);

CREATE TABLE decision_response (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "voter" TEXT COLLATE "C" NOT NULL,
  "ranking" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "voter") REFERENCES participation ("tenant", "id")
);

CREATE TABLE evaluation_finish (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "start" TEXT COLLATE "C",
  "outcome" TEXT COLLATE "C" NOT NULL,
  "finished_at" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "start") REFERENCES evaluation_start ("tenant", "id")
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "predecessor" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evidence_item (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "source_record" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "observed_at" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C",
  "digest" TEXT COLLATE "C",
  "provenance" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES evidence_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE evidence_member (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "item" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "item") REFERENCES evidence_item ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES evidence_member ("tenant", "id")
);

CREATE TABLE evidence_seal (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "head" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "head") REFERENCES evidence_member ("tenant", "id")
);

CREATE TABLE release_candidate (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "series" TEXT COLLATE "C" NOT NULL,
  "version" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "artifact" TEXT COLLATE "C" NOT NULL,
  "policy" TEXT COLLATE "C" NOT NULL,
  "evaluation_definition" TEXT COLLATE "C",
  "decision_case" TEXT COLLATE "C",
  "approved_option" TEXT COLLATE "C",
  "support" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "series") REFERENCES publication_series ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "artifact") REFERENCES artifact_revision ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation_definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "approved_option") REFERENCES decision_option ("tenant", "id"),
  FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE candidate_evaluation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "candidate" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "candidate") REFERENCES release_candidate ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE candidate_qualification (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "candidate" TEXT COLLATE "C" NOT NULL,
  "policy" TEXT COLLATE "C" NOT NULL,
  "evaluation" TEXT COLLATE "C",
  "decision" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "candidate") REFERENCES release_candidate ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation") REFERENCES evaluation_finish ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision") REFERENCES decision_outcome ("tenant", "id")
);

CREATE TABLE release (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "series" TEXT COLLATE "C" NOT NULL,
  "candidate" TEXT COLLATE "C" NOT NULL,
  "qualification" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "artifact" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "series") REFERENCES publication_series ("tenant", "id"),
  FOREIGN KEY ("tenant", "candidate") REFERENCES release_candidate ("tenant", "id"),
  FOREIGN KEY ("tenant", "qualification") REFERENCES candidate_qualification ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "artifact") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE promotion (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "series" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "kind" TEXT COLLATE "C" NOT NULL,
  "release" TEXT COLLATE "C" NOT NULL,
  "channel" TEXT COLLATE "C",
  "command_key" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "series") REFERENCES publication_series ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES promotion ("tenant", "id"),
  FOREIGN KEY ("tenant", "release") REFERENCES release ("tenant", "id"),
  FOREIGN KEY ("tenant", "channel") REFERENCES publication_channel ("tenant", "id")
);

CREATE TABLE release_audience_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "promotion" TEXT COLLATE "C" NOT NULL,
  "release" TEXT COLLATE "C" NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "audience" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "promotion") REFERENCES promotion ("tenant", "id"),
  FOREIGN KEY ("tenant", "release") REFERENCES release ("tenant", "id"),
  FOREIGN KEY ("tenant", "channel") REFERENCES publication_channel ("tenant", "id"),
  FOREIGN KEY ("tenant", "audience") REFERENCES participation_set ("tenant", "id")
);

ALTER TABLE artifact_component ADD FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id");

ALTER TABLE decision_case ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE decision_case ADD FOREIGN KEY ("tenant", "evaluation") REFERENCES evaluation_finish ("tenant", "id");

ALTER TABLE decision_event ADD FOREIGN KEY ("tenant", "response") REFERENCES decision_response ("tenant", "id");

ALTER TABLE decision_event ADD FOREIGN KEY ("tenant", "outcome") REFERENCES decision_outcome ("tenant", "id");

ALTER TABLE decision_outcome ADD FOREIGN KEY ("tenant", "responses") REFERENCES decision_outcome_member ("tenant", "id");

ALTER TABLE decision_outcome_member ADD FOREIGN KEY ("tenant", "response") REFERENCES decision_response ("tenant", "id");

ALTER TABLE decision_response ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE evaluation_finish ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE evidence_bundle ADD FOREIGN KEY ("tenant", "predecessor") REFERENCES evidence_seal ("tenant", "id");

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX artifact_uq_key ON artifact ("tenant", "key_");
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision ("tenant", "content");
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision ("tenant", "artifact", "id");
CREATE UNIQUE INDEX decision_event_uq_decisionCase_ordinal ON decision_event ("tenant", "decision_case", "ordinal");
CREATE UNIQUE INDEX decision_event_uq_kind_response ON decision_event ("tenant", "kind", "response");
CREATE UNIQUE INDEX decision_event_uq_previous ON decision_event ("tenant", "previous");
CREATE UNIQUE INDEX decision_option_uq_decisionCase_ordinal ON decision_option ("tenant", "decision_case", "ordinal");
CREATE UNIQUE INDEX decision_response_uq_decisionCase_voter ON decision_response ("tenant", "decision_case", "voter");
CREATE UNIQUE INDEX evaluation_executor_uq_key ON evaluation_executor ("tenant", "key_");
CREATE UNIQUE INDEX evaluation_finish_uq_run ON evaluation_finish ("tenant", "run");
CREATE INDEX evaluation_run_ix_by_definition ON evaluation_run ("tenant", "definition", "id");
CREATE INDEX evaluation_run_ix_by_evaluation_set ON evaluation_run ("tenant", "evaluation_set", "id");
CREATE UNIQUE INDEX evaluation_start_uq_run ON evaluation_start ("tenant", "run");
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle ("tenant", "key_");
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item ("tenant", "bundle", "source", "source_record");
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item ("tenant", "bundle", "id");
CREATE INDEX evidence_item_ix_by_source ON evidence_item ("tenant", "source", "id");
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal ("tenant", "bundle");
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source ("tenant", "key_");
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier ("tenant", "namespace", "issuer_scope", "value_");
CREATE INDEX identifier_ix_by_identifier_set ON identifier ("tenant", "identifier_set", "id");
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition ("tenant", "identifier");
CREATE UNIQUE INDEX issuer_uq_key ON issuer ("tenant", "key_");
CREATE UNIQUE INDEX participation_uq_participationSet_participant_role_validFrom ON participation ("tenant", "participation_set", "participant", "role", "valid_from");
CREATE INDEX participation_ix_by_participant ON participation ("tenant", "participant", "id");
CREATE INDEX participation_ix_by_participation_set ON participation ("tenant", "participation_set", "id");
CREATE UNIQUE INDEX participation_end_uq_participation ON participation_end ("tenant", "participation");
CREATE UNIQUE INDEX participation_role_uq_namespace_name ON participation_role ("tenant", "namespace", "name");
CREATE UNIQUE INDEX party_uq_identifiers ON party ("tenant", "identifiers");
CREATE UNIQUE INDEX principal_representation_uq_principal_party_validFrom ON principal_representation ("tenant", "principal", "party", "valid_from");
CREATE INDEX principal_representation_ix_by_party ON principal_representation ("tenant", "party", "id");
CREATE INDEX principal_representation_ix_by_principal ON principal_representation ("tenant", "principal", "id");
CREATE UNIQUE INDEX representation_revocation_uq_representation ON representation_revocation ("tenant", "representation");
CREATE UNIQUE INDEX candidate_evaluation_uq_candidate ON candidate_evaluation ("tenant", "candidate");
CREATE UNIQUE INDEX candidate_evaluation_uq_run ON candidate_evaluation ("tenant", "run");
CREATE UNIQUE INDEX candidate_qualification_uq_candidate ON candidate_qualification ("tenant", "candidate");
CREATE UNIQUE INDEX promotion_uq_commandKey ON promotion ("tenant", "command_key");
CREATE UNIQUE INDEX promotion_uq_previous ON promotion ("tenant", "previous");
CREATE UNIQUE INDEX promotion_uq_series_ordinal ON promotion ("tenant", "series", "ordinal");
CREATE UNIQUE INDEX publication_channel_uq_series_name ON publication_channel ("tenant", "series", "name");
CREATE UNIQUE INDEX publication_series_uq_key ON publication_series ("tenant", "key_");
CREATE UNIQUE INDEX release_uq_candidate ON release ("tenant", "candidate");
CREATE UNIQUE INDEX release_audience_link_uq_promotion ON release_audience_link ("tenant", "promotion");
CREATE UNIQUE INDEX release_candidate_uq_series_version ON release_candidate ("tenant", "series", "version");
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization ("tenant", "pin", "build_hash", "manifest_digest");
CREATE INDEX realization_ix_by_pin ON realization ("tenant", "pin", "id");
CREATE UNIQUE INDEX repository_uq_key ON repository ("tenant", "key_");
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin ("tenant", "repository", "anchor", "revision");
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin ("tenant", "repository", "anchor", "id");
