// Generated by forgec build from @forgegraph/foundation/knowledge (contracts/1). Do not edit.

export interface OperationSpec { method: string; path: string; kind: string; resource: string }
export interface ChangesetOperation { op: string; input: unknown }
export interface ChangesetItem { index: number; op: string; status: "ok" | "error" | "committed" | "skipped"; diff?: { path: string; before: unknown; after: unknown }[]; result?: unknown; error?: Problem }
export interface ChangesetBudget { mode: string; logicalOperations: number; logicalLimit: number; physicalActions: number; physicalLimit: number; atomicAllowed: boolean }
export interface Changeset { id: string; status: string; mode: "atomic" | "resumable"; operations: number; contentHash?: string; items?: ChangesetItem[]; budget?: ChangesetBudget; results?: ChangesetItem[] }
export interface ImportInspection { header: string[]; rows: number; sample: string[][]; suggestedMapping: Record<string, string>; errors: { line: number; code: string; message: string }[] }
export interface ImportStaged { changeset: string; rows: number; staged: number; rowErrors: { line: number; code: string; path?: string; message: string }[] }
export interface ImportsApi {
  inspect(input: { resource: string; csv: string }): Promise<ImportInspection>;
  stage(input: { resource: string; csv: string; mapping: Record<string, string>; upsertBy?: string; mode?: "atomic" | "resumable" }): Promise<ImportStaged>;
}
export interface ChangesetsApi {
  propose(input: { mode?: "atomic" | "resumable"; operations: ChangesetOperation[] }, opts?: CallOptions): Promise<Changeset>;
  get(id: string): Promise<Changeset>;
  preview(id: string): Promise<Changeset & { contentHash: string }>;
  approve(id: string, contentHash: string): Promise<Changeset>;
  commit(id: string, opts?: CallOptions): Promise<Changeset>;
}
export interface Page<T> { items: T[]; next: string | null; limit: number }
export interface ProjectionStatus { generation: number; status: string; lastProcessed: unknown }
export interface CacheRead<T> { value: T; source: "cache" | "loader"; freshUntil: string }
export interface Snapshot { version: "export/1"; package: string; tenant: string; exportedAt: string; manifest: { contractsVersion: string; buildHash: string; resources: string[] }; resources: Record<string, { count: number; hash: string; records: Record<string, unknown>[] }> }
export interface VerifyReport { ok: boolean; verifiedAt: string; resources: Record<string, { expectedCount: number; actualCount: number; hashMatch: boolean; revisionMismatches: { id: string; expected: unknown; actual: unknown }[]; references: { checked: number; missing: number } }> }
/** Provider switching (plan §22): operator-only. */
export interface AdminApi {
  export(): Promise<Snapshot>;
  import(snapshot: Snapshot): Promise<{ imported: Record<string, number>; skipped: Record<string, number>; importedAt: string }>;
  verify(snapshot: Snapshot): Promise<VerifyReport>;
  fence(on: boolean): Promise<{ fenced: boolean }>;
  /** Records of one subject through declared bindings; linked subjects reported, never cascaded (plan §7.2). */
  locateSubject(input: { kind: string; resource: string; id: string }): Promise<{ subject: { kind: string; resource: string; id: string }; records: { resource: string; count: number; via?: string }[]; linked: { resource: string; id: string; via: string; kind: string; sharedWith: number | null }[]; cascade: never[] }>;
  /** Content inspection verdict bound to the sealed digest (plan §7.3). */
  inspect(input: { resource: string; id: string; digest: string; verdict: "allowed" | "quarantined" | "failed" | "review"; detector: string; detail?: string }): Promise<{ id: string; generation: number; inspection: { state: string; generation: number } }>;
}
export interface ScheduleStatus { source: string; lastOccurrence: string | null; next: string | null; skipped: string[] }
export interface ScheduleTick { source: string; occurrence: string; outcome: "ran" | "duplicate" | "skipped-overlap" | "failed"; error?: string }
export interface WorkflowInstance { id: string; workflow: string; version: number; status: "running" | "waiting" | "sleeping" | "completed" | "failed" | "cancelled"; input: Record<string, unknown>; bindings: Record<string, unknown>; history: { step: string; kind: string; at: string }[]; waiting?: { step: string; message: string; correlationKey: string; dueAt?: string }; sleeping?: { step: string; dueAt: string }; output?: unknown; error?: { code: string; detail?: string } }
export interface PageOptions { cursor?: string | null; limit?: number }
export interface CallOptions { idempotencyKey?: string; /** Edition 2027: the purpose surface to run under (one; never a union). */ purpose?: string }
export interface SignedUrl { url: string; method: "PUT" | "GET"; headers?: Record<string, string>; expiresAt: string }
export interface ProblemField { path: string; code: string; message: string }
export interface Problem {
  type: string; title: string; status: number; code: string; detail?: string;
  requestId?: string; retryable: boolean; fields?: ProblemField[]; constraint?: string;
}
export type CallResult = { ok: true; value: unknown; version?: number } | { ok: false; code: string; status: number; problem: Problem };
export class ForgeError extends Error {
  readonly problem: Problem;
  constructor(problem: Problem) {
    super(`${problem.code}: ${problem.detail ?? problem.title}`);
    this.problem = problem;
  }
  get code() { return this.problem.code; }
  get status() { return this.problem.status; }
}
export interface ClientOptions {
  baseUrl: string;
  tenant?: string;
  actor?: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

function fillPath(path: string, input: Record<string, unknown>): string {
  return path.replace(/\{(\w+)\}/g, (_, k) => encodeURIComponent(String(input[k])));
}

export function createTransport(options: ClientOptions, ops: Record<string, OperationSpec>) {
  const f = options.fetch ?? fetch;
  const base = options.baseUrl.replace(/\/$/, "");
  async function call(op: string, rawInput: unknown, opts?: CallOptions): Promise<CallResult> {
    const spec = ops[op];
    if (!spec) throw new Error(`unknown operation ${op}`);
    const input = (rawInput ?? {}) as Record<string, unknown>;
    const headers: Record<string, string> = { accept: "application/json", ...(options.headers ?? {}) };
    if (options.tenant) headers["x-forge-tenant"] = options.tenant;
    if (options.actor) headers["x-forge-actor"] = options.actor;
    if (opts?.idempotencyKey) headers["idempotency-key"] = opts.idempotencyKey;
    if (opts?.purpose) headers["x-forge-purpose"] = opts.purpose;
    if (typeof input["expectedVersion"] === "number") headers["if-match"] = `"${input["expectedVersion"]}"`;
    let url = base + fillPath(spec.path, input);
    let body: string | null = null;
    if (spec.kind === "find" || spec.kind === "list" || spec.kind === "effective" || spec.kind === "view.query" || spec.kind === "cache.read") {
      const q = new URLSearchParams();
      for (const [k, v] of Object.entries((input[spec.kind === "cache.read" ? "key" : "params"] ?? {}) as Record<string, unknown>)) q.set(k, String(v));
      if (input["cursor"]) q.set("cursor", String(input["cursor"]));
      if (input["limit"]) q.set("limit", String(input["limit"]));
      const qs = q.toString();
      if (qs) url += "?" + qs;
    } else if (spec.kind === "create" || spec.kind === "function" || spec.kind === "workflow.start" || spec.kind.startsWith("admin.") || spec.kind === "changeset.propose" || spec.kind === "changeset.approve" || spec.kind === "import.inspect" || spec.kind === "import.stage") {
      const { id: _id, ...rest } = input;
      void _id;
      body = JSON.stringify(spec.kind === "changeset.approve" ? rest : input);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "workflow.signal") {
      const { message: _m, ...rest } = input;
      void _m;
      body = JSON.stringify(rest);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "workflow.cancel" || spec.kind === "schedule.tick" || spec.kind === "projection.rebuild") {
      body = JSON.stringify(input);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "update") {
      body = JSON.stringify(input["patch"] ?? {});
      headers["content-type"] = "application/json";
    } else if (spec.kind === "beginUpload" || spec.kind === "move") {
      const { id: _id, expectedVersion: _v, ...rest } = input;
      void _id;
      void _v;
      body = JSON.stringify(rest);
      headers["content-type"] = "application/json";
    } else if (spec.kind === "transition") {
      body = JSON.stringify(input["input"] ?? {});
      headers["content-type"] = "application/json";
    }
    const res = await f(url, { method: spec.method, headers, body });
    const text = await res.text();
    const json = text ? JSON.parse(text) : null;
    if (res.ok) {
      const etag = res.headers.get("etag");
      return { ok: true, value: json, ...(etag ? { version: Number(etag.replace(/"/g, "")) } : {}) };
    }
    const problem: Problem = json && json.code ? json : { type: "about:blank", title: res.statusText, status: res.status, code: "Internal", retryable: res.status >= 500 };
    return { ok: false, code: problem.code, status: res.status, problem };
  }
  async function unwrap<T>(p: Promise<CallResult>): Promise<T> {
    const r = await p;
    if (r.ok) return r.value as T;
    throw new ForgeError(r.problem);
  }
  async function unwrapNullable<T>(p: Promise<CallResult>): Promise<T | null> {
    const r = await p;
    if (r.ok) return r.value as T;
    if (r.code === "NotFound") return null;
    throw new ForgeError(r.problem);
  }
  return { call, unwrap, unwrapNullable };
}

export const operations: Record<string, OperationSpec> = {
  "@forgegraph/foundation/specification/_/Realization.create": { method: "POST", path: "/v1/specification/realizations", kind: "create", resource: "Realization" },
  "@forgegraph/foundation/specification/_/Realization.get": { method: "GET", path: "/v1/specification/realizations/{id}", kind: "get", resource: "Realization" },
  "@forgegraph/foundation/specification/_/Realization.list.all": { method: "GET", path: "/v1/specification/realizations", kind: "list", resource: "Realization" },
  "@forgegraph/foundation/specification/_/Realization.list.byPin": { method: "GET", path: "/v1/specification/realizations/queries/by-pin", kind: "list", resource: "Realization" },
  "@forgegraph/foundation/specification/_/Repository.create": { method: "POST", path: "/v1/specification/repositories", kind: "create", resource: "Repository" },
  "@forgegraph/foundation/specification/_/Repository.get": { method: "GET", path: "/v1/specification/repositories/{id}", kind: "get", resource: "Repository" },
  "@forgegraph/foundation/specification/_/Repository.update": { method: "PATCH", path: "/v1/specification/repositories/{id}", kind: "update", resource: "Repository" },
  "@forgegraph/foundation/specification/_/Repository.delete": { method: "DELETE", path: "/v1/specification/repositories/{id}", kind: "delete", resource: "Repository" },
  "@forgegraph/foundation/specification/_/Repository.find.byKey": { method: "GET", path: "/v1/specification/repositories/queries/by-key", kind: "find", resource: "Repository" },
  "@forgegraph/foundation/specification/_/Repository.list.all": { method: "GET", path: "/v1/specification/repositories", kind: "list", resource: "Repository" },
  "@forgegraph/foundation/specification/_/SpecificationPin.create": { method: "POST", path: "/v1/specification/pins", kind: "create", resource: "SpecificationPin" },
  "@forgegraph/foundation/specification/_/SpecificationPin.get": { method: "GET", path: "/v1/specification/pins/{id}", kind: "get", resource: "SpecificationPin" },
  "@forgegraph/foundation/specification/_/SpecificationPin.find.byRepositoryAnchorRevision": { method: "GET", path: "/v1/specification/pins/queries/by-repository-anchor-revision", kind: "find", resource: "SpecificationPin" },
  "@forgegraph/foundation/specification/_/SpecificationPin.list.all": { method: "GET", path: "/v1/specification/pins", kind: "list", resource: "SpecificationPin" },
  "@forgegraph/foundation/specification/_/SpecificationPin.list.byRepositoryAnchor": { method: "GET", path: "/v1/specification/pins/queries/by-repository-anchor", kind: "list", resource: "SpecificationPin" },
  "@forgegraph/foundation/knowledge/_/changesets.propose": { method: "POST", path: "/v1/changesets", kind: "changeset.propose", resource: "changesets" },
  "@forgegraph/foundation/knowledge/_/changesets.get": { method: "GET", path: "/v1/changesets/{id}", kind: "changeset.get", resource: "changesets" },
  "@forgegraph/foundation/knowledge/_/changesets.preview": { method: "GET", path: "/v1/changesets/{id}/preview", kind: "changeset.preview", resource: "changesets" },
  "@forgegraph/foundation/knowledge/_/changesets.approve": { method: "POST", path: "/v1/changesets/{id}/approve", kind: "changeset.approve", resource: "changesets" },
  "@forgegraph/foundation/knowledge/_/changesets.commit": { method: "POST", path: "/v1/changesets/{id}/commit", kind: "changeset.commit", resource: "changesets" },
  "@forgegraph/foundation/knowledge/_/admin.export": { method: "POST", path: "/v1/admin/export", kind: "admin.export", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/admin.import": { method: "POST", path: "/v1/admin/import", kind: "admin.import", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/admin.verify": { method: "POST", path: "/v1/admin/verify", kind: "admin.verify", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/admin.fence": { method: "POST", path: "/v1/admin/fence", kind: "admin.fence", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/admin.inspect": { method: "POST", path: "/v1/admin/inspect", kind: "admin.inspect", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/admin.subjects.locate": { method: "POST", path: "/v1/admin/subjects/locate", kind: "admin.subjects.locate", resource: "admin" },
  "@forgegraph/foundation/knowledge/_/imports.inspect": { method: "POST", path: "/v1/imports/inspect", kind: "import.inspect", resource: "imports" },
  "@forgegraph/foundation/knowledge/_/imports.stage": { method: "POST", path: "/v1/imports/stage", kind: "import.stage", resource: "imports" },
};

export interface ArtifactRecord {
  id: string;
  key: string;
  label: string;
}

export interface ArtifactCreate {
  key: string;
  label: string;
}

export interface ArtifactPatch {
}

export interface ArtifactComponentRecord {
  id: string;
  name: string;
  revision: string;
  next: string | null;
}

export interface ArtifactComponentCreate {
  name: string;
  revision: string;
  next?: string | null;
}

export interface ArtifactComponentPatch {
}

export interface ArtifactContentRecord {
  id: string;
  version: number;
  createdAt: string;
  updatedAt: string;
  uploadState: string;
  mediaType: string | null;
  byteCount: number | null;
  digest: string | null;
}

export interface ArtifactContentCreate {
}

export interface ArtifactContentPatch {
}

export interface ArtifactRevisionRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  artifact: string;
  content: string;
  digest: string;
  mediaType: string;
  byteCount: number;
  specificationPin: string | null;
  realization: string | null;
  components: string | null;
}

export interface ArtifactRevisionCreate {
  artifact: string;
  content: string;
  digest: string;
  mediaType: string;
  byteCount: number;
  specificationPin?: string | null;
  realization?: string | null;
  components?: string | null;
}

export interface ArtifactRevisionPatch {
}

export interface ClassificationAssignmentRecord {
  id: string;
  classifications: string;
  meaning: string;
  recordedAt: string;
}

export interface ClassificationAssignmentCreate {
  classifications: string;
  meaning: string;
  recordedAt: string;
}

export interface ClassificationAssignmentPatch {
}

export interface ClassificationRetractionRecord {
  id: string;
  assignment: string;
  effectiveAt: string;
  reason: string;
}

export interface ClassificationRetractionCreate {
  assignment: string;
  effectiveAt: string;
  reason: string;
}

export interface ClassificationRetractionPatch {
}

export interface ClassificationSetRecord {
  id: string;
  label: string;
}

export interface ClassificationSetCreate {
  label: string;
}

export interface ClassificationSetPatch {
}

export interface ConceptRecord {
  id: string;
  version: number;
  parent: string | null;
  taxonomy: string;
  ordinal: number;
  identifiers: string;
}

export interface ConceptCreate {
  taxonomy: string;
  ordinal: number;
  identifiers: string;
}

export interface ConceptPatch {
}

export interface ConceptAliasRecord {
  id: string;
  taxonomy: string;
  alias: string;
  meaning: string;
}

export interface ConceptAliasCreate {
  taxonomy: string;
  alias: string;
  meaning: string;
}

export interface ConceptAliasPatch {
}

export interface ConceptDispositionRecord {
  id: string;
  concept: string;
  replacement: string | null;
  effectiveAt: string;
  reason: string;
}

export interface ConceptDispositionCreate {
  concept: string;
  replacement?: string | null;
  effectiveAt: string;
  reason: string;
}

export interface ConceptDispositionPatch {
}

export interface ConceptRevisionRecord {
  id: string;
  concept: string;
  taxonomy: string;
  ordinal: number;
  revision: number;
  previous: string | null;
  parentMeaning: string | null;
  label: string;
  definition: string;
}

export interface ConceptRevisionCreate {
  concept: string;
  taxonomy: string;
  ordinal: number;
  revision: number;
  previous?: string | null;
  parentMeaning?: string | null;
  label: string;
  definition: string;
}

export interface ConceptRevisionPatch {
}

export interface TaxonomyRecord {
  id: string;
  key: string;
  identifiers: string;
}

export interface TaxonomyCreate {
  key: string;
  identifiers: string;
}

export interface TaxonomyPatch {
}

export interface DecisionCaseRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  participationSet: string;
  eligibilityAt: string;
  electors: string;
  rule: "Single" | "First" | "Quorum" | "Unanimous" | "ChooseOne" | "Ranked";
  ruleVersion: string;
  threshold: number;
  optionCount: number;
  deadline: string;
  support: string | null;
  evaluation: string | null;
  reconsideration: string | null;
}

export interface DecisionCaseCreate {
  participationSet: string;
  eligibilityAt: string;
  electors: string;
  rule: "Single" | "First" | "Quorum" | "Unanimous" | "ChooseOne" | "Ranked";
  ruleVersion: string;
  threshold: number;
  optionCount: number;
  deadline: string;
  support?: string | null;
  evaluation?: string | null;
  reconsideration?: string | null;
}

export interface DecisionCasePatch {
}

export interface DecisionElectorRecord {
  id: string;
  participation: string;
  ended: string | null;
  next: string | null;
  depth: number;
}

export interface DecisionElectorCreate {
  participation: string;
  ended?: string | null;
  next?: string | null;
  depth: number;
}

export interface DecisionElectorPatch {
}

export interface DecisionEventRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  decisionCase: string;
  ordinal: number;
  previous: string | null;
  kind: "Responded" | "Withdrawn" | "Finalized" | "Expired";
  response: string | null;
  outcome: string | null;
  recordedBy: string;
}

export interface DecisionEventCreate {
  decisionCase: string;
  ordinal: number;
  previous?: string | null;
  kind: "Responded" | "Withdrawn" | "Finalized" | "Expired";
  response?: string | null;
  outcome?: string | null;
  recordedBy: string;
}

export interface DecisionEventPatch {
}

export interface DecisionOptionRecord {
  id: string;
  decisionCase: string;
  ordinal: number;
  label: string;
}

export interface DecisionOptionCreate {
  decisionCase: string;
  ordinal: number;
  label: string;
}

export interface DecisionOptionPatch {
}

export interface DecisionOutcomeRecord {
  id: string;
  decisionCase: string;
  selected: string;
  responses: string;
  snapshotDigest: string;
}

export interface DecisionOutcomeCreate {
  decisionCase: string;
  selected: string;
  responses: string;
  snapshotDigest: string;
}

export interface DecisionOutcomePatch {
}

export interface DecisionOutcomeMemberRecord {
  id: string;
  response: string;
  next: string | null;
  depth: number;
}

export interface DecisionOutcomeMemberCreate {
  response: string;
  next?: string | null;
  depth: number;
}

export interface DecisionOutcomeMemberPatch {
}

export interface DecisionResponseRecord {
  id: string;
  decisionCase: string;
  voter: string;
  ranking: Array<number>;
  support: string | null;
  recordedBy: string;
}

export interface DecisionResponseCreate {
  decisionCase: string;
  voter: string;
  ranking: Array<number>;
  support?: string | null;
  recordedBy: string;
}

export interface DecisionResponsePatch {
}

export interface EntitlementRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  holder: string;
  right: string;
  scope: string;
  quantity: string | null;
  unit: string | null;
  validFrom: string;
  validUntil: string | null;
  predecessor: string | null;
  recordedBy: string;
  reason: string;
}

export interface EntitlementCreate {
  holder: string;
  right: string;
  scope: string;
  quantity?: string | null;
  unit?: string | null;
  validFrom: string;
  validUntil?: string | null;
  predecessor?: string | null;
  recordedBy: string;
  reason: string;
}

export interface EntitlementPatch {
}

export interface EntitlementEndRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  entitlement: string;
  kind: "Revoked" | "Expired";
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface EntitlementEndCreate {
  entitlement: string;
  kind: "Revoked" | "Expired";
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface EntitlementEndPatch {
}

export interface EntitlementScopeRecord {
  id: string;
  label: string;
}

export interface EntitlementScopeCreate {
  label: string;
}

export interface EntitlementScopePatch {
}

export interface ObligationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  obligatedParty: string;
  requirement: string;
  scope: string;
  quantity: string | null;
  unit: string | null;
  incurredAt: string;
  dueAt: string | null;
  recordedBy: string;
  reason: string;
}

export interface ObligationCreate {
  obligatedParty: string;
  requirement: string;
  scope: string;
  quantity?: string | null;
  unit?: string | null;
  incurredAt: string;
  dueAt?: string | null;
  recordedBy: string;
  reason: string;
}

export interface ObligationPatch {
}

export interface ObligationEndRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  obligation: string;
  kind: "Discharged" | "Cancelled";
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface ObligationEndCreate {
  obligation: string;
  kind: "Discharged" | "Cancelled";
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface ObligationEndPatch {
}

export interface RequirementDefinitionRecord {
  id: string;
  namespace: string;
  name: string;
}

export interface RequirementDefinitionCreate {
  namespace: string;
  name: string;
}

export interface RequirementDefinitionPatch {
}

export interface RightDefinitionRecord {
  id: string;
  namespace: string;
  name: string;
}

export interface RightDefinitionCreate {
  namespace: string;
  name: string;
}

export interface RightDefinitionPatch {
}

export interface EvaluationExecutorRecord {
  id: string;
  key: string;
  label: string;
}

export interface EvaluationExecutorCreate {
  key: string;
  label: string;
}

export interface EvaluationExecutorPatch {
}

export interface EvaluationFinishRecord {
  id: string;
  run: string;
  start: string | null;
  outcome: "Completed" | "Failed" | "Cancelled";
  finishedAt: string;
  support: string | null;
  reason: string;
  recordedBy: string;
}

export interface EvaluationFinishCreate {
  run: string;
  start?: string | null;
  outcome: "Completed" | "Failed" | "Cancelled";
  finishedAt: string;
  support?: string | null;
  reason: string;
  recordedBy: string;
}

export interface EvaluationFinishPatch {
}

export interface EvaluationRunRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  evaluationSet: string;
  definition: string;
  executor: string;
  parent: string | null;
  depth: number;
}

export interface EvaluationRunCreate {
  evaluationSet: string;
  definition: string;
  executor: string;
  parent?: string | null;
  depth: number;
}

export interface EvaluationRunPatch {
}

export interface EvaluationSetRecord {
  id: string;
  label: string;
}

export interface EvaluationSetCreate {
  label: string;
}

export interface EvaluationSetPatch {
}

export interface EvaluationStartRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  run: string;
  startedAt: string;
  recordedBy: string;
}

export interface EvaluationStartCreate {
  run: string;
  startedAt: string;
  recordedBy: string;
}

export interface EvaluationStartPatch {
}

export interface EvidenceBundleRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  key: string;
  label: string;
  predecessor: string | null;
}

export interface EvidenceBundleCreate {
  key: string;
  label: string;
  predecessor?: string | null;
}

export interface EvidenceBundlePatch {
}

export interface EvidenceItemRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  bundle: string;
  source: string;
  sourceRecord: string;
  kind: string;
  observedAt: string;
  revision: string | null;
  digest: string | null;
  provenance: string;
}

export interface EvidenceItemCreate {
  bundle: string;
  source: string;
  sourceRecord: string;
  kind: string;
  observedAt: string;
  revision?: string | null;
  digest?: string | null;
  provenance: string;
}

export interface EvidenceItemPatch {
}

export interface EvidenceMemberRecord {
  id: string;
  bundle: string;
  item: string;
  next: string | null;
  depth: number;
}

export interface EvidenceMemberCreate {
  bundle: string;
  item: string;
  next?: string | null;
  depth: number;
}

export interface EvidenceMemberPatch {
}

export interface EvidenceSealRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  bundle: string;
  head: string | null;
  recordedBy: string;
}

export interface EvidenceSealCreate {
  bundle: string;
  head?: string | null;
  recordedBy: string;
}

export interface EvidenceSealPatch {
}

export interface EvidenceSourceRecord {
  id: string;
  key: string;
  label: string;
}

export interface EvidenceSourceCreate {
  key: string;
  label: string;
}

export interface EvidenceSourcePatch {
}

export interface IdentifierRecord {
  id: string;
  identifierSet: string;
  namespace: string;
  issuer: string | null;
  issuerScope: string;
  value: string;
  validFrom: string;
  validUntil: string | null;
}

export interface IdentifierCreate {
  identifierSet: string;
  namespace: string;
  issuer?: string | null;
  issuerScope: string;
  value: string;
  validFrom: string;
  validUntil?: string | null;
}

export interface IdentifierPatch {
}

export interface IdentifierDispositionRecord {
  id: string;
  identifier: string;
  replacement: string | null;
  effectiveAt: string;
  reason: string;
}

export interface IdentifierDispositionCreate {
  identifier: string;
  replacement?: string | null;
  effectiveAt: string;
  reason: string;
}

export interface IdentifierDispositionPatch {
}

export interface IdentifierSetRecord {
  id: string;
  label: string;
}

export interface IdentifierSetCreate {
  label: string;
}

export interface IdentifierSetPatch {
}

export interface IssuerRecord {
  id: string;
  key: string;
}

export interface IssuerCreate {
  key: string;
}

export interface IssuerPatch {
}

export interface KnowledgeClassificationRecord {
  id: string;
  assignment: string;
  next: string | null;
  depth: number;
}

export interface KnowledgeClassificationCreate {
  assignment: string;
  next?: string | null;
  depth: number;
}

export interface KnowledgeClassificationPatch {
}

export interface KnowledgeFeedbackRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  edition: string;
  revision: string;
  run: string;
}

export interface KnowledgeFeedbackCreate {
  edition: string;
  revision: string;
  run: string;
}

export interface KnowledgeFeedbackPatch {
}

export interface KnowledgeFeedbackResultRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  feedback: string;
  finish: string;
}

export interface KnowledgeFeedbackResultCreate {
  feedback: string;
  finish: string;
}

export interface KnowledgeFeedbackResultPatch {
}

export interface KnowledgeItemRecord {
  id: string;
  key: string;
  title: string;
  accessRight: string;
  scope: string;
}

export interface KnowledgeItemCreate {
  key: string;
  title: string;
  accessRight: string;
  scope: string;
}

export interface KnowledgeItemPatch {
}

export interface KnowledgePublicationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  revision: string;
  release: string;
  audience: string;
}

export interface KnowledgePublicationCreate {
  revision: string;
  release: string;
  audience: string;
}

export interface KnowledgePublicationPatch {
}

export interface KnowledgeRevisionRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  item: string;
  revision: number;
  previous: string | null;
  specification: string;
  content: string;
  classifications: string;
  assessmentDefinition: string;
}

export interface KnowledgeRevisionCreate {
  item: string;
  revision: number;
  previous?: string | null;
  specification: string;
  content: string;
  classifications: string;
  assessmentDefinition: string;
}

export interface KnowledgeRevisionPatch {
}

export interface ParticipationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  participationSet: string;
  participant: string;
  role: string;
  validFrom: string;
  validUntil: string | null;
  recordedBy: string;
  reason: string;
}

export interface ParticipationCreate {
  participationSet: string;
  participant: string;
  role: string;
  validFrom: string;
  validUntil?: string | null;
  recordedBy: string;
  reason: string;
}

export interface ParticipationPatch {
}

export interface ParticipationEndRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  participation: string;
  effectiveAt: string;
  revoked: boolean;
  recordedBy: string;
  reason: string;
}

export interface ParticipationEndCreate {
  participation: string;
  effectiveAt: string;
  revoked: boolean;
  recordedBy: string;
  reason: string;
}

export interface ParticipationEndPatch {
}

export interface ParticipationRoleRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  namespace: string;
  name: string;
}

export interface ParticipationRoleCreate {
  namespace: string;
  name: string;
}

export interface ParticipationRolePatch {
}

export interface ParticipationSetRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  label: string;
}

export interface ParticipationSetCreate {
  label: string;
}

export interface ParticipationSetPatch {
}

export interface PartyRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  label: string;
  identifiers: string | null;
}

export interface PartyCreate {
  label: string;
  identifiers?: string | null;
}

export interface PartyPatch {
}

export interface PrincipalRepresentationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  party: string;
  principal: string;
  validFrom: string;
  validUntil: string | null;
  recordedBy: string;
  reason: string;
}

export interface PrincipalRepresentationCreate {
  party: string;
  principal: string;
  validFrom: string;
  validUntil?: string | null;
  recordedBy: string;
  reason: string;
}

export interface PrincipalRepresentationPatch {
}

export interface RepresentationRevocationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  representation: string;
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface RepresentationRevocationCreate {
  representation: string;
  effectiveAt: string;
  recordedBy: string;
  reason: string;
}

export interface RepresentationRevocationPatch {
}

export interface CandidateEvaluationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  candidate: string;
  run: string;
}

export interface CandidateEvaluationCreate {
  candidate: string;
  run: string;
}

export interface CandidateEvaluationPatch {
}

export interface CandidateQualificationRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  candidate: string;
  policy: "None" | "EvaluationCompleted" | "DecisionApproved" | "Both";
  evaluation: string | null;
  decision: string | null;
}

export interface CandidateQualificationCreate {
  candidate: string;
  policy: "None" | "EvaluationCompleted" | "DecisionApproved" | "Both";
  evaluation?: string | null;
  decision?: string | null;
}

export interface CandidateQualificationPatch {
}

export interface PromotionRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  series: string;
  ordinal: number;
  previous: string | null;
  kind: "Published" | "Promoted" | "Deprecated" | "Retired";
  release: string;
  channel: string | null;
  commandKey: string | null;
  reason: string;
  recordedBy: string;
}

export interface PromotionCreate {
  series: string;
  ordinal: number;
  previous?: string | null;
  kind: "Published" | "Promoted" | "Deprecated" | "Retired";
  release: string;
  channel?: string | null;
  commandKey?: string | null;
  reason: string;
  recordedBy: string;
}

export interface PromotionPatch {
}

export interface PublicationChannelRecord {
  id: string;
  series: string;
  name: string;
  audience: string;
}

export interface PublicationChannelCreate {
  series: string;
  name: string;
  audience: string;
}

export interface PublicationChannelPatch {
}

export interface PublicationSeriesRecord {
  id: string;
  key: string;
  label: string;
}

export interface PublicationSeriesCreate {
  key: string;
  label: string;
}

export interface PublicationSeriesPatch {
}

export interface ReleaseRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  series: string;
  candidate: string;
  qualification: string;
  specification: string;
  artifact: string;
  recordedBy: string;
}

export interface ReleaseCreate {
  series: string;
  candidate: string;
  qualification: string;
  specification: string;
  artifact: string;
  recordedBy: string;
}

export interface ReleasePatch {
}

export interface ReleaseAudienceLinkRecord {
  id: string;
  promotion: string;
  release: string;
  channel: string;
  audience: string;
}

export interface ReleaseAudienceLinkCreate {
  promotion: string;
  release: string;
  channel: string;
  audience: string;
}

export interface ReleaseAudienceLinkPatch {
}

export interface ReleaseCandidateRecord {
  id: string;
  createdAt: string;
  updatedAt: string;
  series: string;
  version: string;
  specification: string;
  artifact: string;
  policy: "None" | "EvaluationCompleted" | "DecisionApproved" | "Both";
  evaluationDefinition: string | null;
  decisionCase: string | null;
  approvedOption: string | null;
  support: string | null;
}

export interface ReleaseCandidateCreate {
  series: string;
  version: string;
  specification: string;
  artifact: string;
  policy: "None" | "EvaluationCompleted" | "DecisionApproved" | "Both";
  evaluationDefinition?: string | null;
  decisionCase?: string | null;
  approvedOption?: string | null;
  support?: string | null;
}

export interface ReleaseCandidatePatch {
}

export interface RealizationRecord {
  id: string;
  pin: string;
  buildHash: string;
  manifestDigest: string;
}

export interface RealizationCreate {
  pin: string;
  buildHash: string;
  manifestDigest: string;
}

export interface RealizationPatch {
}

export interface RepositoryRecord {
  id: string;
  version: number;
  key: string;
  provider: string;
  locator: string;
}

export interface RepositoryCreate {
  key: string;
  provider: string;
  locator: string;
}

export interface RepositoryPatch {
  provider?: string;
  locator?: string;
}

export interface SpecificationPinRecord {
  id: string;
  repository: string;
  anchor: string;
  revision: string;
}

export interface SpecificationPinCreate {
  repository: string;
  anchor: string;
  revision: string;
}

export interface SpecificationPinPatch {
}

export interface ArtifactApi {
}

export interface ArtifactComponentApi {
}

export interface ArtifactContentApi {
}

export interface ArtifactRevisionApi {
}

export interface ClassificationAssignmentApi {
}

export interface ClassificationRetractionApi {
}

export interface ClassificationSetApi {
}

export interface ConceptApi {
}

export interface ConceptAliasApi {
}

export interface ConceptDispositionApi {
}

export interface ConceptRevisionApi {
}

export interface TaxonomyApi {
}

export interface DecisionCaseApi {
}

export interface DecisionElectorApi {
}

export interface DecisionEventApi {
}

export interface DecisionOptionApi {
}

export interface DecisionOutcomeApi {
}

export interface DecisionOutcomeMemberApi {
}

export interface DecisionResponseApi {
}

export interface EntitlementApi {
}

export interface EntitlementEndApi {
}

export interface EntitlementScopeApi {
}

export interface ObligationApi {
}

export interface ObligationEndApi {
}

export interface RequirementDefinitionApi {
}

export interface RightDefinitionApi {
}

export interface EvaluationExecutorApi {
}

export interface EvaluationFinishApi {
}

export interface EvaluationRunApi {
}

export interface EvaluationSetApi {
}

export interface EvaluationStartApi {
}

export interface EvidenceBundleApi {
}

export interface EvidenceItemApi {
}

export interface EvidenceMemberApi {
}

export interface EvidenceSealApi {
}

export interface EvidenceSourceApi {
}

export interface IdentifierApi {
}

export interface IdentifierDispositionApi {
}

export interface IdentifierSetApi {
}

export interface IssuerApi {
}

export interface KnowledgeClassificationApi {
}

export interface KnowledgeFeedbackApi {
}

export interface KnowledgeFeedbackResultApi {
}

export interface KnowledgeItemApi {
}

export interface KnowledgePublicationApi {
}

export interface KnowledgeRevisionApi {
}

export interface ParticipationApi {
}

export interface ParticipationEndApi {
}

export interface ParticipationRoleApi {
}

export interface ParticipationSetApi {
}

export interface PartyApi {
}

export interface PrincipalRepresentationApi {
}

export interface RepresentationRevocationApi {
}

export interface CandidateEvaluationApi {
}

export interface CandidateQualificationApi {
}

export interface PromotionApi {
}

export interface PublicationChannelApi {
}

export interface PublicationSeriesApi {
}

export interface ReleaseApi {
}

export interface ReleaseAudienceLinkApi {
}

export interface ReleaseCandidateApi {
}

export interface RealizationApi {
  create(input: RealizationCreate, opts?: CallOptions): Promise<RealizationRecord>;
  get(id: string): Promise<RealizationRecord>;
  listAll(params: {  }, page?: PageOptions): Promise<Page<RealizationRecord>>;
  listByPin(params: { pin: string }, page?: PageOptions): Promise<Page<RealizationRecord>>;
}

export interface RepositoryApi {
  create(input: RepositoryCreate, opts?: CallOptions): Promise<RepositoryRecord>;
  get(id: string): Promise<RepositoryRecord>;
  update(id: string, expectedVersion: number, patch: RepositoryPatch, opts?: CallOptions): Promise<RepositoryRecord>;
  delete(id: string, expectedVersion: number, opts?: CallOptions): Promise<RepositoryRecord>;
  findByKey(params: { key: string }): Promise<RepositoryRecord | null>;
  listAll(params: {  }, page?: PageOptions): Promise<Page<RepositoryRecord>>;
}

export interface SpecificationPinApi {
  create(input: SpecificationPinCreate, opts?: CallOptions): Promise<SpecificationPinRecord>;
  get(id: string): Promise<SpecificationPinRecord>;
  findByRepositoryAnchorRevision(params: { repository: string; anchor: string; revision: string }): Promise<SpecificationPinRecord | null>;
  listAll(params: {  }, page?: PageOptions): Promise<Page<SpecificationPinRecord>>;
  listByRepositoryAnchor(params: { repository: string; anchor: string }, page?: PageOptions): Promise<Page<SpecificationPinRecord>>;
}

export interface FunctionsApi {
}

export interface ForgeClient {
  functions: FunctionsApi;
  call(op: string, input: unknown, opts?: CallOptions): Promise<CallResult>;
  changesets: ChangesetsApi;
  imports: ImportsApi;
  admin: AdminApi;
  artifacts: ArtifactApi;
  artifactComponents: ArtifactComponentApi;
  artifactContents: ArtifactContentApi;
  artifactRevisions: ArtifactRevisionApi;
  classificationAssignments: ClassificationAssignmentApi;
  classificationRetractions: ClassificationRetractionApi;
  classificationSets: ClassificationSetApi;
  concepts: ConceptApi;
  conceptAliases: ConceptAliasApi;
  conceptDispositions: ConceptDispositionApi;
  conceptRevisions: ConceptRevisionApi;
  taxonomys: TaxonomyApi;
  decisionCases: DecisionCaseApi;
  decisionElectors: DecisionElectorApi;
  decisionEvents: DecisionEventApi;
  decisionOptions: DecisionOptionApi;
  decisionOutcomes: DecisionOutcomeApi;
  decisionOutcomeMembers: DecisionOutcomeMemberApi;
  decisionResponses: DecisionResponseApi;
  entitlements: EntitlementApi;
  entitlementEnds: EntitlementEndApi;
  entitlementScopes: EntitlementScopeApi;
  obligations: ObligationApi;
  obligationEnds: ObligationEndApi;
  requirementDefinitions: RequirementDefinitionApi;
  rightDefinitions: RightDefinitionApi;
  evaluationExecutors: EvaluationExecutorApi;
  evaluationFinishs: EvaluationFinishApi;
  evaluationRuns: EvaluationRunApi;
  evaluationSets: EvaluationSetApi;
  evaluationStarts: EvaluationStartApi;
  evidenceBundles: EvidenceBundleApi;
  evidenceItems: EvidenceItemApi;
  evidenceMembers: EvidenceMemberApi;
  evidenceSeals: EvidenceSealApi;
  evidenceSources: EvidenceSourceApi;
  identifiers: IdentifierApi;
  identifierDispositions: IdentifierDispositionApi;
  identifierSets: IdentifierSetApi;
  issuers: IssuerApi;
  knowledgeClassifications: KnowledgeClassificationApi;
  knowledgeFeedbacks: KnowledgeFeedbackApi;
  knowledgeFeedbackResults: KnowledgeFeedbackResultApi;
  knowledgeItems: KnowledgeItemApi;
  knowledgePublications: KnowledgePublicationApi;
  knowledgeRevisions: KnowledgeRevisionApi;
  participations: ParticipationApi;
  participationEnds: ParticipationEndApi;
  participationRoles: ParticipationRoleApi;
  participationSets: ParticipationSetApi;
  partys: PartyApi;
  principalRepresentations: PrincipalRepresentationApi;
  representationRevocations: RepresentationRevocationApi;
  candidateEvaluations: CandidateEvaluationApi;
  candidateQualifications: CandidateQualificationApi;
  promotions: PromotionApi;
  publicationChannels: PublicationChannelApi;
  publicationSerieses: PublicationSeriesApi;
  releases: ReleaseApi;
  releaseAudienceLinks: ReleaseAudienceLinkApi;
  releaseCandidates: ReleaseCandidateApi;
  realizations: RealizationApi;
  repositorys: RepositoryApi;
  specificationPins: SpecificationPinApi;
  views: {
  };
  projections: {
  };
  caches: {
  };
  schedules: {
  };
  workflows: {
  };
}

export function createClient(options: ClientOptions): ForgeClient {
  const t = createTransport(options, operations);
  return {
    call: t.call,
    changesets: {
      propose: (input, opts) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/changesets.propose", input, opts)),
      get: (id) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/changesets.get", { id })),
      preview: (id) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/changesets.preview", { id })),
      approve: (id, contentHash) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/changesets.approve", { id, contentHash })),
      commit: (id, opts) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/changesets.commit", { id }, opts)),
    },
    functions: {
    },
    imports: {
      inspect: (input) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/imports.inspect", input)),
      stage: (input) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/imports.stage", input)),
    },
    admin: {
      export: () => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.export", {})),
      import: (snapshot) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.import", { snapshot })),
      verify: (snapshot) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.verify", { snapshot })),
      fence: (on) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.fence", { on })),
      locateSubject: (input) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.subjects.locate", input)),
      inspect: (input) => t.unwrap(t.call("@forgegraph/foundation/knowledge/_/admin.inspect", input)),
    },
    views: {
    },
    projections: {
    },
    caches: {
    },
    schedules: {
    },
    workflows: {
    },
    artifacts: {
    },
    artifactComponents: {
    },
    artifactContents: {
    },
    artifactRevisions: {
    },
    classificationAssignments: {
    },
    classificationRetractions: {
    },
    classificationSets: {
    },
    concepts: {
    },
    conceptAliases: {
    },
    conceptDispositions: {
    },
    conceptRevisions: {
    },
    taxonomys: {
    },
    decisionCases: {
    },
    decisionElectors: {
    },
    decisionEvents: {
    },
    decisionOptions: {
    },
    decisionOutcomes: {
    },
    decisionOutcomeMembers: {
    },
    decisionResponses: {
    },
    entitlements: {
    },
    entitlementEnds: {
    },
    entitlementScopes: {
    },
    obligations: {
    },
    obligationEnds: {
    },
    requirementDefinitions: {
    },
    rightDefinitions: {
    },
    evaluationExecutors: {
    },
    evaluationFinishs: {
    },
    evaluationRuns: {
    },
    evaluationSets: {
    },
    evaluationStarts: {
    },
    evidenceBundles: {
    },
    evidenceItems: {
    },
    evidenceMembers: {
    },
    evidenceSeals: {
    },
    evidenceSources: {
    },
    identifiers: {
    },
    identifierDispositions: {
    },
    identifierSets: {
    },
    issuers: {
    },
    knowledgeClassifications: {
    },
    knowledgeFeedbacks: {
    },
    knowledgeFeedbackResults: {
    },
    knowledgeItems: {
    },
    knowledgePublications: {
    },
    knowledgeRevisions: {
    },
    participations: {
    },
    participationEnds: {
    },
    participationRoles: {
    },
    participationSets: {
    },
    partys: {
    },
    principalRepresentations: {
    },
    representationRevocations: {
    },
    candidateEvaluations: {
    },
    candidateQualifications: {
    },
    promotions: {
    },
    publicationChannels: {
    },
    publicationSerieses: {
    },
    releases: {
    },
    releaseAudienceLinks: {
    },
    releaseCandidates: {
    },
    realizations: {
      create: (input, opts) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Realization.create", input, opts)),
      get: (id) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Realization.get", { id })),
      listAll: (params, page) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Realization.list.all", { params, ...page })),
      listByPin: (params, page) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Realization.list.byPin", { params, ...page })),
    },
    repositorys: {
      create: (input, opts) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Repository.create", input, opts)),
      get: (id) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Repository.get", { id })),
      update: (id, expectedVersion, patch, opts) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Repository.update", { id, expectedVersion, patch }, opts)),
      delete: (id, expectedVersion, opts) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Repository.delete", { id, expectedVersion }, opts)),
      findByKey: (params) => t.unwrapNullable(t.call("@forgegraph/foundation/specification/_/Repository.find.byKey", { params })),
      listAll: (params, page) => t.unwrap(t.call("@forgegraph/foundation/specification/_/Repository.list.all", { params, ...page })),
    },
    specificationPins: {
      create: (input, opts) => t.unwrap(t.call("@forgegraph/foundation/specification/_/SpecificationPin.create", input, opts)),
      get: (id) => t.unwrap(t.call("@forgegraph/foundation/specification/_/SpecificationPin.get", { id })),
      findByRepositoryAnchorRevision: (params) => t.unwrapNullable(t.call("@forgegraph/foundation/specification/_/SpecificationPin.find.byRepositoryAnchorRevision", { params })),
      listAll: (params, page) => t.unwrap(t.call("@forgegraph/foundation/specification/_/SpecificationPin.list.all", { params, ...page })),
      listByRepositoryAnchor: (params, page) => t.unwrap(t.call("@forgegraph/foundation/specification/_/SpecificationPin.list.byRepositoryAnchor", { params, ...page })),
    },
  };
}
