-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE country_address (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "country" TEXT NOT NULL,
  "street" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, country) REFERENCES code_revision (tenant, id)
);

CREATE TABLE currency_amount (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "currency" TEXT NOT NULL,
  "minor_units" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, currency) REFERENCES code_revision (tenant, id)
);

CREATE TABLE industry_registration (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "industry" TEXT NOT NULL,
  "business_name" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, industry) REFERENCES code_revision (tenant, id)
);

CREATE TABLE artifact (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_component (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  "next" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE artifact_content (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "upload_state" TEXT NOT NULL,
  "media_type" TEXT,
  "byte_count" INTEGER,
  "digest" TEXT,
  "upload_attempt" INTEGER,
  "staged_media_type" TEXT,
  "staged_byte_count" INTEGER,
  "content_generation" INTEGER,
  "sealed_generation" TEXT,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "artifact" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "media_type" TEXT NOT NULL,
  "byte_count" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "realization" TEXT,
  "components" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, artifact) REFERENCES artifact (tenant, id),
  FOREIGN KEY (tenant, content) REFERENCES artifact_content (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, realization) REFERENCES realization (tenant, id),
  FOREIGN KEY (tenant, components) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE classification_assignment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "classifications" TEXT NOT NULL,
  "meaning" TEXT NOT NULL,
  "recorded_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, classifications) REFERENCES classification_set (tenant, id),
  FOREIGN KEY (tenant, meaning) REFERENCES concept_revision (tenant, id)
);

CREATE TABLE classification_retraction (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "assignment" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, assignment) REFERENCES classification_assignment (tenant, id)
);

CREATE TABLE classification_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE concept (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "taxonomy" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "identifiers" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "parent" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, taxonomy) REFERENCES taxonomy (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id),
  FOREIGN KEY (tenant, parent) REFERENCES concept (tenant, id)
);

CREATE TABLE concept_alias (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "taxonomy" TEXT NOT NULL,
  "alias" TEXT NOT NULL,
  "meaning" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, taxonomy) REFERENCES taxonomy (tenant, id),
  FOREIGN KEY (tenant, meaning) REFERENCES concept_revision (tenant, id)
);

CREATE TABLE concept_disposition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "concept" TEXT NOT NULL,
  "replacement" TEXT,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, concept) REFERENCES concept (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES concept_revision (tenant, id)
);

CREATE TABLE concept_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "concept" TEXT NOT NULL,
  "taxonomy" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "revision" INTEGER NOT NULL,
  "previous" TEXT,
  "parent_meaning" TEXT,
  "label" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, concept) REFERENCES concept (tenant, id),
  FOREIGN KEY (tenant, taxonomy) REFERENCES taxonomy (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES concept_revision (tenant, id),
  FOREIGN KEY (tenant, parent_meaning) REFERENCES concept_revision (tenant, id)
);

CREATE TABLE taxonomy (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "identifiers" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id)
);

CREATE TABLE code (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "literal" TEXT NOT NULL,
  "identifiers" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, domain) REFERENCES coded_domain (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id)
);

CREATE TABLE code_disposition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "replacement" TEXT,
  "replacement_code" TEXT,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "support" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, code) REFERENCES code (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES code_revision (tenant, id),
  FOREIGN KEY (tenant, replacement_code) REFERENCES code (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE code_label (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "locale" TEXT NOT NULL,
  "revision" INTEGER NOT NULL,
  "previous" TEXT,
  "label" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, code) REFERENCES code (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES code_label (tenant, id)
);

CREATE TABLE code_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "release" TEXT NOT NULL,
  "release_ordinal" INTEGER NOT NULL,
  "revision" INTEGER NOT NULL,
  "previous" TEXT,
  "definition" TEXT NOT NULL,
  "meaning" TEXT,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "source" TEXT NOT NULL,
  "support" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, code) REFERENCES code (tenant, id),
  FOREIGN KEY (tenant, release) REFERENCES domain_release (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES code_revision (tenant, id),
  FOREIGN KEY (tenant, meaning) REFERENCES concept_revision (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE coded_domain (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "authority" TEXT NOT NULL,
  "context" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "identifiers" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, authority) REFERENCES issuer (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id)
);

CREATE TABLE concept_mapping (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "concept" TEXT NOT NULL,
  "authority" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, code) REFERENCES code (tenant, id),
  FOREIGN KEY (tenant, concept) REFERENCES concept (tenant, id),
  FOREIGN KEY (tenant, authority) REFERENCES issuer (tenant, id)
);

CREATE TABLE domain_release (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "version" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "previous" TEXT,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "source" TEXT NOT NULL,
  "support" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, domain) REFERENCES coded_domain (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES domain_release (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE mapping_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "mapping" TEXT NOT NULL,
  "revision" INTEGER NOT NULL,
  "previous" TEXT,
  "code_revision" TEXT NOT NULL,
  "meaning" TEXT NOT NULL,
  "relation" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "source" TEXT NOT NULL,
  "support" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, mapping) REFERENCES concept_mapping (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES mapping_revision (tenant, id),
  FOREIGN KEY (tenant, code_revision) REFERENCES code_revision (tenant, id),
  FOREIGN KEY (tenant, meaning) REFERENCES concept_revision (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE release_withdrawal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "release" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "support" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, release) REFERENCES domain_release (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "predecessor" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, predecessor) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evidence_item (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "source_record" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "revision" TEXT,
  "digest" TEXT,
  "provenance" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES evidence_source (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id)
);

CREATE TABLE evidence_member (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "item" TEXT NOT NULL,
  "next" TEXT,
  "depth" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, item) REFERENCES evidence_item (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_seal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "head" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, head) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_source (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE identifier (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier_set" TEXT NOT NULL,
  "namespace" TEXT NOT NULL,
  "issuer" TEXT,
  "issuer_scope" TEXT NOT NULL,
  "value_" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier_set) REFERENCES identifier_set (tenant, id),
  FOREIGN KEY (tenant, issuer) REFERENCES issuer (tenant, id)
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier" TEXT NOT NULL,
  "replacement" TEXT,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier) REFERENCES identifier (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES identifier (tenant, id)
);

CREATE TABLE identifier_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE issuer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE realization (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "build_hash" TEXT NOT NULL,
  "manifest_digest" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE repository (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "locator" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE specification_pin (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "anchor" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, repository) REFERENCES repository (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX artifact_uq_key ON artifact (tenant, key_);
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision (tenant, content);
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision (tenant, artifact, id);
CREATE UNIQUE INDEX classification_assignment_uq_classifications_meaning ON classification_assignment (tenant, classifications, meaning);
CREATE INDEX classification_assignment_ix_by_classifications ON classification_assignment (tenant, classifications, id);
CREATE UNIQUE INDEX classification_retraction_uq_assignment ON classification_retraction (tenant, assignment);
CREATE UNIQUE INDEX concept_uq_identifiers ON concept (tenant, identifiers);
CREATE UNIQUE INDEX concept_uq_taxonomy_ordinal ON concept (tenant, taxonomy, ordinal);
CREATE INDEX concept_ix_by_taxonomy ON concept (tenant, taxonomy, ordinal, id);
CREATE UNIQUE INDEX concept_alias_uq_taxonomy_alias ON concept_alias (tenant, taxonomy, alias);
CREATE UNIQUE INDEX concept_disposition_uq_concept ON concept_disposition (tenant, concept);
CREATE UNIQUE INDEX concept_revision_uq_concept_revision ON concept_revision (tenant, concept, revision);
CREATE INDEX concept_revision_ix_by_concept ON concept_revision (tenant, concept, revision, id);
CREATE UNIQUE INDEX taxonomy_uq_key ON taxonomy (tenant, key_);
CREATE UNIQUE INDEX code_uq_domain_literal ON code (tenant, domain, literal);
CREATE UNIQUE INDEX code_uq_domain_ordinal ON code (tenant, domain, ordinal);
CREATE UNIQUE INDEX code_uq_identifiers ON code (tenant, identifiers);
CREATE UNIQUE INDEX code_disposition_uq_code ON code_disposition (tenant, code);
CREATE UNIQUE INDEX code_label_uq_code_locale_revision ON code_label (tenant, code, locale, revision);
CREATE UNIQUE INDEX code_label_uq_previous ON code_label (tenant, previous);
CREATE UNIQUE INDEX code_revision_uq_code_release ON code_revision (tenant, code, release);
CREATE UNIQUE INDEX code_revision_uq_code_revision ON code_revision (tenant, code, revision);
CREATE UNIQUE INDEX code_revision_uq_previous ON code_revision (tenant, previous);
CREATE UNIQUE INDEX coded_domain_uq_authority_context_key ON coded_domain (tenant, authority, context, key_);
CREATE UNIQUE INDEX coded_domain_uq_identifiers ON coded_domain (tenant, identifiers);
CREATE UNIQUE INDEX concept_mapping_uq_code_concept_authority ON concept_mapping (tenant, code, concept, authority);
CREATE UNIQUE INDEX domain_release_uq_domain_ordinal ON domain_release (tenant, domain, ordinal);
CREATE UNIQUE INDEX domain_release_uq_domain_version ON domain_release (tenant, domain, version);
CREATE UNIQUE INDEX domain_release_uq_previous ON domain_release (tenant, previous);
CREATE UNIQUE INDEX mapping_revision_uq_mapping_revision ON mapping_revision (tenant, mapping, revision);
CREATE UNIQUE INDEX mapping_revision_uq_previous ON mapping_revision (tenant, previous);
CREATE UNIQUE INDEX release_withdrawal_uq_release ON release_withdrawal (tenant, release);
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle (tenant, key_);
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item (tenant, bundle, source, source_record);
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item (tenant, bundle, id);
CREATE INDEX evidence_item_ix_by_source ON evidence_item (tenant, source, id);
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal (tenant, bundle);
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source (tenant, key_);
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier (tenant, namespace, issuer_scope, value_);
CREATE INDEX identifier_ix_by_identifier_set ON identifier (tenant, identifier_set, id);
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition (tenant, identifier);
CREATE UNIQUE INDEX issuer_uq_key ON issuer (tenant, key_);
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization (tenant, pin, build_hash, manifest_digest);
CREATE INDEX realization_ix_by_pin ON realization (tenant, pin, id);
CREATE UNIQUE INDEX repository_uq_key ON repository (tenant, key_);
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin (tenant, repository, anchor, revision);
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin (tenant, repository, anchor, id);
