-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE credential_details (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "qualification" TEXT NOT NULL,
  "credential_number" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, qualification) REFERENCES qualification (tenant, id)
);

CREATE TABLE runner (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "machine_name" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id)
);

CREATE TABLE runner_requirement (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "requirement" TEXT NOT NULL,
  "runtime_name" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, requirement) REFERENCES qualification_requirement (tenant, id)
);

CREATE TABLE technician (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "person" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, person) REFERENCES party_subject (tenant, id)
);

CREATE TABLE vendor (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "organization" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, organization) REFERENCES party_subject (tenant, id)
);

CREATE TABLE artifact (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_component (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  "next" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE artifact_content (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "upload_state" TEXT NOT NULL,
  "media_type" TEXT,
  "byte_count" INTEGER,
  "digest" TEXT,
  "upload_attempt" INTEGER,
  "staged_media_type" TEXT,
  "staged_byte_count" INTEGER,
  "content_generation" INTEGER,
  "sealed_generation" TEXT,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "artifact" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "media_type" TEXT NOT NULL,
  "byte_count" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "realization" TEXT,
  "components" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, artifact) REFERENCES artifact (tenant, id),
  FOREIGN KEY (tenant, content) REFERENCES artifact_content (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, realization) REFERENCES realization (tenant, id),
  FOREIGN KEY (tenant, components) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "predecessor" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, predecessor) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evidence_item (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "source_record" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "revision" TEXT,
  "digest" TEXT,
  "provenance" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES evidence_source (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id)
);

CREATE TABLE evidence_member (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "item" TEXT NOT NULL,
  "next" TEXT,
  "depth" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, item) REFERENCES evidence_item (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_seal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "head" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, head) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_source (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE identifier (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier_set" TEXT NOT NULL,
  "namespace" TEXT NOT NULL,
  "issuer" TEXT,
  "issuer_scope" TEXT NOT NULL,
  "value_" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier_set) REFERENCES identifier_set (tenant, id),
  FOREIGN KEY (tenant, issuer) REFERENCES issuer (tenant, id)
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier" TEXT NOT NULL,
  "replacement" TEXT,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier) REFERENCES identifier (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES identifier (tenant, id)
);

CREATE TABLE identifier_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE issuer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE party (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "identifiers" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id)
);

CREATE TABLE principal_representation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "party" TEXT NOT NULL,
  "principal" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, party) REFERENCES party (tenant, id)
);

CREATE TABLE representation_revocation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "representation" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, representation) REFERENCES principal_representation (tenant, id)
);

CREATE TABLE party_subject (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "party" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id),
  FOREIGN KEY (tenant, party) REFERENCES party (tenant, id)
);

CREATE TABLE qualification (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "level" TEXT,
  "issuer" TEXT NOT NULL,
  "issuer_record" TEXT NOT NULL,
  "issued_at" TEXT NOT NULL,
  "expires_at" TEXT,
  "support" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id),
  FOREIGN KEY (tenant, level) REFERENCES qualification_level (tenant, id),
  FOREIGN KEY (tenant, issuer) REFERENCES party (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE qualification_definition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE qualification_level (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "rank" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id)
);

CREATE TABLE qualification_requirement (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "minimum_level" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id),
  FOREIGN KEY (tenant, minimum_level) REFERENCES qualification_level (tenant, id)
);

CREATE TABLE qualification_revocation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "qualification" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, qualification) REFERENCES qualification (tenant, id)
);

CREATE TABLE qualification_subject (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE realization (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "build_hash" TEXT NOT NULL,
  "manifest_digest" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE repository (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "locator" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE specification_pin (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "anchor" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, repository) REFERENCES repository (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX credential_details_uq_qualification ON credential_details (tenant, qualification);
CREATE UNIQUE INDEX runner_uq_subject ON runner (tenant, subject);
CREATE UNIQUE INDEX technician_uq_person ON technician (tenant, person);
CREATE UNIQUE INDEX vendor_uq_organization ON vendor (tenant, organization);
CREATE UNIQUE INDEX artifact_uq_key ON artifact (tenant, key_);
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision (tenant, content);
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision (tenant, artifact, id);
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle (tenant, key_);
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item (tenant, bundle, source, source_record);
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item (tenant, bundle, id);
CREATE INDEX evidence_item_ix_by_source ON evidence_item (tenant, source, id);
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal (tenant, bundle);
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source (tenant, key_);
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier (tenant, namespace, issuer_scope, value_);
CREATE INDEX identifier_ix_by_identifier_set ON identifier (tenant, identifier_set, id);
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition (tenant, identifier);
CREATE UNIQUE INDEX issuer_uq_key ON issuer (tenant, key_);
CREATE UNIQUE INDEX party_uq_identifiers ON party (tenant, identifiers);
CREATE UNIQUE INDEX principal_representation_uq_principal_party_validFrom ON principal_representation (tenant, principal, party, valid_from);
CREATE INDEX principal_representation_ix_by_party ON principal_representation (tenant, party, id);
CREATE INDEX principal_representation_ix_by_principal ON principal_representation (tenant, principal, id);
CREATE UNIQUE INDEX representation_revocation_uq_representation ON representation_revocation (tenant, representation);
CREATE UNIQUE INDEX party_subject_uq_party ON party_subject (tenant, party);
CREATE UNIQUE INDEX party_subject_uq_subject ON party_subject (tenant, subject);
CREATE UNIQUE INDEX qualification_uq_issuer_issuerRecord ON qualification (tenant, issuer, issuer_record);
CREATE INDEX qualification_ix_by_subject ON qualification (tenant, subject, id);
CREATE UNIQUE INDEX qualification_definition_uq_key_pin ON qualification_definition (tenant, key_, pin);
CREATE UNIQUE INDEX qualification_level_uq_definition_code ON qualification_level (tenant, definition, code);
CREATE UNIQUE INDEX qualification_level_uq_definition_rank ON qualification_level (tenant, definition, rank);
CREATE UNIQUE INDEX qualification_revocation_uq_qualification ON qualification_revocation (tenant, qualification);
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization (tenant, pin, build_hash, manifest_digest);
CREATE INDEX realization_ix_by_pin ON realization (tenant, pin, id);
CREATE UNIQUE INDEX repository_uq_key ON repository (tenant, key_);
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin (tenant, repository, anchor, revision);
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin (tenant, repository, anchor, id);
