[package]
name = "@foundation-app/levelforge"
version = "0.1.0"
edition = "2027"
[dependencies.evaluation]
path = "../../../../packages/foundation/evaluation"
deploy = true
[dependencies.specification]
path = "../../../../packages/foundation/specification"
deploy = true
