-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE allocation_pool (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "mode" TEXT COLLATE "C" NOT NULL,
  "capacity" BIGINT NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE allocation_reservation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pool" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  "hold_until" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pool") REFERENCES allocation_pool ("tenant", "id")
);

CREATE TABLE allocation_journal (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pool" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "command_key" TEXT COLLATE "C" NOT NULL,
  "previous" TEXT COLLATE "C",
  "reservation" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "action" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pool") REFERENCES allocation_pool ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES allocation_journal ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES allocation_reservation ("tenant", "id")
);

CREATE TABLE artifact (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE artifact_content (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  "upload_state" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C",
  "byte_count" BIGINT,
  "digest" TEXT COLLATE "C",
  "upload_attempt" BIGINT,
  "staged_media_type" TEXT COLLATE "C",
  "staged_byte_count" BIGINT,
  "content_generation" BIGINT,
  "sealed_generation" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE attestation_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE availability_calendar (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE availability_rule_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "calendar" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "calendar") REFERENCES availability_calendar ("tenant", "id")
);

CREATE TABLE availability_rule (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "rule_set" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "weekday" BIGINT,
  "local_date" TEXT COLLATE "C",
  "start_minute" BIGINT,
  "end_minute" BIGINT,
  "available" BIGINT NOT NULL,
  "from_" TEXT COLLATE "C",
  "until" TEXT COLLATE "C",
  "priority" BIGINT,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "rule_set") REFERENCES availability_rule_set ("tenant", "id")
);

CREATE TABLE evaluation_executor (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evaluation_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evidence_source (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE fulfillment_executor (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE fulfillment_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE issuer (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE identifier (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier_set" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C",
  "issuer_scope" TEXT COLLATE "C" NOT NULL,
  "value_" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier_set") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES issuer ("tenant", "id")
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifier" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifier") REFERENCES identifier ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES identifier ("tenant", "id")
);

CREATE TABLE lineage_graph (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE lineage_node (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "graph" TEXT COLLATE "C" NOT NULL,
  "rank" BIGINT NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "graph") REFERENCES lineage_graph ("tenant", "id")
);

CREATE TABLE metric_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE participation_role (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE participation_set (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE party (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id")
);

CREATE TABLE attestation_party_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id")
);

CREATE TABLE participation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation_set" TEXT COLLATE "C" NOT NULL,
  "participant" TEXT COLLATE "C" NOT NULL,
  "role" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation_set") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "role") REFERENCES participation_role ("tenant", "id")
);

CREATE TABLE participation_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "revoked" BIGINT NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation") REFERENCES participation ("tenant", "id")
);

CREATE TABLE decision_elector (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation" TEXT COLLATE "C" NOT NULL,
  "ended" TEXT COLLATE "C",
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation") REFERENCES participation ("tenant", "id"),
  FOREIGN KEY ("tenant", "ended") REFERENCES participation_end ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES decision_elector ("tenant", "id")
);

CREATE TABLE principal_representation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  "principal" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id")
);

CREATE TABLE representation_revocation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "representation" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "representation") REFERENCES principal_representation ("tenant", "id")
);

CREATE TABLE place (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "parent" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "parent") REFERENCES place ("tenant", "id")
);

CREATE TABLE place_address_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C" NOT NULL,
  "revision" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "line1" TEXT COLLATE "C" NOT NULL,
  "line2" TEXT COLLATE "C",
  "locality" TEXT COLLATE "C" NOT NULL,
  "region" TEXT COLLATE "C",
  "postal_code" TEXT COLLATE "C",
  "country_code" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES place_address_revision ("tenant", "id")
);

CREATE TABLE place_timezone_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C" NOT NULL,
  "revision" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "zone" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES place_timezone_revision ("tenant", "id")
);

CREATE TABLE qualification_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE attestation_qualification_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "qualification_subject" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "qualification_subject") REFERENCES qualification_subject ("tenant", "id")
);

CREATE TABLE party_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES qualification_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id")
);

CREATE TABLE resource_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE relation_scope (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES resource_subject ("tenant", "id")
);

CREATE TABLE repository (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "provider" TEXT COLLATE "C" NOT NULL,
  "locator" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE specification_pin (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "repository" TEXT COLLATE "C" NOT NULL,
  "anchor" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "repository") REFERENCES repository ("tenant", "id")
);

CREATE TABLE availability_calendar_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "calendar" TEXT COLLATE "C" NOT NULL,
  "rule_set" TEXT COLLATE "C" NOT NULL,
  "rule_count" BIGINT NOT NULL,
  "rules_digest" TEXT COLLATE "C" NOT NULL,
  "timezone" TEXT COLLATE "C" NOT NULL,
  "timezone_data_version" TEXT COLLATE "C" NOT NULL,
  "origin" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "calendar") REFERENCES availability_calendar ("tenant", "id"),
  FOREIGN KEY ("tenant", "rule_set") REFERENCES availability_rule_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "origin") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE demand_group (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "member_count" BIGINT NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "constraints" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C",
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "constraints") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id")
);

CREATE TABLE evaluation_run (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "evaluation_set" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "executor" TEXT COLLATE "C" NOT NULL,
  "parent" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation_set") REFERENCES evaluation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "executor") REFERENCES evaluation_executor ("tenant", "id"),
  FOREIGN KEY ("tenant", "parent") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE evaluation_quarantine (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "source_digest" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE evaluation_start (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "started_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id")
);

CREATE TABLE intake_form (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "anonymous_allowed" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE stock_item_specification (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE stock_item (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "identifiers" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "serial" TEXT COLLATE "C",
  "lot" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES stock_item_specification ("tenant", "id"),
  FOREIGN KEY ("tenant", "identifiers") REFERENCES identifier_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "serial") REFERENCES resource_subject ("tenant", "id")
);

CREATE TABLE inventory_position (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "item" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C" NOT NULL,
  "custodian" TEXT COLLATE "C" NOT NULL,
  "condition" TEXT COLLATE "C" NOT NULL,
  "pool" TEXT COLLATE "C" NOT NULL,
  "reorder_point" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "item") REFERENCES stock_item ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "custodian") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "pool") REFERENCES allocation_pool ("tenant", "id")
);

CREATE TABLE lineage_relation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "graph" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "target" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C",
  "supersedes" TEXT COLLATE "C",
  "revision" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "graph") REFERENCES lineage_graph ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES lineage_node ("tenant", "id"),
  FOREIGN KEY ("tenant", "target") REFERENCES lineage_node ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "supersedes") REFERENCES lineage_relation ("tenant", "id")
);

CREATE TABLE transformation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "graph" TEXT COLLATE "C" NOT NULL,
  "rank" BIGINT NOT NULL,
  "definition" TEXT COLLATE "C",
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "graph") REFERENCES lineage_graph ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE transformation_input (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "transformation" TEXT COLLATE "C" NOT NULL,
  "node" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "transformation") REFERENCES transformation ("tenant", "id"),
  FOREIGN KEY ("tenant", "node") REFERENCES lineage_node ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES transformation_input ("tenant", "id")
);

CREATE TABLE transformation_output (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "transformation" TEXT COLLATE "C" NOT NULL,
  "node" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "transformation") REFERENCES transformation ("tenant", "id"),
  FOREIGN KEY ("tenant", "node") REFERENCES lineage_node ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES transformation_output ("tenant", "id")
);

CREATE TABLE transformation_seal (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "transformation" TEXT COLLATE "C" NOT NULL,
  "inputs" TEXT COLLATE "C" NOT NULL,
  "outputs" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "transformation") REFERENCES transformation ("tenant", "id"),
  FOREIGN KEY ("tenant", "inputs") REFERENCES transformation_input ("tenant", "id"),
  FOREIGN KEY ("tenant", "outputs") REFERENCES transformation_output ("tenant", "id")
);

CREATE TABLE metric_definition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "dimension" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "semantics" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "semantics") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE metric_objective (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "metric" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "policy" TEXT COLLATE "C" NOT NULL,
  "target" BIGINT NOT NULL,
  "minimum" BIGINT,
  "maximum" BIGINT,
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "metric") REFERENCES metric_definition ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES metric_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "policy") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE operation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE planned_allocation_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "reservation" TEXT COLLATE "C" NOT NULL,
  "previous" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES planned_allocation_link ("tenant", "id")
);

CREATE TABLE qualification_definition (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "pin" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pin") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE qualification_level (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "code" TEXT COLLATE "C" NOT NULL,
  "rank" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES qualification_definition ("tenant", "id")
);

CREATE TABLE qualification_requirement (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "minimum_level" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES qualification_definition ("tenant", "id"),
  FOREIGN KEY ("tenant", "minimum_level") REFERENCES qualification_level ("tenant", "id")
);

CREATE TABLE relation_kind (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "namespace" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE asset_profile (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "attestation_subject" TEXT COLLATE "C" NOT NULL,
  "commissioning_attestation_required" BIGINT NOT NULL,
  "custody_kind" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "resource") REFERENCES resource_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "attestation_subject") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "custody_kind") REFERENCES relation_kind ("tenant", "id")
);

CREATE TABLE maintenance_plan (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "asset" TEXT COLLATE "C" NOT NULL,
  "requirement" TEXT COLLATE "C" NOT NULL,
  "anchor" TEXT COLLATE "C" NOT NULL,
  "interval_days" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "asset") REFERENCES asset_profile ("tenant", "id"),
  FOREIGN KEY ("tenant", "requirement") REFERENCES qualification_requirement ("tenant", "id")
);

CREATE TABLE party_resource_relation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "scope" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT,
  "unit" TEXT COLLATE "C",
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "previous" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES resource_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "kind") REFERENCES relation_kind ("tenant", "id"),
  FOREIGN KEY ("tenant", "scope") REFERENCES relation_scope ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES party_resource_relation ("tenant", "id")
);

CREATE TABLE routing_request (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "requirement" TEXT COLLATE "C" NOT NULL,
  "participants" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "requirement") REFERENCES qualification_requirement ("tenant", "id"),
  FOREIGN KEY ("tenant", "participants") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment_set ("tenant", "id")
);

CREATE TABLE routing_resource (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "party" TEXT COLLATE "C",
  "executor" TEXT COLLATE "C" NOT NULL,
  "pool" TEXT COLLATE "C" NOT NULL,
  "calendar" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES qualification_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "party") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "executor") REFERENCES fulfillment_executor ("tenant", "id"),
  FOREIGN KEY ("tenant", "pool") REFERENCES allocation_pool ("tenant", "id"),
  FOREIGN KEY ("tenant", "calendar") REFERENCES availability_calendar_revision ("tenant", "id")
);

CREATE TABLE scheduling_need (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pool" TEXT COLLATE "C" NOT NULL,
  "calendar" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "participant" TEXT COLLATE "C",
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pool") REFERENCES allocation_pool ("tenant", "id"),
  FOREIGN KEY ("tenant", "calendar") REFERENCES availability_calendar_revision ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES participation ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES scheduling_need ("tenant", "id")
);

CREATE TABLE scheduling_requirement (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "duration_minutes" BIGINT NOT NULL,
  "participants" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C" NOT NULL,
  "head" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participants") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "head") REFERENCES scheduling_need ("tenant", "id")
);

CREATE TABLE candidate_slot (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "requirement" TEXT COLLATE "C" NOT NULL,
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "requirement") REFERENCES scheduling_requirement ("tenant", "id")
);

CREATE TABLE appointment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "slot" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "predecessor" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "slot") REFERENCES candidate_slot ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "predecessor") REFERENCES appointment ("tenant", "id")
);

CREATE TABLE appointment_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "appointment" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "appointment") REFERENCES appointment ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES appointment ("tenant", "id")
);

CREATE TABLE appointment_reservation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "appointment" TEXT COLLATE "C" NOT NULL,
  "reservation" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "appointment") REFERENCES appointment ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES appointment_reservation ("tenant", "id")
);

CREATE TABLE appointment_commit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "appointment" TEXT COLLATE "C" NOT NULL,
  "head" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "appointment") REFERENCES appointment ("tenant", "id"),
  FOREIGN KEY ("tenant", "head") REFERENCES appointment_reservation ("tenant", "id")
);

CREATE TABLE realization (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "pin" TEXT COLLATE "C" NOT NULL,
  "build_hash" TEXT COLLATE "C" NOT NULL,
  "manifest_digest" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "pin") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE usage_dimension (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE usage_source (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE usage_stream (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "dimension" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "dimension") REFERENCES usage_dimension ("tenant", "id")
);

CREATE TABLE operation_run (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "plans" TEXT COLLATE "C",
  "usage_stream" TEXT COLLATE "C" NOT NULL,
  "usage_source" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "plans") REFERENCES planned_allocation_link ("tenant", "id"),
  FOREIGN KEY ("tenant", "usage_stream") REFERENCES usage_stream ("tenant", "id"),
  FOREIGN KEY ("tenant", "usage_source") REFERENCES usage_source ("tenant", "id")
);

CREATE TABLE actual_allocation_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "planned" TEXT COLLATE "C" NOT NULL,
  "reservation" TEXT COLLATE "C" NOT NULL,
  "grant" TEXT COLLATE "C" NOT NULL,
  "previous" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "planned") REFERENCES planned_allocation_link ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "grant") REFERENCES allocation_journal ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES actual_allocation_link ("tenant", "id")
);

CREATE TABLE operation_lineage_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "transformation" TEXT COLLATE "C" NOT NULL,
  "seal" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "transformation") REFERENCES transformation ("tenant", "id"),
  FOREIGN KEY ("tenant", "seal") REFERENCES transformation_seal ("tenant", "id")
);

CREATE TABLE operation_reservation_claim (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "planned" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "planned") REFERENCES planned_allocation_link ("tenant", "id")
);

CREATE TABLE operation_start (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "actual" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "actual") REFERENCES actual_allocation_link ("tenant", "id")
);

CREATE TABLE usage_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "stream" TEXT COLLATE "C" NOT NULL,
  "dimension" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "event_key" TEXT COLLATE "C" NOT NULL,
  "occurred_at" TEXT COLLATE "C",
  "interval_start" TEXT COLLATE "C",
  "interval_end" TEXT COLLATE "C",
  "replacement_for" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "stream") REFERENCES usage_stream ("tenant", "id"),
  FOREIGN KEY ("tenant", "dimension") REFERENCES usage_dimension ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES usage_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement_for") REFERENCES usage_event ("tenant", "id")
);

CREATE TABLE operation_usage_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "event" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "event") REFERENCES usage_event ("tenant", "id")
);

CREATE TABLE usage_correction (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "event" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "event") REFERENCES usage_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES usage_event ("tenant", "id")
);

CREATE TABLE fleet_maintenance (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "vehicle" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE industrial_maintenance (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "machine" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE medical_maintenance (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "device" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE network_maintenance (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "service" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE artifact_component (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "name" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE artifact_revision (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "artifact" TEXT COLLATE "C" NOT NULL,
  "content" TEXT COLLATE "C" NOT NULL,
  "digest" TEXT COLLATE "C" NOT NULL,
  "media_type" TEXT COLLATE "C" NOT NULL,
  "byte_count" BIGINT NOT NULL,
  "specification_pin" TEXT COLLATE "C",
  "realization" TEXT COLLATE "C",
  "components" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "artifact") REFERENCES artifact ("tenant", "id"),
  FOREIGN KEY ("tenant", "content") REFERENCES artifact_content ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification_pin") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "realization") REFERENCES realization ("tenant", "id"),
  FOREIGN KEY ("tenant", "components") REFERENCES artifact_component ("tenant", "id")
);

CREATE TABLE asset_configuration (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "snapshot" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "resource") REFERENCES resource_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "snapshot") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE attestation_artifact_subject (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE submission (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "form" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "submitter" TEXT COLLATE "C",
  "source_key" TEXT COLLATE "C" NOT NULL,
  "submitted_at" TEXT COLLATE "C" NOT NULL,
  "raw" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "form") REFERENCES intake_form ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "submitter") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "raw") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE asset_lifecycle_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "asset" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "action" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C",
  "custody" TEXT COLLATE "C",
  "configuration" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C" NOT NULL,
  "attestation" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "asset") REFERENCES asset_profile ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES asset_lifecycle_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "custody") REFERENCES party_resource_relation ("tenant", "id"),
  FOREIGN KEY ("tenant", "configuration") REFERENCES asset_configuration ("tenant", "id")
);

CREATE TABLE attestation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "issuer_record" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "issued_at" TEXT COLLATE "C" NOT NULL,
  "valid_from" TEXT COLLATE "C" NOT NULL,
  "valid_until" TEXT COLLATE "C",
  "conclusion" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "proof" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES attestation_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "proof") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE attestation_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "attestation" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "attestation") REFERENCES attestation ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES attestation ("tenant", "id")
);

CREATE TABLE qualification_attestation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "qualification" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "issuer" TEXT COLLATE "C" NOT NULL,
  "attestation" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES qualification_definition ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES attestation_qualification_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES attestation_party_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "attestation") REFERENCES attestation ("tenant", "id")
);

CREATE TABLE decision_case (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "participation_set" TEXT COLLATE "C" NOT NULL,
  "eligibility_at" TEXT COLLATE "C" NOT NULL,
  "electors" TEXT COLLATE "C" NOT NULL,
  "rule" TEXT COLLATE "C" NOT NULL,
  "rule_version" TEXT COLLATE "C" NOT NULL,
  "threshold" BIGINT NOT NULL,
  "option_count" BIGINT NOT NULL,
  "deadline" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "evaluation" TEXT COLLATE "C",
  "reconsideration" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "participation_set") REFERENCES participation_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "electors") REFERENCES decision_elector ("tenant", "id"),
  FOREIGN KEY ("tenant", "reconsideration") REFERENCES decision_case ("tenant", "id")
);

CREATE TABLE decision_option (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id")
);

CREATE TABLE decision_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "kind" TEXT COLLATE "C" NOT NULL,
  "response" TEXT COLLATE "C",
  "outcome" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES decision_event ("tenant", "id")
);

CREATE TABLE decision_outcome (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "selected" TEXT COLLATE "C" NOT NULL,
  "responses" TEXT COLLATE "C" NOT NULL,
  "snapshot_digest" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "selected") REFERENCES decision_option ("tenant", "id")
);

CREATE TABLE decision_outcome_member (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES decision_outcome_member ("tenant", "id")
);

CREATE TABLE decision_response (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "decision_case" TEXT COLLATE "C" NOT NULL,
  "voter" TEXT COLLATE "C" NOT NULL,
  "ranking" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "decision_case") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "voter") REFERENCES participation ("tenant", "id")
);

CREATE TABLE demand (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "requester" TEXT COLLATE "C" NOT NULL,
  "specification" TEXT COLLATE "C" NOT NULL,
  "constraints" TEXT COLLATE "C" NOT NULL,
  "origin" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "place" TEXT COLLATE "C",
  "from_" TEXT COLLATE "C" NOT NULL,
  "until" TEXT COLLATE "C" NOT NULL,
  "priority" BIGINT NOT NULL,
  "priority_policy" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "requester") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "constraints") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "place") REFERENCES place ("tenant", "id"),
  FOREIGN KEY ("tenant", "priority_policy") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE demand_allocation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "reservation" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id")
);

CREATE TABLE demand_group_member (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "group_" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "group_") REFERENCES demand_group ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id")
);

CREATE TABLE inventory_reorder (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "position" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "position") REFERENCES inventory_position ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id")
);

CREATE TABLE inventory_reservation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "position" TEXT COLLATE "C" NOT NULL,
  "allocation" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "position") REFERENCES inventory_position ("tenant", "id"),
  FOREIGN KEY ("tenant", "allocation") REFERENCES allocation_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id")
);

CREATE TABLE demand_resolution (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "outcome" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "fulfillment" TEXT COLLATE "C",
  "at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES demand ("tenant", "id")
);

CREATE TABLE demand_route (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "resolution" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "request" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "resolution") REFERENCES demand_resolution ("tenant", "id"),
  FOREIGN KEY ("tenant", "request") REFERENCES routing_request ("tenant", "id")
);

CREATE TABLE demand_schedule (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "resolution" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "appointment" TEXT COLLATE "C" NOT NULL,
  "slot" TEXT COLLATE "C" NOT NULL,
  "requirement" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "resolution") REFERENCES demand_resolution ("tenant", "id"),
  FOREIGN KEY ("tenant", "appointment") REFERENCES appointment ("tenant", "id"),
  FOREIGN KEY ("tenant", "slot") REFERENCES candidate_slot ("tenant", "id"),
  FOREIGN KEY ("tenant", "requirement") REFERENCES scheduling_requirement ("tenant", "id")
);

CREATE TABLE demand_submission (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "submission" TEXT COLLATE "C" NOT NULL,
  "validation" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "submission") REFERENCES submission ("tenant", "id")
);

CREATE TABLE evaluation_finish (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "start" TEXT COLLATE "C",
  "outcome" TEXT COLLATE "C" NOT NULL,
  "finished_at" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "start") REFERENCES evaluation_start ("tenant", "id")
);

CREATE TABLE submission_validation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "submission" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "finish" TEXT COLLATE "C" NOT NULL,
  "verdict" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "submission") REFERENCES submission ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES evaluation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "finish") REFERENCES evaluation_finish ("tenant", "id")
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "predecessor" TEXT COLLATE "C",
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE evidence_item (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "source_record" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "observed_at" TEXT COLLATE "C" NOT NULL,
  "revision" TEXT COLLATE "C",
  "digest" TEXT COLLATE "C",
  "provenance" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES evidence_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id")
);

CREATE TABLE evidence_member (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "item" TEXT COLLATE "C" NOT NULL,
  "next" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "item") REFERENCES evidence_item ("tenant", "id"),
  FOREIGN KEY ("tenant", "next") REFERENCES evidence_member ("tenant", "id")
);

CREATE TABLE evidence_seal (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "bundle" TEXT COLLATE "C" NOT NULL,
  "head" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "bundle") REFERENCES evidence_bundle ("tenant", "id"),
  FOREIGN KEY ("tenant", "head") REFERENCES evidence_member ("tenant", "id")
);

CREATE TABLE fulfillment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "fulfillment_set" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "specification_pin" TEXT COLLATE "C",
  "executor" TEXT COLLATE "C" NOT NULL,
  "requested_at" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment_set") REFERENCES fulfillment_set ("tenant", "id"),
  FOREIGN KEY ("tenant", "specification_pin") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "executor") REFERENCES fulfillment_executor ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE fulfillment_start (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "began_at" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE fulfillment_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "start" TEXT COLLATE "C",
  "outcome" TEXT COLLATE "C" NOT NULL,
  "coverage" TEXT COLLATE "C" NOT NULL,
  "ended_at" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id"),
  FOREIGN KEY ("tenant", "start") REFERENCES fulfillment_start ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE fulfillment_replacement (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "prior" TEXT COLLATE "C" NOT NULL,
  "prior_end" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "prior") REFERENCES fulfillment ("tenant", "id"),
  FOREIGN KEY ("tenant", "prior_end") REFERENCES fulfillment_end ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE fulfillment_task_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "queue" TEXT COLLATE "C" NOT NULL,
  "task" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE inventory_count (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "position" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "position") REFERENCES inventory_position ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE inventory_movement (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "item" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "previous" TEXT COLLATE "C",
  "key_" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "position" TEXT COLLATE "C" NOT NULL,
  "destination" TEXT COLLATE "C",
  "quantity" BIGINT NOT NULL,
  "reservation" TEXT COLLATE "C",
  "count" TEXT COLLATE "C",
  "source" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "item") REFERENCES stock_item ("tenant", "id"),
  FOREIGN KEY ("tenant", "previous") REFERENCES inventory_movement ("tenant", "id"),
  FOREIGN KEY ("tenant", "position") REFERENCES inventory_position ("tenant", "id"),
  FOREIGN KEY ("tenant", "destination") REFERENCES inventory_position ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES inventory_reservation ("tenant", "id"),
  FOREIGN KEY ("tenant", "count") REFERENCES inventory_count ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES specification_pin ("tenant", "id")
);

CREATE TABLE inventory_visibility (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "movement" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "related" TEXT COLLATE "C",
  "transaction_" TEXT COLLATE "C",
  "evidence" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "movement") REFERENCES inventory_movement ("tenant", "id"),
  FOREIGN KEY ("tenant", "related") REFERENCES stock_item ("tenant", "id"),
  FOREIGN KEY ("tenant", "transaction_") REFERENCES specification_pin ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE metric_observation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "metric" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "value_" BIGINT NOT NULL,
  "observed_at" TEXT COLLATE "C",
  "from_" TEXT COLLATE "C",
  "until" TEXT COLLATE "C",
  "source" TEXT COLLATE "C" NOT NULL,
  "source_record" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C",
  "operation" TEXT COLLATE "C" NOT NULL,
  "left_" TEXT COLLATE "C",
  "right_" TEXT COLLATE "C",
  "depth" BIGINT NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "metric") REFERENCES metric_definition ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES metric_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES evidence_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id"),
  FOREIGN KEY ("tenant", "left_") REFERENCES metric_observation ("tenant", "id"),
  FOREIGN KEY ("tenant", "right_") REFERENCES metric_observation ("tenant", "id")
);

CREATE TABLE performance_assessment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "objective" TEXT COLLATE "C" NOT NULL,
  "observation" TEXT COLLATE "C" NOT NULL,
  "evaluation" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "objective") REFERENCES metric_objective ("tenant", "id"),
  FOREIGN KEY ("tenant", "observation") REFERENCES metric_observation ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation") REFERENCES evaluation_finish ("tenant", "id")
);

CREATE TABLE metric_breach_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "assessment" TEXT COLLATE "C" NOT NULL,
  "occurred_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "assessment") REFERENCES performance_assessment ("tenant", "id")
);

CREATE TABLE metric_breach_effect (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "breach" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "breach") REFERENCES metric_breach_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE operation_evaluation_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "evaluation" TEXT COLLATE "C" NOT NULL,
  "finish" TEXT COLLATE "C" NOT NULL,
  "support" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation") REFERENCES evaluation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "finish") REFERENCES evaluation_finish ("tenant", "id"),
  FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE operation_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "start" TEXT COLLATE "C" NOT NULL,
  "outcome" TEXT COLLATE "C" NOT NULL,
  "evaluation" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "start") REFERENCES operation_start ("tenant", "id"),
  FOREIGN KEY ("tenant", "evaluation") REFERENCES operation_evaluation_link ("tenant", "id")
);

CREATE TABLE operation_cleanup (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "ended" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "ended") REFERENCES operation_end ("tenant", "id")
);

CREATE TABLE operation_fulfillment_link (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "run" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "run") REFERENCES operation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE qualification (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "subject" TEXT COLLATE "C" NOT NULL,
  "definition" TEXT COLLATE "C" NOT NULL,
  "level" TEXT COLLATE "C",
  "issuer" TEXT COLLATE "C" NOT NULL,
  "issuer_record" TEXT COLLATE "C" NOT NULL,
  "issued_at" TEXT COLLATE "C" NOT NULL,
  "expires_at" TEXT COLLATE "C",
  "support" TEXT COLLATE "C",
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "subject") REFERENCES qualification_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "definition") REFERENCES qualification_definition ("tenant", "id"),
  FOREIGN KEY ("tenant", "level") REFERENCES qualification_level ("tenant", "id"),
  FOREIGN KEY ("tenant", "issuer") REFERENCES party ("tenant", "id"),
  FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE qualification_revocation (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "qualification" TEXT COLLATE "C" NOT NULL,
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "qualification") REFERENCES qualification ("tenant", "id")
);

CREATE TABLE relation_source (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "source_record" TEXT COLLATE "C" NOT NULL,
  "occurred_at" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C" NOT NULL,
  "description" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES evidence_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id")
);

CREATE TABLE relation_commit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "prior" TEXT COLLATE "C",
  "prior_commit" TEXT COLLATE "C",
  "current" TEXT COLLATE "C",
  "effective_at" TEXT COLLATE "C" NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "recorded_by" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "updated_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "prior") REFERENCES party_resource_relation ("tenant", "id"),
  FOREIGN KEY ("tenant", "prior_commit") REFERENCES relation_commit ("tenant", "id"),
  FOREIGN KEY ("tenant", "current") REFERENCES party_resource_relation ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES relation_source ("tenant", "id")
);

CREATE TABLE routing_candidate (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "request" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "qualification" TEXT COLLATE "C" NOT NULL,
  "participant" TEXT COLLATE "C",
  "evaluated_at" TEXT COLLATE "C" NOT NULL,
  "rank" BIGINT NOT NULL,
  "rationale" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "request") REFERENCES routing_request ("tenant", "id"),
  FOREIGN KEY ("tenant", "resource") REFERENCES routing_resource ("tenant", "id"),
  FOREIGN KEY ("tenant", "qualification") REFERENCES qualification ("tenant", "id"),
  FOREIGN KEY ("tenant", "participant") REFERENCES participation ("tenant", "id")
);

CREATE TABLE assignment_offer (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "candidate" TEXT COLLATE "C" NOT NULL,
  "offered_at" TEXT COLLATE "C" NOT NULL,
  "expires_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "candidate") REFERENCES routing_candidate ("tenant", "id")
);

CREATE TABLE assignment (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "request" TEXT COLLATE "C" NOT NULL,
  "offer" TEXT COLLATE "C" NOT NULL,
  "reservation" TEXT COLLATE "C" NOT NULL,
  "accepted_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "request") REFERENCES routing_request ("tenant", "id"),
  FOREIGN KEY ("tenant", "offer") REFERENCES assignment_offer ("tenant", "id"),
  FOREIGN KEY ("tenant", "reservation") REFERENCES allocation_reservation ("tenant", "id")
);

CREATE TABLE maintenance_work_order (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "asset" TEXT COLLATE "C" NOT NULL,
  "trigger" TEXT COLLATE "C" NOT NULL,
  "plan" TEXT COLLATE "C",
  "cycle" BIGINT NOT NULL,
  "demand" TEXT COLLATE "C" NOT NULL,
  "conversion" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  "technician" TEXT COLLATE "C" NOT NULL,
  "requirement" TEXT COLLATE "C" NOT NULL,
  "assignment" TEXT COLLATE "C",
  "appointment" TEXT COLLATE "C",
  "operation" TEXT COLLATE "C",
  "condition" TEXT COLLATE "C",
  "defect" TEXT COLLATE "C",
  "part_count" BIGINT NOT NULL,
  "inspection" TEXT COLLATE "C" NOT NULL,
  "approval" TEXT COLLATE "C" NOT NULL,
  "accepted" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "asset") REFERENCES asset_profile ("tenant", "id"),
  FOREIGN KEY ("tenant", "plan") REFERENCES maintenance_plan ("tenant", "id"),
  FOREIGN KEY ("tenant", "demand") REFERENCES demand ("tenant", "id"),
  FOREIGN KEY ("tenant", "conversion") REFERENCES demand_resolution ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id"),
  FOREIGN KEY ("tenant", "technician") REFERENCES qualification_subject ("tenant", "id"),
  FOREIGN KEY ("tenant", "requirement") REFERENCES qualification_requirement ("tenant", "id"),
  FOREIGN KEY ("tenant", "assignment") REFERENCES assignment ("tenant", "id"),
  FOREIGN KEY ("tenant", "appointment") REFERENCES appointment ("tenant", "id"),
  FOREIGN KEY ("tenant", "operation") REFERENCES operation_fulfillment_link ("tenant", "id"),
  FOREIGN KEY ("tenant", "condition") REFERENCES performance_assessment ("tenant", "id"),
  FOREIGN KEY ("tenant", "defect") REFERENCES evidence_seal ("tenant", "id"),
  FOREIGN KEY ("tenant", "inspection") REFERENCES evaluation_run ("tenant", "id"),
  FOREIGN KEY ("tenant", "approval") REFERENCES decision_case ("tenant", "id"),
  FOREIGN KEY ("tenant", "accepted") REFERENCES decision_option ("tenant", "id")
);

CREATE TABLE maintenance_finish (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "inspection" TEXT COLLATE "C" NOT NULL,
  "evidence" TEXT COLLATE "C" NOT NULL,
  "return_to_service" TEXT COLLATE "C",
  "at" TEXT COLLATE "C" NOT NULL,
  "follow_up" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id"),
  FOREIGN KEY ("tenant", "inspection") REFERENCES evaluation_finish ("tenant", "id"),
  FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id"),
  FOREIGN KEY ("tenant", "return_to_service") REFERENCES asset_lifecycle_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "follow_up") REFERENCES demand ("tenant", "id")
);

CREATE TABLE maintenance_part (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "order_" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "movement" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id"),
  FOREIGN KEY ("tenant", "movement") REFERENCES inventory_movement ("tenant", "id")
);

CREATE TABLE assignment_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "assignment" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "assignment") REFERENCES assignment ("tenant", "id")
);

CREATE TABLE assignment_execution (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "assignment" TEXT COLLATE "C" NOT NULL,
  "fulfillment" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "assignment") REFERENCES assignment ("tenant", "id"),
  FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id")
);

CREATE TABLE assignment_offer_end (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "offer" TEXT COLLATE "C" NOT NULL,
  "outcome" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "offer") REFERENCES assignment_offer ("tenant", "id")
);

ALTER TABLE fleet_maintenance ADD FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id");

ALTER TABLE industrial_maintenance ADD FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id");

ALTER TABLE medical_maintenance ADD FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id");

ALTER TABLE network_maintenance ADD FOREIGN KEY ("tenant", "order_") REFERENCES maintenance_work_order ("tenant", "id");

ALTER TABLE artifact_component ADD FOREIGN KEY ("tenant", "revision") REFERENCES artifact_revision ("tenant", "id");

ALTER TABLE asset_lifecycle_event ADD FOREIGN KEY ("tenant", "evidence") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE asset_lifecycle_event ADD FOREIGN KEY ("tenant", "attestation") REFERENCES attestation ("tenant", "id");

ALTER TABLE attestation ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE qualification_attestation ADD FOREIGN KEY ("tenant", "qualification") REFERENCES qualification ("tenant", "id");

ALTER TABLE decision_case ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE decision_case ADD FOREIGN KEY ("tenant", "evaluation") REFERENCES evaluation_finish ("tenant", "id");

ALTER TABLE decision_event ADD FOREIGN KEY ("tenant", "response") REFERENCES decision_response ("tenant", "id");

ALTER TABLE decision_event ADD FOREIGN KEY ("tenant", "outcome") REFERENCES decision_outcome ("tenant", "id");

ALTER TABLE decision_outcome ADD FOREIGN KEY ("tenant", "responses") REFERENCES decision_outcome_member ("tenant", "id");

ALTER TABLE decision_outcome_member ADD FOREIGN KEY ("tenant", "response") REFERENCES decision_response ("tenant", "id");

ALTER TABLE decision_response ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE demand ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE demand_resolution ADD FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id");

ALTER TABLE demand_route ADD FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id");

ALTER TABLE demand_schedule ADD FOREIGN KEY ("tenant", "fulfillment") REFERENCES fulfillment ("tenant", "id");

ALTER TABLE demand_submission ADD FOREIGN KEY ("tenant", "validation") REFERENCES submission_validation ("tenant", "id");

ALTER TABLE evaluation_finish ADD FOREIGN KEY ("tenant", "support") REFERENCES evidence_seal ("tenant", "id");

ALTER TABLE evidence_bundle ADD FOREIGN KEY ("tenant", "predecessor") REFERENCES evidence_seal ("tenant", "id");

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX fleet_maintenance_uq_order ON fleet_maintenance ("tenant", "order_");
CREATE UNIQUE INDEX industrial_maintenance_uq_order ON industrial_maintenance ("tenant", "order_");
CREATE UNIQUE INDEX medical_maintenance_uq_order ON medical_maintenance ("tenant", "order_");
CREATE UNIQUE INDEX network_maintenance_uq_order ON network_maintenance ("tenant", "order_");
CREATE UNIQUE INDEX allocation_journal_uq_pool_commandKey ON allocation_journal ("tenant", "pool", "command_key");
CREATE UNIQUE INDEX allocation_journal_uq_pool_ordinal ON allocation_journal ("tenant", "pool", "ordinal");
CREATE INDEX allocation_journal_ix_by_pool ON allocation_journal ("tenant", "pool", "ordinal", "id");
CREATE UNIQUE INDEX allocation_pool_uq_key ON allocation_pool ("tenant", "key_");
CREATE UNIQUE INDEX allocation_reservation_uq_pool_key ON allocation_reservation ("tenant", "pool", "key_");
CREATE UNIQUE INDEX artifact_uq_key ON artifact ("tenant", "key_");
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision ("tenant", "content");
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision ("tenant", "artifact", "id");
CREATE UNIQUE INDEX asset_lifecycle_event_uq_asset_ordinal ON asset_lifecycle_event ("tenant", "asset", "ordinal");
CREATE UNIQUE INDEX asset_profile_uq_attestationSubject ON asset_profile ("tenant", "attestation_subject");
CREATE UNIQUE INDEX asset_profile_uq_resource ON asset_profile ("tenant", "resource");
CREATE UNIQUE INDEX attestation_uq_issuer_issuerRecord ON attestation ("tenant", "issuer", "issuer_record");
CREATE UNIQUE INDEX attestation_artifact_subject_uq_revision ON attestation_artifact_subject ("tenant", "revision");
CREATE UNIQUE INDEX attestation_artifact_subject_uq_subject ON attestation_artifact_subject ("tenant", "subject");
CREATE UNIQUE INDEX attestation_end_uq_attestation ON attestation_end ("tenant", "attestation");
CREATE UNIQUE INDEX attestation_party_subject_uq_party ON attestation_party_subject ("tenant", "party");
CREATE UNIQUE INDEX attestation_party_subject_uq_subject ON attestation_party_subject ("tenant", "subject");
CREATE UNIQUE INDEX attestation_qualification_subject_uq_qualificationSubject ON attestation_qualification_subject ("tenant", "qualification_subject");
CREATE UNIQUE INDEX attestation_qualification_subject_uq_subject ON attestation_qualification_subject ("tenant", "subject");
CREATE UNIQUE INDEX qualification_attestation_uq_qualification_attestation ON qualification_attestation ("tenant", "qualification", "attestation");
CREATE INDEX availability_calendar_revision_ix_by_calendar ON availability_calendar_revision ("tenant", "calendar", "id");
CREATE UNIQUE INDEX availability_rule_uq_ruleSet_ordinal ON availability_rule ("tenant", "rule_set", "ordinal");
CREATE UNIQUE INDEX decision_event_uq_decisionCase_ordinal ON decision_event ("tenant", "decision_case", "ordinal");
CREATE UNIQUE INDEX decision_event_uq_kind_response ON decision_event ("tenant", "kind", "response");
CREATE UNIQUE INDEX decision_event_uq_previous ON decision_event ("tenant", "previous");
CREATE UNIQUE INDEX decision_option_uq_decisionCase_ordinal ON decision_option ("tenant", "decision_case", "ordinal");
CREATE UNIQUE INDEX decision_response_uq_decisionCase_voter ON decision_response ("tenant", "decision_case", "voter");
CREATE UNIQUE INDEX demand_uq_key ON demand ("tenant", "key_");
CREATE UNIQUE INDEX demand_allocation_uq_reservation ON demand_allocation ("tenant", "reservation");
CREATE UNIQUE INDEX demand_group_uq_key ON demand_group ("tenant", "key_");
CREATE UNIQUE INDEX demand_group_member_uq_group_demand ON demand_group_member ("tenant", "group_", "demand");
CREATE UNIQUE INDEX demand_group_member_uq_group_ordinal ON demand_group_member ("tenant", "group_", "ordinal");
CREATE INDEX demand_group_member_ix_by_group ON demand_group_member ("tenant", "group_", "id");
CREATE UNIQUE INDEX demand_resolution_uq_demand ON demand_resolution ("tenant", "demand");
CREATE UNIQUE INDEX demand_resolution_uq_fulfillment ON demand_resolution ("tenant", "fulfillment");
CREATE UNIQUE INDEX demand_route_uq_request ON demand_route ("tenant", "request");
CREATE UNIQUE INDEX demand_schedule_uq_appointment ON demand_schedule ("tenant", "appointment");
CREATE UNIQUE INDEX demand_submission_uq_demand ON demand_submission ("tenant", "demand");
CREATE UNIQUE INDEX demand_submission_uq_submission ON demand_submission ("tenant", "submission");
CREATE UNIQUE INDEX evaluation_executor_uq_key ON evaluation_executor ("tenant", "key_");
CREATE UNIQUE INDEX evaluation_finish_uq_run ON evaluation_finish ("tenant", "run");
CREATE UNIQUE INDEX evaluation_quarantine_uq_run ON evaluation_quarantine ("tenant", "run");
CREATE INDEX evaluation_run_ix_by_definition ON evaluation_run ("tenant", "definition", "id");
CREATE INDEX evaluation_run_ix_by_evaluation_set ON evaluation_run ("tenant", "evaluation_set", "id");
CREATE UNIQUE INDEX evaluation_start_uq_run ON evaluation_start ("tenant", "run");
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle ("tenant", "key_");
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item ("tenant", "bundle", "source", "source_record");
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item ("tenant", "bundle", "id");
CREATE INDEX evidence_item_ix_by_source ON evidence_item ("tenant", "source", "id");
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal ("tenant", "bundle");
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source ("tenant", "key_");
CREATE UNIQUE INDEX fulfillment_uq_fulfillmentSet_ordinal ON fulfillment ("tenant", "fulfillment_set", "ordinal");
CREATE INDEX fulfillment_ix_by_fulfillment_set ON fulfillment ("tenant", "fulfillment_set", "ordinal", "id");
CREATE UNIQUE INDEX fulfillment_end_uq_fulfillment ON fulfillment_end ("tenant", "fulfillment");
CREATE UNIQUE INDEX fulfillment_executor_uq_key ON fulfillment_executor ("tenant", "key_");
CREATE UNIQUE INDEX fulfillment_replacement_uq_prior ON fulfillment_replacement ("tenant", "prior");
CREATE UNIQUE INDEX fulfillment_replacement_uq_replacement ON fulfillment_replacement ("tenant", "replacement");
CREATE UNIQUE INDEX fulfillment_start_uq_fulfillment ON fulfillment_start ("tenant", "fulfillment");
CREATE UNIQUE INDEX fulfillment_task_link_uq_queue_task ON fulfillment_task_link ("tenant", "queue", "task");
CREATE INDEX fulfillment_task_link_ix_by_fulfillment ON fulfillment_task_link ("tenant", "fulfillment", "id");
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier ("tenant", "namespace", "issuer_scope", "value_");
CREATE INDEX identifier_ix_by_identifier_set ON identifier ("tenant", "identifier_set", "id");
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition ("tenant", "identifier");
CREATE UNIQUE INDEX issuer_uq_key ON issuer ("tenant", "key_");
CREATE UNIQUE INDEX submission_uq_form_sourceKey ON submission ("tenant", "form", "source_key");
CREATE INDEX submission_ix_by_form ON submission ("tenant", "form", "id");
CREATE UNIQUE INDEX submission_validation_uq_submission ON submission_validation ("tenant", "submission");
CREATE UNIQUE INDEX inventory_movement_uq_count ON inventory_movement ("tenant", "count");
CREATE UNIQUE INDEX inventory_movement_uq_item_key ON inventory_movement ("tenant", "item", "key_");
CREATE UNIQUE INDEX inventory_movement_uq_item_ordinal ON inventory_movement ("tenant", "item", "ordinal");
CREATE UNIQUE INDEX inventory_position_uq_item_place_custodian_condition ON inventory_position ("tenant", "item", "place", "custodian", "condition");
CREATE UNIQUE INDEX inventory_position_uq_pool ON inventory_position ("tenant", "pool");
CREATE UNIQUE INDEX inventory_reservation_uq_allocation ON inventory_reservation ("tenant", "allocation");
CREATE UNIQUE INDEX stock_item_uq_key ON stock_item ("tenant", "key_");
CREATE UNIQUE INDEX stock_item_uq_serial ON stock_item ("tenant", "serial");
CREATE UNIQUE INDEX stock_item_uq_specification_lot ON stock_item ("tenant", "specification", "lot");
CREATE UNIQUE INDEX stock_item_specification_uq_key ON stock_item_specification ("tenant", "key_");
CREATE UNIQUE INDEX lineage_node_uq_graph_rank ON lineage_node ("tenant", "graph", "rank");
CREATE UNIQUE INDEX lineage_relation_uq_supersedes ON lineage_relation ("tenant", "supersedes");
CREATE INDEX lineage_relation_ix_by_source ON lineage_relation ("tenant", "source", "id");
CREATE INDEX lineage_relation_ix_by_target ON lineage_relation ("tenant", "target", "id");
CREATE UNIQUE INDEX transformation_input_uq_transformation_node ON transformation_input ("tenant", "transformation", "node");
CREATE INDEX transformation_input_ix_by_node ON transformation_input ("tenant", "node", "id");
CREATE INDEX transformation_input_ix_by_transformation ON transformation_input ("tenant", "transformation", "id");
CREATE UNIQUE INDEX transformation_output_uq_transformation_node ON transformation_output ("tenant", "transformation", "node");
CREATE INDEX transformation_output_ix_by_node ON transformation_output ("tenant", "node", "id");
CREATE INDEX transformation_output_ix_by_transformation ON transformation_output ("tenant", "transformation", "id");
CREATE UNIQUE INDEX transformation_seal_uq_transformation ON transformation_seal ("tenant", "transformation");
CREATE UNIQUE INDEX maintenance_finish_uq_order ON maintenance_finish ("tenant", "order_");
CREATE UNIQUE INDEX maintenance_part_uq_movement ON maintenance_part ("tenant", "movement");
CREATE UNIQUE INDEX maintenance_part_uq_order_ordinal ON maintenance_part ("tenant", "order_", "ordinal");
CREATE INDEX maintenance_part_ix_by_order ON maintenance_part ("tenant", "order_", "id");
CREATE UNIQUE INDEX maintenance_work_order_uq_demand ON maintenance_work_order ("tenant", "demand");
CREATE UNIQUE INDEX maintenance_work_order_uq_fulfillment ON maintenance_work_order ("tenant", "fulfillment");
CREATE UNIQUE INDEX maintenance_work_order_uq_key ON maintenance_work_order ("tenant", "key_");
CREATE UNIQUE INDEX maintenance_work_order_uq_plan_cycle ON maintenance_work_order ("tenant", "plan", "cycle");
CREATE INDEX maintenance_work_order_ix_by_asset ON maintenance_work_order ("tenant", "asset", "id");
CREATE UNIQUE INDEX metric_breach_effect_uq_breach_fulfillment ON metric_breach_effect ("tenant", "breach", "fulfillment");
CREATE UNIQUE INDEX metric_breach_event_uq_assessment ON metric_breach_event ("tenant", "assessment");
CREATE UNIQUE INDEX metric_definition_uq_key_definition ON metric_definition ("tenant", "key_", "definition");
CREATE UNIQUE INDEX metric_objective_uq_key ON metric_objective ("tenant", "key_");
CREATE UNIQUE INDEX metric_observation_uq_key ON metric_observation ("tenant", "key_");
CREATE UNIQUE INDEX metric_observation_uq_source_sourceRecord ON metric_observation ("tenant", "source", "source_record");
CREATE UNIQUE INDEX metric_subject_uq_key ON metric_subject ("tenant", "key_");
CREATE UNIQUE INDEX performance_assessment_uq_objective_observation ON performance_assessment ("tenant", "objective", "observation");
CREATE UNIQUE INDEX actual_allocation_link_uq_planned ON actual_allocation_link ("tenant", "planned");
CREATE UNIQUE INDEX operation_uq_key ON operation ("tenant", "key_");
CREATE UNIQUE INDEX operation_cleanup_uq_ended ON operation_cleanup ("tenant", "ended");
CREATE UNIQUE INDEX operation_end_uq_run ON operation_end ("tenant", "run");
CREATE UNIQUE INDEX operation_fulfillment_link_uq_fulfillment ON operation_fulfillment_link ("tenant", "fulfillment");
CREATE INDEX operation_fulfillment_link_ix_by_run ON operation_fulfillment_link ("tenant", "run", "id");
CREATE UNIQUE INDEX operation_reservation_claim_uq_planned ON operation_reservation_claim ("tenant", "planned");
CREATE UNIQUE INDEX operation_run_uq_operation_ordinal ON operation_run ("tenant", "operation", "ordinal");
CREATE UNIQUE INDEX operation_start_uq_run ON operation_start ("tenant", "run");
CREATE UNIQUE INDEX operation_usage_link_uq_event ON operation_usage_link ("tenant", "event");
CREATE UNIQUE INDEX planned_allocation_link_uq_reservation ON planned_allocation_link ("tenant", "reservation");
CREATE UNIQUE INDEX participation_uq_participationSet_participant_role_validFrom ON participation ("tenant", "participation_set", "participant", "role", "valid_from");
CREATE INDEX participation_ix_by_participant ON participation ("tenant", "participant", "id");
CREATE INDEX participation_ix_by_participation_set ON participation ("tenant", "participation_set", "id");
CREATE UNIQUE INDEX participation_end_uq_participation ON participation_end ("tenant", "participation");
CREATE UNIQUE INDEX participation_role_uq_namespace_name ON participation_role ("tenant", "namespace", "name");
CREATE UNIQUE INDEX party_uq_identifiers ON party ("tenant", "identifiers");
CREATE UNIQUE INDEX principal_representation_uq_principal_party_validFrom ON principal_representation ("tenant", "principal", "party", "valid_from");
CREATE INDEX principal_representation_ix_by_party ON principal_representation ("tenant", "party", "id");
CREATE INDEX principal_representation_ix_by_principal ON principal_representation ("tenant", "principal", "id");
CREATE UNIQUE INDEX representation_revocation_uq_representation ON representation_revocation ("tenant", "representation");
CREATE UNIQUE INDEX place_uq_identifiers ON place ("tenant", "identifiers");
CREATE UNIQUE INDEX place_address_revision_uq_place_revision ON place_address_revision ("tenant", "place", "revision");
CREATE INDEX place_address_revision_ix_by_place ON place_address_revision ("tenant", "place", "revision", "id");
CREATE UNIQUE INDEX place_timezone_revision_uq_place_revision ON place_timezone_revision ("tenant", "place", "revision");
CREATE INDEX place_timezone_revision_ix_by_place ON place_timezone_revision ("tenant", "place", "revision", "id");
CREATE UNIQUE INDEX party_subject_uq_party ON party_subject ("tenant", "party");
CREATE UNIQUE INDEX party_subject_uq_subject ON party_subject ("tenant", "subject");
CREATE UNIQUE INDEX qualification_uq_issuer_issuerRecord ON qualification ("tenant", "issuer", "issuer_record");
CREATE INDEX qualification_ix_by_subject ON qualification ("tenant", "subject", "id");
CREATE UNIQUE INDEX qualification_definition_uq_key_pin ON qualification_definition ("tenant", "key_", "pin");
CREATE UNIQUE INDEX qualification_level_uq_definition_code ON qualification_level ("tenant", "definition", "code");
CREATE UNIQUE INDEX qualification_level_uq_definition_rank ON qualification_level ("tenant", "definition", "rank");
CREATE UNIQUE INDEX qualification_revocation_uq_qualification ON qualification_revocation ("tenant", "qualification");
CREATE UNIQUE INDEX party_resource_relation_uq_key ON party_resource_relation ("tenant", "key_");
CREATE INDEX party_resource_relation_ix_by_subject ON party_resource_relation ("tenant", "subject", "id");
CREATE UNIQUE INDEX relation_commit_uq_current ON relation_commit ("tenant", "current");
CREATE UNIQUE INDEX relation_commit_uq_key ON relation_commit ("tenant", "key_");
CREATE UNIQUE INDEX relation_commit_uq_prior ON relation_commit ("tenant", "prior");
CREATE UNIQUE INDEX relation_kind_uq_namespace_name ON relation_kind ("tenant", "namespace", "name");
CREATE UNIQUE INDEX relation_scope_uq_subject_key ON relation_scope ("tenant", "subject", "key_");
CREATE UNIQUE INDEX relation_source_uq_key ON relation_source ("tenant", "key_");
CREATE UNIQUE INDEX resource_subject_uq_key ON resource_subject ("tenant", "key_");
CREATE UNIQUE INDEX assignment_uq_offer ON assignment ("tenant", "offer");
CREATE UNIQUE INDEX assignment_uq_request ON assignment ("tenant", "request");
CREATE UNIQUE INDEX assignment_end_uq_assignment ON assignment_end ("tenant", "assignment");
CREATE UNIQUE INDEX assignment_execution_uq_assignment ON assignment_execution ("tenant", "assignment");
CREATE UNIQUE INDEX assignment_execution_uq_fulfillment ON assignment_execution ("tenant", "fulfillment");
CREATE UNIQUE INDEX assignment_offer_end_uq_offer ON assignment_offer_end ("tenant", "offer");
CREATE INDEX routing_candidate_ix_by_request ON routing_candidate ("tenant", "request", "id");
CREATE UNIQUE INDEX routing_request_uq_key ON routing_request ("tenant", "key_");
CREATE UNIQUE INDEX routing_resource_uq_key ON routing_resource ("tenant", "key_");
CREATE UNIQUE INDEX appointment_uq_key ON appointment ("tenant", "key_");
CREATE UNIQUE INDEX appointment_commit_uq_appointment ON appointment_commit ("tenant", "appointment");
CREATE UNIQUE INDEX appointment_end_uq_appointment ON appointment_end ("tenant", "appointment");
CREATE UNIQUE INDEX scheduling_requirement_uq_key ON scheduling_requirement ("tenant", "key_");
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization ("tenant", "pin", "build_hash", "manifest_digest");
CREATE INDEX realization_ix_by_pin ON realization ("tenant", "pin", "id");
CREATE UNIQUE INDEX repository_uq_key ON repository ("tenant", "key_");
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin ("tenant", "repository", "anchor", "revision");
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin ("tenant", "repository", "anchor", "id");
CREATE UNIQUE INDEX usage_correction_uq_event ON usage_correction ("tenant", "event");
CREATE UNIQUE INDEX usage_dimension_uq_key ON usage_dimension ("tenant", "key_");
CREATE UNIQUE INDEX usage_event_uq_source_eventKey ON usage_event ("tenant", "source", "event_key");
CREATE UNIQUE INDEX usage_event_uq_stream_ordinal ON usage_event ("tenant", "stream", "ordinal");
CREATE INDEX usage_event_ix_by_stream ON usage_event ("tenant", "stream", "ordinal", "id");
CREATE UNIQUE INDEX usage_source_uq_key ON usage_source ("tenant", "key_");
