-- Generated by forgec build; do not edit.
PRAGMA foreign_keys = ON;

CREATE TABLE _forge_assert (
  "op_id" TEXT NOT NULL,
  "satisfied" INTEGER NOT NULL,
  PRIMARY KEY (op_id),
  CONSTRAINT forge_precondition CHECK (satisfied = 1)
);

CREATE TABLE forge_audit (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "record_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "new_version" INTEGER,
  "actor" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "payload" TEXT,
  PRIMARY KEY (tenant, op_id)
);

CREATE TABLE forge_outbox (
  "tenant" TEXT NOT NULL,
  "op_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "lease_owner" TEXT,
  "lease_until" INTEGER,
  "attempts" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "delivered" TEXT,
  "trace" TEXT,
  PRIMARY KEY (tenant, op_id, ordinal)
);

CREATE TABLE forge_processed (
  "tenant" TEXT NOT NULL,
  "subscription" TEXT NOT NULL,
  "message_id" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, subscription, message_id)
);

CREATE TABLE forge_document (
  "tenant" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "body" TEXT NOT NULL,
  PRIMARY KEY (tenant, kind, id)
);

CREATE TABLE forge_receipt (
  "tenant" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "request_hash" TEXT NOT NULL,
  "status" INTEGER NOT NULL,
  "response" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, operation, key)
);

CREATE TABLE allocation_journal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pool" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "command_key" TEXT NOT NULL,
  "previous" TEXT,
  "reservation" TEXT NOT NULL,
  "replacement" TEXT,
  "action" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pool) REFERENCES allocation_pool (tenant, id),
  FOREIGN KEY (tenant, previous) REFERENCES allocation_journal (tenant, id),
  FOREIGN KEY (tenant, reservation) REFERENCES allocation_reservation (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES allocation_reservation (tenant, id)
);

CREATE TABLE allocation_pool (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "mode" TEXT NOT NULL,
  "capacity" INTEGER NOT NULL,
  "unit" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE allocation_reservation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pool" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit" TEXT NOT NULL,
  "from_" TEXT NOT NULL,
  "until" TEXT NOT NULL,
  "hold_until" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pool) REFERENCES allocation_pool (tenant, id)
);

CREATE TABLE artifact (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_component (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  "next" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE artifact_content (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "upload_state" TEXT NOT NULL,
  "media_type" TEXT,
  "byte_count" INTEGER,
  "digest" TEXT,
  "upload_attempt" INTEGER,
  "staged_media_type" TEXT,
  "staged_byte_count" INTEGER,
  "content_generation" INTEGER,
  "sealed_generation" TEXT,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE artifact_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "artifact" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "media_type" TEXT NOT NULL,
  "byte_count" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "realization" TEXT,
  "components" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, artifact) REFERENCES artifact (tenant, id),
  FOREIGN KEY (tenant, content) REFERENCES artifact_content (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, realization) REFERENCES realization (tenant, id),
  FOREIGN KEY (tenant, components) REFERENCES artifact_component (tenant, id)
);

CREATE TABLE availability_calendar (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE availability_calendar_revision (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "calendar" TEXT NOT NULL,
  "rule_set" TEXT NOT NULL,
  "rule_count" INTEGER NOT NULL,
  "rules_digest" TEXT NOT NULL,
  "timezone" TEXT NOT NULL,
  "timezone_data_version" TEXT NOT NULL,
  "origin" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, calendar) REFERENCES availability_calendar (tenant, id),
  FOREIGN KEY (tenant, rule_set) REFERENCES availability_rule_set (tenant, id),
  FOREIGN KEY (tenant, origin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE availability_rule (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "rule_set" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "kind" TEXT NOT NULL,
  "weekday" INTEGER,
  "local_date" TEXT,
  "start_minute" INTEGER,
  "end_minute" INTEGER,
  "available" INTEGER NOT NULL,
  "from_" TEXT,
  "until" TEXT,
  "priority" INTEGER,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, rule_set) REFERENCES availability_rule_set (tenant, id)
);

CREATE TABLE availability_rule_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "calendar" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, calendar) REFERENCES availability_calendar (tenant, id)
);

CREATE TABLE evidence_bundle (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "predecessor" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, predecessor) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE evidence_item (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "source_record" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "revision" TEXT,
  "digest" TEXT,
  "provenance" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, source) REFERENCES evidence_source (tenant, id),
  FOREIGN KEY (tenant, revision) REFERENCES artifact_revision (tenant, id)
);

CREATE TABLE evidence_member (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "item" TEXT NOT NULL,
  "next" TEXT,
  "depth" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, item) REFERENCES evidence_item (tenant, id),
  FOREIGN KEY (tenant, next) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_seal (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "bundle" TEXT NOT NULL,
  "head" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, bundle) REFERENCES evidence_bundle (tenant, id),
  FOREIGN KEY (tenant, head) REFERENCES evidence_member (tenant, id)
);

CREATE TABLE evidence_source (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment_set" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "specification_pin" TEXT,
  "executor" TEXT NOT NULL,
  "requested_at" TEXT NOT NULL,
  "evidence" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment_set) REFERENCES fulfillment_set (tenant, id),
  FOREIGN KEY (tenant, specification_pin) REFERENCES specification_pin (tenant, id),
  FOREIGN KEY (tenant, executor) REFERENCES fulfillment_executor (tenant, id),
  FOREIGN KEY (tenant, evidence) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE fulfillment_end (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "start" TEXT,
  "outcome" TEXT NOT NULL,
  "coverage" TEXT NOT NULL,
  "ended_at" TEXT NOT NULL,
  "evidence" TEXT,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id),
  FOREIGN KEY (tenant, start) REFERENCES fulfillment_start (tenant, id),
  FOREIGN KEY (tenant, evidence) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE fulfillment_executor (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment_replacement (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "prior" TEXT NOT NULL,
  "prior_end" TEXT NOT NULL,
  "replacement" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, prior) REFERENCES fulfillment (tenant, id),
  FOREIGN KEY (tenant, prior_end) REFERENCES fulfillment_end (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE fulfillment_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE fulfillment_start (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "began_at" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE fulfillment_task_link (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "queue" TEXT NOT NULL,
  "task" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE identifier (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier_set" TEXT NOT NULL,
  "namespace" TEXT NOT NULL,
  "issuer" TEXT,
  "issuer_scope" TEXT NOT NULL,
  "value_" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier_set) REFERENCES identifier_set (tenant, id),
  FOREIGN KEY (tenant, issuer) REFERENCES issuer (tenant, id)
);

CREATE TABLE identifier_disposition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "identifier" TEXT NOT NULL,
  "replacement" TEXT,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifier) REFERENCES identifier (tenant, id),
  FOREIGN KEY (tenant, replacement) REFERENCES identifier (tenant, id)
);

CREATE TABLE identifier_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE issuer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE participation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "participation_set" TEXT NOT NULL,
  "participant" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, participation_set) REFERENCES participation_set (tenant, id),
  FOREIGN KEY (tenant, participant) REFERENCES party (tenant, id),
  FOREIGN KEY (tenant, role) REFERENCES participation_role (tenant, id)
);

CREATE TABLE participation_end (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "participation" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "revoked" INTEGER NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, participation) REFERENCES participation (tenant, id)
);

CREATE TABLE participation_role (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "namespace" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE participation_set (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE party (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "identifiers" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, identifiers) REFERENCES identifier_set (tenant, id)
);

CREATE TABLE principal_representation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "party" TEXT NOT NULL,
  "principal" TEXT NOT NULL,
  "valid_from" TEXT NOT NULL,
  "valid_until" TEXT,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, party) REFERENCES party (tenant, id)
);

CREATE TABLE representation_revocation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "representation" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, representation) REFERENCES principal_representation (tenant, id)
);

CREATE TABLE party_subject (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "party" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id),
  FOREIGN KEY (tenant, party) REFERENCES party (tenant, id)
);

CREATE TABLE qualification (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "level" TEXT,
  "issuer" TEXT NOT NULL,
  "issuer_record" TEXT NOT NULL,
  "issued_at" TEXT NOT NULL,
  "expires_at" TEXT,
  "support" TEXT,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id),
  FOREIGN KEY (tenant, level) REFERENCES qualification_level (tenant, id),
  FOREIGN KEY (tenant, issuer) REFERENCES party (tenant, id),
  FOREIGN KEY (tenant, support) REFERENCES evidence_seal (tenant, id)
);

CREATE TABLE qualification_definition (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE qualification_level (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "rank" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id)
);

CREATE TABLE qualification_requirement (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "definition" TEXT NOT NULL,
  "minimum_level" TEXT,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, definition) REFERENCES qualification_definition (tenant, id),
  FOREIGN KEY (tenant, minimum_level) REFERENCES qualification_level (tenant, id)
);

CREATE TABLE qualification_revocation (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "qualification" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, qualification) REFERENCES qualification (tenant, id)
);

CREATE TABLE qualification_subject (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE assignment (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "request" TEXT NOT NULL,
  "offer" TEXT NOT NULL,
  "reservation" TEXT NOT NULL,
  "accepted_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, request) REFERENCES routing_request (tenant, id),
  FOREIGN KEY (tenant, offer) REFERENCES assignment_offer (tenant, id),
  FOREIGN KEY (tenant, reservation) REFERENCES allocation_reservation (tenant, id)
);

CREATE TABLE assignment_end (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "assignment" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, assignment) REFERENCES assignment (tenant, id)
);

CREATE TABLE assignment_execution (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "assignment" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, assignment) REFERENCES assignment (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment (tenant, id)
);

CREATE TABLE assignment_offer (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "candidate" TEXT NOT NULL,
  "offered_at" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, candidate) REFERENCES routing_candidate (tenant, id)
);

CREATE TABLE assignment_offer_end (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "offer" TEXT NOT NULL,
  "outcome" TEXT NOT NULL,
  "at" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, offer) REFERENCES assignment_offer (tenant, id)
);

CREATE TABLE routing_candidate (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "request" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "qualification" TEXT NOT NULL,
  "participant" TEXT,
  "evaluated_at" TEXT NOT NULL,
  "rank" INTEGER NOT NULL,
  "rationale" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, request) REFERENCES routing_request (tenant, id),
  FOREIGN KEY (tenant, resource) REFERENCES routing_resource (tenant, id),
  FOREIGN KEY (tenant, qualification) REFERENCES qualification (tenant, id),
  FOREIGN KEY (tenant, participant) REFERENCES participation (tenant, id)
);

CREATE TABLE routing_request (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "requirement" TEXT NOT NULL,
  "participants" TEXT NOT NULL,
  "fulfillment" TEXT NOT NULL,
  "from_" TEXT NOT NULL,
  "until" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unit" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, requirement) REFERENCES qualification_requirement (tenant, id),
  FOREIGN KEY (tenant, participants) REFERENCES participation_set (tenant, id),
  FOREIGN KEY (tenant, fulfillment) REFERENCES fulfillment_set (tenant, id)
);

CREATE TABLE routing_resource (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "party" TEXT,
  "executor" TEXT NOT NULL,
  "pool" TEXT NOT NULL,
  "calendar" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, subject) REFERENCES qualification_subject (tenant, id),
  FOREIGN KEY (tenant, party) REFERENCES party (tenant, id),
  FOREIGN KEY (tenant, executor) REFERENCES fulfillment_executor (tenant, id),
  FOREIGN KEY (tenant, pool) REFERENCES allocation_pool (tenant, id),
  FOREIGN KEY (tenant, calendar) REFERENCES availability_calendar_revision (tenant, id)
);

CREATE TABLE realization (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "pin" TEXT NOT NULL,
  "build_hash" TEXT NOT NULL,
  "manifest_digest" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, pin) REFERENCES specification_pin (tenant, id)
);

CREATE TABLE repository (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "key_" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "locator" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  PRIMARY KEY (tenant, id)
);

CREATE TABLE specification_pin (
  "tenant" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "repository" TEXT NOT NULL,
  "anchor" TEXT NOT NULL,
  "revision" TEXT NOT NULL,
  PRIMARY KEY (tenant, id),
  FOREIGN KEY (tenant, repository) REFERENCES repository (tenant, id)
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX allocation_journal_uq_pool_commandKey ON allocation_journal (tenant, pool, command_key);
CREATE UNIQUE INDEX allocation_journal_uq_pool_ordinal ON allocation_journal (tenant, pool, ordinal);
CREATE INDEX allocation_journal_ix_by_pool ON allocation_journal (tenant, pool, ordinal, id);
CREATE UNIQUE INDEX allocation_pool_uq_key ON allocation_pool (tenant, key_);
CREATE UNIQUE INDEX allocation_reservation_uq_pool_key ON allocation_reservation (tenant, pool, key_);
CREATE UNIQUE INDEX artifact_uq_key ON artifact (tenant, key_);
CREATE UNIQUE INDEX artifact_revision_uq_content ON artifact_revision (tenant, content);
CREATE INDEX artifact_revision_ix_by_artifact ON artifact_revision (tenant, artifact, id);
CREATE INDEX availability_calendar_revision_ix_by_calendar ON availability_calendar_revision (tenant, calendar, id);
CREATE UNIQUE INDEX availability_rule_uq_ruleSet_ordinal ON availability_rule (tenant, rule_set, ordinal);
CREATE UNIQUE INDEX evidence_bundle_uq_key ON evidence_bundle (tenant, key_);
CREATE UNIQUE INDEX evidence_item_uq_bundle_source_sourceRecord ON evidence_item (tenant, bundle, source, source_record);
CREATE INDEX evidence_item_ix_by_bundle ON evidence_item (tenant, bundle, id);
CREATE INDEX evidence_item_ix_by_source ON evidence_item (tenant, source, id);
CREATE UNIQUE INDEX evidence_seal_uq_bundle ON evidence_seal (tenant, bundle);
CREATE UNIQUE INDEX evidence_source_uq_key ON evidence_source (tenant, key_);
CREATE UNIQUE INDEX fulfillment_uq_fulfillmentSet_ordinal ON fulfillment (tenant, fulfillment_set, ordinal);
CREATE INDEX fulfillment_ix_by_fulfillment_set ON fulfillment (tenant, fulfillment_set, ordinal, id);
CREATE UNIQUE INDEX fulfillment_end_uq_fulfillment ON fulfillment_end (tenant, fulfillment);
CREATE UNIQUE INDEX fulfillment_executor_uq_key ON fulfillment_executor (tenant, key_);
CREATE UNIQUE INDEX fulfillment_replacement_uq_prior ON fulfillment_replacement (tenant, prior);
CREATE UNIQUE INDEX fulfillment_replacement_uq_replacement ON fulfillment_replacement (tenant, replacement);
CREATE UNIQUE INDEX fulfillment_start_uq_fulfillment ON fulfillment_start (tenant, fulfillment);
CREATE UNIQUE INDEX fulfillment_task_link_uq_queue_task ON fulfillment_task_link (tenant, queue, task);
CREATE INDEX fulfillment_task_link_ix_by_fulfillment ON fulfillment_task_link (tenant, fulfillment, id);
CREATE UNIQUE INDEX identifier_uq_namespace_issuerScope_value ON identifier (tenant, namespace, issuer_scope, value_);
CREATE INDEX identifier_ix_by_identifier_set ON identifier (tenant, identifier_set, id);
CREATE UNIQUE INDEX identifier_disposition_uq_identifier ON identifier_disposition (tenant, identifier);
CREATE UNIQUE INDEX issuer_uq_key ON issuer (tenant, key_);
CREATE UNIQUE INDEX participation_uq_participationSet_participant_role_validFrom ON participation (tenant, participation_set, participant, role, valid_from);
CREATE INDEX participation_ix_by_participant ON participation (tenant, participant, id);
CREATE INDEX participation_ix_by_participation_set ON participation (tenant, participation_set, id);
CREATE UNIQUE INDEX participation_end_uq_participation ON participation_end (tenant, participation);
CREATE UNIQUE INDEX participation_role_uq_namespace_name ON participation_role (tenant, namespace, name);
CREATE UNIQUE INDEX party_uq_identifiers ON party (tenant, identifiers);
CREATE UNIQUE INDEX principal_representation_uq_principal_party_validFrom ON principal_representation (tenant, principal, party, valid_from);
CREATE INDEX principal_representation_ix_by_party ON principal_representation (tenant, party, id);
CREATE INDEX principal_representation_ix_by_principal ON principal_representation (tenant, principal, id);
CREATE UNIQUE INDEX representation_revocation_uq_representation ON representation_revocation (tenant, representation);
CREATE UNIQUE INDEX party_subject_uq_party ON party_subject (tenant, party);
CREATE UNIQUE INDEX party_subject_uq_subject ON party_subject (tenant, subject);
CREATE UNIQUE INDEX qualification_uq_issuer_issuerRecord ON qualification (tenant, issuer, issuer_record);
CREATE INDEX qualification_ix_by_subject ON qualification (tenant, subject, id);
CREATE UNIQUE INDEX qualification_definition_uq_key_pin ON qualification_definition (tenant, key_, pin);
CREATE UNIQUE INDEX qualification_level_uq_definition_code ON qualification_level (tenant, definition, code);
CREATE UNIQUE INDEX qualification_level_uq_definition_rank ON qualification_level (tenant, definition, rank);
CREATE UNIQUE INDEX qualification_revocation_uq_qualification ON qualification_revocation (tenant, qualification);
CREATE UNIQUE INDEX assignment_uq_offer ON assignment (tenant, offer);
CREATE UNIQUE INDEX assignment_uq_request ON assignment (tenant, request);
CREATE UNIQUE INDEX assignment_end_uq_assignment ON assignment_end (tenant, assignment);
CREATE UNIQUE INDEX assignment_execution_uq_assignment ON assignment_execution (tenant, assignment);
CREATE UNIQUE INDEX assignment_execution_uq_fulfillment ON assignment_execution (tenant, fulfillment);
CREATE UNIQUE INDEX assignment_offer_end_uq_offer ON assignment_offer_end (tenant, offer);
CREATE INDEX routing_candidate_ix_by_request ON routing_candidate (tenant, request, id);
CREATE UNIQUE INDEX routing_request_uq_key ON routing_request (tenant, key_);
CREATE UNIQUE INDEX routing_resource_uq_key ON routing_resource (tenant, key_);
CREATE UNIQUE INDEX realization_uq_pin_buildHash_manifestDigest ON realization (tenant, pin, build_hash, manifest_digest);
CREATE INDEX realization_ix_by_pin ON realization (tenant, pin, id);
CREATE UNIQUE INDEX repository_uq_key ON repository (tenant, key_);
CREATE UNIQUE INDEX specification_pin_uq_repository_anchor_revision ON specification_pin (tenant, repository, anchor, revision);
CREATE INDEX specification_pin_ix_by_repository_anchor ON specification_pin (tenant, repository, anchor, id);
