-- Generated by forgec build (PostgreSQL dialect); do not edit.

CREATE TABLE _forge_assert (
  "op_id" TEXT COLLATE "C" NOT NULL,
  "satisfied" BOOLEAN NOT NULL,
  PRIMARY KEY ("op_id"),
  CONSTRAINT forge_precondition CHECK (satisfied)
);

CREATE TABLE forge_audit (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "resource" TEXT COLLATE "C" NOT NULL,
  "record_id" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "new_version" BIGINT,
  "actor" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id")
);

CREATE TABLE forge_outbox (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "op_id" TEXT COLLATE "C" NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "channel" TEXT COLLATE "C" NOT NULL,
  "message" TEXT COLLATE "C" NOT NULL,
  "payload" TEXT COLLATE "C" NOT NULL,
  "status" TEXT COLLATE "C" NOT NULL,
  "lease_owner" TEXT COLLATE "C",
  "lease_until" BIGINT,
  "attempts" BIGINT NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  "delivered" TEXT COLLATE "C",
  "trace" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "op_id", "ordinal")
);

CREATE TABLE forge_processed (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "subscription" TEXT COLLATE "C" NOT NULL,
  "message_id" TEXT COLLATE "C" NOT NULL,
  "at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "subscription", "message_id")
);

CREATE TABLE forge_document (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "kind" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "version" BIGINT NOT NULL,
  "body" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "kind", "id")
);

CREATE TABLE forge_receipt (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "operation" TEXT COLLATE "C" NOT NULL,
  "key" TEXT COLLATE "C" NOT NULL,
  "request_hash" TEXT COLLATE "C" NOT NULL,
  "status" BIGINT NOT NULL,
  "response" TEXT COLLATE "C" NOT NULL,
  "created_at" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "operation", "key")
);

CREATE TABLE usage_dimension (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE usage_source (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "key_" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id")
);

CREATE TABLE usage_stream (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "label" TEXT COLLATE "C" NOT NULL,
  "dimension" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "dimension") REFERENCES usage_dimension ("tenant", "id")
);

CREATE TABLE usage_event (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "stream" TEXT COLLATE "C" NOT NULL,
  "dimension" TEXT COLLATE "C" NOT NULL,
  "unit" TEXT COLLATE "C" NOT NULL,
  "quantity" BIGINT NOT NULL,
  "ordinal" BIGINT NOT NULL,
  "source" TEXT COLLATE "C" NOT NULL,
  "event_key" TEXT COLLATE "C" NOT NULL,
  "occurred_at" TEXT COLLATE "C",
  "interval_start" TEXT COLLATE "C",
  "interval_end" TEXT COLLATE "C",
  "replacement_for" TEXT COLLATE "C",
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "stream") REFERENCES usage_stream ("tenant", "id"),
  FOREIGN KEY ("tenant", "dimension") REFERENCES usage_dimension ("tenant", "id"),
  FOREIGN KEY ("tenant", "source") REFERENCES usage_source ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement_for") REFERENCES usage_event ("tenant", "id")
);

CREATE TABLE usage_correction (
  "tenant" TEXT COLLATE "C" NOT NULL,
  "id" TEXT COLLATE "C" NOT NULL,
  "event" TEXT COLLATE "C" NOT NULL,
  "replacement" TEXT COLLATE "C",
  "reason" TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY ("tenant", "id"),
  FOREIGN KEY ("tenant", "event") REFERENCES usage_event ("tenant", "id"),
  FOREIGN KEY ("tenant", "replacement") REFERENCES usage_event ("tenant", "id")
);

CREATE INDEX forge_outbox_pending ON forge_outbox (status, lease_until);
CREATE UNIQUE INDEX usage_correction_uq_event ON usage_correction ("tenant", "event");
CREATE UNIQUE INDEX usage_dimension_uq_key ON usage_dimension ("tenant", "key_");
CREATE UNIQUE INDEX usage_event_uq_source_eventKey ON usage_event ("tenant", "source", "event_key");
CREATE UNIQUE INDEX usage_event_uq_stream_ordinal ON usage_event ("tenant", "stream", "ordinal");
CREATE INDEX usage_event_ix_by_stream ON usage_event ("tenant", "stream", "ordinal", "id");
CREATE UNIQUE INDEX usage_source_uq_key ON usage_source ("tenant", "key_");
